### DISCUSSION TITLE
Will the image pull policy changed to IfNotPresent

### DISCUSSION THREAD

**Discussion by alongL** [kubeedge/kubeedge#3789] [General]
in the file  build\agent\kubernetes\edgemesh-agent\05-daemonset.yaml
the image of kubeedge/edgemesh-agent:latest  is pulled default always by default .
```
      containers:
      - name: edgemesh-agent
        securityContext:
          privileged: true
        image: kubeedge/edgemesh-agent:latest
```
In some condition, pull image from docker.io is hard. 
You know GFW.
Shall we change it to IfNotPresent
just add this :
```
         imagePullPolicy: IfNotPresent
```
