### ISSUE TITLE
Failed to run pod on edge node

### ISSUE THREAD

**Issue by cwhuang29** [kubeedge/kubeedge#1213]
**What happened**:
I had installed k8s and every thing works well, then I install KubeEdge, and edge node is ready. However, even I can deploy pods or services on my edge node, the pod can't works properly.
If the pod is deployed on master node, its IP is `10.244.0.30` (starts with 10.244), and I can connect into pod by the command ` kubectl exec <pod_name> -it -- bash` or via Service/rs/rc. But for the pods deployed on edge node, there IP are like `172.17.0.X` (starts with 172), and I can never connect into the pod by exec or via Service/rs/rc
**What you expected to happen**:
pods and services' network connection work properly, so I can do some simple test like run simple web server on container and test them via curl
**How to reproduce it (as minimally and precisely as possible)**:
Install k8s: [Creating a single control-plane cluster with kubeadm](https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)
Install KubeEdge: [Setup KubeEdge from sourcecode](https://docs.kubeedge.io/en/latest/setup/setup.html)
my pod's yaml:
```
apiVersion: v1
kind: Pod
metadata: 
  name: simple-pod-for-edge-2 
  labels:
    app: kubia
    creation_method: manual 
    env: prod
  spec: 
  terminationGracePeriodSeconds: 0 
  containers:
    - name: my-pod-kubia 
    image: cwhuang29/kubia
    ports:
      - containerPort: 8080
      hostPort: 8080
      # protocol: TCP   
```

my Dockerfile:
```
FROM node:7
ADD app.js /app.js
ENTRYPOINT ["node", "app.js"]
```

app.js:
```
const http = require('http');
const os = require('os');

var handler = function(request, response){
	console.log("Received request from " + request.connection.remoteAddress);
	response.writeHead(200); // 200: http status code
	response.end("You've hit " + os.hostname() + "\n");
};
var www = http.createServer(handler);
const myport = parseInt(process.env.PORT) || 8080;
www.listen(myport);
```

**Anything else we need to know?**:
A strange point: after I installed kubeedge, I test a pod which I used to ran in k8s, it deployed successfully on edgenode (STATUS is RUNNING); however, I can't connect into this pod just as described above. Then I notice KubeEdge has a requirment:

> Note: Currently, for edge node, we must use hostPort in the Pod container spec so that the pod comes up normally, or the pod will be always in ContainerCreating status. The hostPort must be equal to containerPort and can not be 0.

so I add `containerPort` on my pod's yaml (as you see above), and after adding containerPort, the pod can't even deploy successfully on edge node (STATUS will be  ContainerCreating)

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`): (command not found)
Cloud & Edge are 2 VMs run on work station, almost every thing of them are same

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): Linux cwhuang-master 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.12.9 linux/amd64
- docker: docker://19.3.2 
- kubeadm: kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:20:51Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**EdgeSide Environment**:
- mosquitto (`mosquitto -v`): mosquitto version 1.4.15
- edgecore version (e.g. `edgecore --version`): (command not found)
- Hardware configuration (e.g. `lscpu`): x86_64
- OS (e.g. `cat /etc/os-release`): Ubuntu 18.04.3 LTS
- Kernel (e.g. `uname -a`): Linux cwhuang-slave1 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): go version go1.12.9 linux/amd64
- docker: docker://19.3.2
- kubeadm: kubeadm version: &version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:20:51Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cwhuang29** [comment]
This is cloud node's project/conf/controller.yaml
```
controller:
  kube:
    master: https://192.168.56.106:6443 # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 10
    kubeconfig: "/home/k8s/.kube/config"
cloudhub:
  protocol_websocket: true # enable websocket protocol
  port: 10000 # open port for websocket server
  protocol_quic: true # enable quic protocol
  quic_port: 10001 # open prot for quic server
  max_incomingstreams: 10000 # the max incoming stream for quic server
  enable_uds: true # enable unix domain socket protocol
  uds_address: unix:///var/lib/kubeedge/kubeedge.sock # unix domain socket address
  address: 0.0.0.0
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
devicecontroller:
  kube:
    master: https://192.168.56.106:6443 # kube-apiserver address (such as:http://localhost:8080)
    namespace: ""
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    kubeconfig: "/home/k8s/.kube/config"
    # Enter path to kubeconfig file to enable https connection to k8s apiserver,if master and kubeconfig are both set, master will override any value in kubeconfig.
```
This is edge node's project/conf/edge.yaml:
```
mqtt:
    server: tcp://127.0.0.1:1883 # external mqtt broker url.
    internal-server: tcp://127.0.0.1:1884 # internal mqtt broker url.
    mode: 2 # 0: internal mqtt broker enable only. 1: internal and external mqtt broker enable. 2: external mqtt broker enable only.
    qos: 0 # 0: QOSAtMostOnce, 1: QOSAtLeastOnce, 2: QOSExactlyOnce.
    retain: false # if the flag set true, server will store the message and can be delivered to future subscribers.
    session-queue-size: 100 # A size of how many sessions will be handled. default to 100.
edgehub:
    websocket:
        url: wss://192.168.56.106:10000/projectidtesting1010/edgenode1010/events
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    quic:
        url: 192.168.56.106:10001
        cafile: /etc/kubeedge/ca/rootCA.crt
        certfile: /etc/kubeedge/certs/edge.crt
        keyfile: /etc/kubeedge/certs/edge.key
        handshake-timeout: 30 #second
        write-deadline: 15 # second
        read-deadline: 15 # second
    controller:
        protocol: websocket # websocket, quic
        heartbeat: 15  # second
        project-id: projectidtesting1010
        node-id: edgenode1010
edged:
    register-node-namespace: default
    hostname-override: edgenode1010
    interface-name: enp0s3 # eth0
    edged-memory-capacity-bytes: 7852396000
    node-status-update-frequency: 10 # second
    device-plugin-enabled: false
    gpu-plugin-enabled: false
    image-gc-high-threshold: 80 # percent
    image-gc-low-threshold: 40 # percent
    maximum-dead-containers-per-container: 1
    docker-address: unix:///var/run/docker.sock
    runtime-type: docker
    remote-runtime-endpoint: unix:///var/run/dockershim.sock
    remote-image-endpoint: unix:///var/run/dockershim.sock
    runtime-request-timeout: 2
    podsandbox-image: kubeedge/pause:3.1 # kubeedge/pause:3.1 for x86 arch , kubeedge/pause-arm:3.1 for arm arch, kubeedge/pause-arm64 for arm64 arch
    image-pull-progress-deadline: 60 # second
    cgroup-driver: cgroupfs
    node-ip: "192.168.56.107"
    cluster-dns: ""
    cluster-domain: ""

mesh:
    loadbalance:
        strategy-name: RoundRobin
```
