### ISSUE TITLE
Cannot use ConfigMap on the edge side

### ISSUE THREAD

**Issue by bitosky** [kubeedge/kubeedge#1282]
**What happened**:

I wrote a yaml file to deploy a standalone spark cluster.

And I use a ConfigMap to save master ip config.

But all of my setting is empty  when I check the edge pod log
(everything is OK on the cloud side)

yaml file:
```yaml
---

apiVersion: v1
kind: Namespace
metadata:
  name: spark-standalone

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: spark-config
  namespace: spark-standalone
data:
  spark_master_ip: "10.4.20.34"
  spark_master_port: "7077"
  spark_master_webui_port: "8080"
  spark_slave_webui_port: "8081"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark-standalone
  labels:
    k8s-app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      name: spark-master
      namespace: spark-standalone
      labels:
        k8s-app: spark-master
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      hostNetwork: true
      containers:
        - name: spark-master
          image: spark:2.4.3
          command: ["/bin/sh","-c"]
          args: 
            - "
              ${SPARK_HOME}/sbin/start-master.sh
              -h 0.0.0.0
              -p ${SPARK_MASTER_PORT}
              --webui-port $(SPARK_MASTER_WEBUI_PORT)
              &&
              tail -f ${SPARK_HOME}/logs/*
              "
          env:
            - name: SPARK_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: spark-config
                  key: spark_master_port
            - name: SPARK_MASTER_WEBUI_PORT
              valueFrom:
                configMapKeyRef:
                  name: spark-config
                  key: spark_master_webui_port
---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: spark-slave
  namespace: spark-standalone
  labels:
    k8s-app: spark-slave
spec:
  selector:
    matchLabels:
      k8s-app: spark-slave
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      name: spark-slave
      namespace: spark-standalone
      labels:
        k8s-app: spark-slave
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: Exists
      hostNetwork: true
      containers:
        - name: spark-slave
          image: spark:2.4.3
          command: ["/bin/sh","-c"]
          args: 
            - "
              ${SPARK_HOME}/sbin/start-slave.sh
              spark://$(SPARK_MASTER_IP):$(SPARK_MASTER_PORT)
              --webui-port $(SPARK_SLAVE_WEBUI_PORT)
              &&
              tail -f ${SPARK_HOME}/logs/*
              "
          env:
            - name: SPARK_MASTER_IP
              valueFrom:
                configMapKeyRef:
                  name: spark-config
                  key: spark_master_ip
            - name: SPARK_MASTER_PORT
              valueFrom:
                configMapKeyRef:
                  name: spark-config
                  key: spark_master_port
            - name: SPARK_SLAVE_WEBUI_PORT
              valueFrom:
                configMapKeyRef:
                  name: spark-config
                  key: spark_slave_webui_port
---
```
edge pod log
```
/bin/sh: SPARK_MASTER_IP: command not found
/bin/sh: SPARK_MASTER_PORT: command not found
/bin/sh: SPARK_SLAVE_WEBUI_PORT: command not found
starting org.apache.spark.deploy.worker.Worker, logging to /opt/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-ubuntu.out
failed to launch: nice -n 0 /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port 8081 spark://: -h 0.0.0.0 --webui-port
  Options:
    -c CORES, --cores CORES  Number of cores to use
    -m MEM, --memory MEM     Amount of memory to use (e.g. 1000M, 2G)
    -d DIR, --work-dir DIR   Directory to run apps in (default: SPARK_HOME/work)
    -i HOST, --ip IP         Hostname to listen on (deprecated, please use --host or -h)
    -h HOST, --host HOST     Hostname to listen on
    -p PORT, --port PORT     Port to listen on (default: random)
    --webui-port PORT        Port for web UI (default: 8081)
    --properties-file FILE   Path to a custom Spark properties file.
                             Default is conf/spark-defaults.conf.
full log in /opt/spark/logs/spark--org.apache.spark.deploy.worker.Worker-1-ubuntu.out
Options:
  -c CORES, --cores CORES  Number of cores to use
  -m MEM, --memory MEM     Amount of memory to use (e.g. 1000M, 2G)
  -d DIR, --work-dir DIR   Directory to run apps in (default: SPARK_HOME/work)
  -i HOST, --ip IP         Hostname to listen on (deprecated, please use --host or -h)
  -h HOST, --host HOST     Hostname to listen on
  -p PORT, --port PORT     Port to listen on (default: random)
  --webui-port PORT        Port for web UI (default: 8081)
  --properties-file FILE   Path to a custom Spark properties file.
                           Default is conf/spark-defaults.conf.

```

`/bin/sh: SPARK_MASTER_IP: command not found` means it's not exists.

**What you expected to happen**:
edge pod get the values of SPARK_MASTER_IP, SPARK_MASTER_PORT, SPARK_SLAVE_WEBUI_PORT

**How to reproduce it (as minimally and precisely as possible)**:
try to use ConfigMap

**Anything else we need to know?**:
On the edge side I failed to config CNI, It's this the reason? 

**Environment**:
- Kubeedge version 1.1.0
- Docker version   19.03.5
- Kubernetes version 1.15.3
