### ISSUE TITLE
keadm supports the ability to convert old configfiles into new config

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1437]
**What would you like to be added/modified**:

currently the kubeedge use new config api to run kubeedge component.  Before the 1.2 version, the old configuration file was used. The format of the new and old configuration files is quite different and incompatible. Need keadm to provide convert function to convert the old configuration file to the new configuration file

ref: #1172 

take cloudcore as an example:

for old config files, there are two files: modules.yaml and controller.yaml

controller.yaml
```
cloudhub:
  protocol_websocket: true # enable websocket protocol
  protocol_quic: true # enable quic protocol
  enable_uds: true # enable unix domain socket protocol
  address: 0.0.0.0
  port: 10000 # open port for websocket server
  quic_port: 10001 # open prot for quic server
  max_incomingstreams: 10000 # the max incoming stream for quic server
  uds_address: unix:///var/lib/kubeedge/kubeedge.sock # unix domain socket address
  keepalive-interval: 30
  write-timeout: 30
  node-limit: 10
  ca: /etc/kubeedge/ca/rootCA.crt
  cert: /etc/kubeedge/certs/edge.crt
  key: /etc/kubeedge/certs/edge.key

controller:
  buffer:
    update-pod-status: 1024 # default
    update-node-status: 1024 # default
    query-configmap: 1024 # default
    query-secret: 1024 # default
    query-service: 1024 # default
    query-endpoints: 1024 # default
    pod-event: 1 # default
    configmap-event: 1 # default
    secret-event: 1 # default
    service-event: 1 # default
    endpoints-event: 1 # default
    query-persistentvolume: 1024 # default
    query-persistentvolumeclaim: 1024 # default
    query-volumeattachment: 1024 # default
    query-node: 1024 # default
    update-node: 1024 # default
  context:
    send-module: cloudhub
    receive-module: edgecontroller
    response-module: cloudhub
  kube:
    node-name: "" # default
    master: ""     # kube-apiserver address (such as:http://localhost:8080)
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
    node_update_frequency: 20
    kubeconfig: "/root/.kube/config"   #default
  load:
    update-pod-status-workers: 1 # default
    update-node-status-workers: 1 # default
    query-configmap-workers: 1 # default
    query-secret-workers: 4 # default
    query-service-workers: 4 # default
    query-endpoints-workers: 4 # default
    query-persistentvolume-workers: 4 # default
    query-persistentvolumeclaim-workers: 4 # default
    query-volumeattachment-workers: 4 # default
    query-node-workers: 4 # default
    update-node-workers: 4 # default

metamanager:
  edgesite: false # default


devicecontroller:
  kube:
    master: ""        # kube-apiserver address (such as:http://localhost:8080)
    kubeconfig: "/root/.kube/config" 
    content_type: "application/vnd.kubernetes.protobuf"
    qps: 5
    burst: 10
  context:
    send-module: cloudhub
    receive-module: devicecontroller
    response-module: cloudhub
  buffer:
    update-device-status: 1024
    device-event: 1
    device-model-event: 1
  load:
    update-device-status-workers: 1

```

modules.yaml
```
modules:
    enabled: [devicecontroller, edgecontroller, cloudhub]
```

while for new config file, there only one file:
cloudcore.yaml
```
apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  kubeConfig: /root/.kube/config
  master: ""
  qps: 100
modules:
  cloudhub:
    enable: true
    keepaliveInterval: 30
    nodeLimit: 10
    quic:
      address: 0.0.0.0
      maxIncomingStreams: 10000
      port: 10001
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
      enable: true
    websocket:
      address: 0.0.0.0
      enable: true
      port: 10000
    writeTimeout: 30
  devicecontroller:
    buffer:
      deviceEvent: 1
      deviceModelEvent: 1
      updateDeviceStatus: 1024
    context:
      receiveModule: devicecontroller
      responseModule: cloudhub
      sendModule: cloudhub
    enable: true
    load:
      updateDeviceStatusWorkers: 1
  edgecontroller:
    buffer:
      configmapEvent: 1
      endpointsEvent: 1
      podEvent: 1
      queryConfigmap: 1024
      queryEndpoints: 1024
      queryNode: 1024
      queryPersistentvolume: 1024
      queryPersistentvolumeclaim: 1024
      querySecret: 1024
      queryService: 1024
      queryVolumeattachment: 1024
      secretEvent: 1
      serviceEvent: 1
      updateNode: 1024
      updateNodeStatus: 1024
      updatePodStatus: 1024
    context:
      receiveModule: edgecontroller
      responseModule: cloudhub
      sendModule: cloudhub
    enable: true
    load:
      queryConfigmapWorkers: 4
      queryEndpointsWorkers: 4
      queryNodeWorkers: 4
      queryPersistentColumeClaimWorkers: 4
      queryPersistentVolumeWorkers: 4
      querySecretWorkers: 4
      queryServiceWorkers: 4
      queryVolumeAttachmentWorkers: 4
      updateNodeStatusWorkers: 1
      updateNodeWorkers: 4
      updatePodStatusWorkers: 1
    nodeUpdateFrequency: 10
```

keadm need convert those two old configfies into new configfile.

**Why is this needed**:
Quickly convert old configuration files to new configuration files, reducing manual modification。
