### ISSUE TITLE
Cannot find edgeSite.yaml and controller.yaml

### ISSUE THREAD

**Issue by fkh12345** [kubeedge/kubeedge#1520]
I meet some problem in setting up edgesite.
I used edgesite.md to setup edgesite. In the readme, the doc asks me to 

**Modify edgeSite.yaml configuration file. Modify [edgeSite.yaml](https://github.com/kubeedge/kubeedge/blob/master/edgesite/conf/edgeSite.yaml) configuration file, with the IP address of K8S API server**

+ Configure K8S (API Server)
  
  Replace `localhost` at `controller.kube.master` with the IP address

  ```yaml
  controller:
    kube:
      master: http://localhost:8080
      ...
  ```

+ Add EdgeSite (Worker) Node ID/name

  Replace `edge-node` with an unique edge id/name in below fields :
    - `controller.kube.node-id`
    - `controller.edged.hostname-override`
  
  ```yaml
  controller:
    kube:
      ...
      node-id: edge-node
      node-name: edge-node
      ...
    edged:
      ...
      hostname-override: edge-node
      ...
  ```

**However, I can not find edgeSite.yaml in the master branch source code. So how can I setup the edgesite v1.2 in the k8s cluster?**
