### ISSUE TITLE
nodePort not working

### ISSUE THREAD

**Issue by anumercian** [kubeedge/kubeedge#1586]
**What happened**: I am trying to setup a service and expose the node port so that I can access the service using <cloudcore-IP>:<port> but I am unable to access the service when the pod is running on the edge node.

I tried host port to expose a pod and that work well. 

**What you expected to happen**:
I should be able to access the service on the nodeport on the cloudcore node.

**How to reproduce it (as minimally and precisely as possible)**:
influxdb-pod.yml
```
apiVersion: v1
kind: Pod
metadata:
  name: influxdb
  labels:
    name: influxdb
spec:
  containers:
    - name: influxdb
      image: influxdb
      ports:
        - containerPort: 8086
```
influxdb-nodeport.yml
```
kind: Service
apiVersion: v1
metadata:
  name: influxdb
spec:
  type: NodePort
  ports:
    - port: 8086
      nodePort: 30000
  selector:
    name: influxdb
```

`$ kubectl apply -f influxdb-pod.yml`
`$ kubectl apply -f influxdb-nodeport.yml`

`ufw allow 30000`

`curl -v http://<cloudcore-ip>:30000/ping`

Output:
```
root@ns2:~# curl -v http://127.0.0.1:30000/ping
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 31693 failed: No route to host
* Failed to connect to 127.0.0.1 port 30000: No route to host
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 30000: No route to host
```

**Anything else we need to know?**:
Running kubeadm based k8s master 
Kubeedge version :
```
root@ns2:~# kubectl get nodes
NAME           STATUS   ROLES    AGE    VERSION
antman-4       Ready    edge     6h7m   v1.17.1-kubeedge-v1.2.1
ns2   Ready    master   8h     v1.18.0
```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.17.1-kubeedge-v1.2.1

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
- OS (e.g. `cat /etc/os-release`):
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`):
Linux ns2 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Go version (e.g. `go version`): 
go version go1.13 linux/amd64
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): KubeEdge v1.2.1
- Hardware configuration (e.g. `lscpu`): (same as cloudcore)
- OS (e.g. `cat /etc/os-release`): 18.04.4 LTS
- Kernel (e.g. `uname -a`): 4.15.0-96-generic
- Go version (e.g. `go version`): go version go1.13 linux/amd64
- Others:

**Comment by kevin-wangzefeng** [comment]
Hi Anu, NodePort isn't currently supported is KubeEdge as in most cases, edge nodes would locate in different subnet with each other (and with cloud), edge nodes may even locate in a private network with no public IP. NodePort would break even it's impelemented. You may simply try hostport or `hostnetwork: true` for testing.

**Comment by alesz** [comment]
Working pod spec snippet example. `hostPost` and `containerPort` must be equal.
```yaml
spec:
  hostNetwork: true
  containers:
    - ports:
      - containerPort: 9090
        hostPort: 9090
        name: prometheus
        protocol: TCP
```

**Comment by fisherxu** [comment]
> Working pod spec snippet example. hostPost and containerPort must be equal.

If the `hostNetwork` has been set to true, the `hostPost` and `containerPort` can be omitted :)

**Comment by anumercian** [comment]
Thank you for your suggestions @kevin-wangzefeng, @alesz , @fisherxu . If I have a service file with my deployment, using hostNetwork, can I omit the service file while deploying with kubeedge?

I have a scenario where my app, needs to be listening on port 8080. But edgecore seems to have http-alt on port 8080, so I am having a port conflict.

**Comment by kevin-wangzefeng** [comment]
> I have a scenario where my app, needs to be listening on port 8080. But edgecore seems to have http-alt on port 8080, so I am having a port conflict.

In this case you can map 8080 to another hostPort, e.g.:
```yaml
spec:
  containers:
    - ports:
      - containerPort: 8080
        hostPort: 9090
        protocol: TCP
```
