### ISSUE TITLE
edgecore fails to run

### ISSUE THREAD

**Issue by sheep94lion** [kubeedge/kubeedge#1615]
**What happened**:
When I run `edgecore`, it fails with output:

> 2020-04-26 13:18:15.285203 I | INFO: Install client plugin, protocol: rest
> 2020-04-26 13:18:15.285328 I | INFO: Installed service discovery plugin: edge
> I0426 13:18:15.285828   22412 util.go:395] Looking for default routes with IPv4 addresses
> I0426 13:18:15.285853   22412 util.go:400] Default route transits interface "ens33"
> I0426 13:18:15.286107   22412 util.go:209] Interface ens33 is up
> I0426 13:18:15.286178   22412 util.go:257] Interface "ens33" has 2 addresses :[172.16.61.131/24 fe80::20c:29ff:fe99:f0e7/64].
> I0426 13:18:15.286209   22412 util.go:225] Checking addr  172.16.61.131/24.
> I0426 13:18:15.286227   22412 util.go:232] IP found 172.16.61.131
> I0426 13:18:15.286246   22412 util.go:263] Found valid IPv4 address 172.16.61.131 for interface "ens33".
> I0426 13:18:15.286253   22412 util.go:406] Found active IP 172.16.61.131 
> I0426 13:18:15.286384   22412 util.go:395] Looking for default routes with IPv4 addresses
> I0426 13:18:15.286405   22412 util.go:400] Default route transits interface "ens33"
> I0426 13:18:15.286530   22412 util.go:209] Interface ens33 is up
> I0426 13:18:15.286579   22412 util.go:257] Interface "ens33" has 2 addresses :[172.16.61.131/24 fe80::20c:29ff:fe99:f0e7/64].
> I0426 13:18:15.286809   22412 util.go:225] Checking addr  172.16.61.131/24.
> I0426 13:18:15.286890   22412 util.go:232] IP found 172.16.61.131
> I0426 13:18:15.286942   22412 util.go:263] Found valid IPv4 address 172.16.61.131 for interface "ens33".
> I0426 13:18:15.286996   22412 util.go:406] Found active IP 172.16.61.131 
> I0426 13:18:15.287159   22412 util.go:395] Looking for default routes with IPv4 addresses
> I0426 13:18:15.287223   22412 util.go:400] Default route transits interface "ens33"
> I0426 13:18:15.287427   22412 util.go:209] Interface ens33 is up
> I0426 13:18:15.287561   22412 util.go:257] Interface "ens33" has 2 addresses :[172.16.61.131/24 fe80::20c:29ff:fe99:f0e7/64].
> I0426 13:18:15.287626   22412 util.go:225] Checking addr  172.16.61.131/24.
> I0426 13:18:15.287682   22412 util.go:232] IP found 172.16.61.131
> I0426 13:18:15.287732   22412 util.go:263] Found valid IPv4 address 172.16.61.131 for interface "ens33".
> I0426 13:18:15.287783   22412 util.go:406] Found active IP 172.16.61.131 
> [TLSCAFile: Invalid value: "/etc/kubeedge/ca/rootCA.crt": TLSCAFile not exist]

**What you expected to happen**:
`edgecore` run normally.
**How to reproduce it (as minimally and precisely as possible)**:
run `sudo edgecore`
**Anything else we need to know?**:
My edgecore.yaml is:

```
typemeta:                                                                                                                                                     
  kind: EdgeCore                                                                                                                                              
  apiversion: edgecore.config.kubeedge.io/v1alpha1                                                      
database:                                                               
  drivername: sqlite3                                                                    
  aliasname: default                                                               
  datasource: /var/lib/kubeedge/edgecore.db                     
modules:                                                                                                                     
  edged:                                                                   
    enable: true                                                 
    nodestatusupdatefrequency: 10                                                                       
    runtimetype: docker                                                 
    dockeraddress: unix:///var/run/docker.sock                                           
    remoteruntimeendpoint: unix:///var/run/dockershim.sock                         
    remoteimageendpoint: unix:///var/run/dockershim.sock        
    nodeip: 172.16.61.131                                                                                                    
    clusterdns: ""                                                         
    clusterdomain: ""                                            
    edgedmemorycapacity: 7852396000                                                                     
    podsandboximage: kubeedge/pause:3.1                                 
    imagepullprogressdeadline: 60                                             
    runtimerequesttimeout: 2                              
    hostnameoverride: kubeedge-node1                                                  
    registernode: true                                    
    registernodenamespace: default           
    interfacename: zthnhcwxog                
    devicepluginenabled: false
    gpupluginenabled: false                     
    imagegchighthreshold: 80           
    imagegclowthreshold: 40                                                              
    maximumdeadcontainersperpod: 1            
    cgroupdriver: cgroupfs                    
    networkpluginname: ""
    cniconfdir: /etc/cni/net.d                                    
    cnibindir: /opt/cni/bin
    cnicachedir: /var/lib/cni/cache
    networkpluginmtu: 1500
  edgehub:
    enable: true
    heartbeat: 15
    projectid: e632aba927ea4ac2b575ec1603d56f10
    tlscafile: /etc/kubeedge/ca/rootCA.crt
    tlscertfile: /etc/kubeedge/certs/edge.crt
    tlsprivatekeyfile: /etc/kubeedge/certs/edge.key
    quic:
      enable: false
      handshaketimeout: 30
      readdeadline: 15
      server: 127.0.0.1:10001
      writedeadline: 15
    websocket:
      enable: true
      handshaketimeout: 30
      readdeadline: 15
      server: 172.29.166.4:10000
      writedeadline: 15
  eventbus:
    enable: true
    mqttqos: 0
    mqttretain: false
    mqttsessionqueuesize: 100
    mqttserverinternal: tcp://127.0.0.1:1884
    mqttserverexternal: tcp://127.0.0.1:1883
    mqttmode: 2
  metamanager:
    enable: true
    contextsendgroup: hub
    contextsendmodule: websocket
    podstatussyncinterval: 60
  servicebus:
    enable: false
  devicetwin:
    enable: true
  dbtest:
    enable: false
  edgemesh:
    enable: true
    lbstrategy: RoundRobin
```

Edge node can access cloud server using the `zthnhcwxog` interface as specified in edgecore.yaml. But the output of `sudo edgecore` seems to using the `ens33` interface, is this the problem? What does the last line of output `[TLSCAFile: Invalid value: "/etc/kubeedge/ca/rootCA.crt": TLSCAFile not exist]` mean? This file does not exist. Is this the problem?

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  1.2.1
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):x86_64
- OS (e.g. `cat /etc/os-release`):ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`): 1.2.1
- Hardware configuration (e.g. `lscpu`):x86_64
- OS (e.g. `cat /etc/os-release`):ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
