### ISSUE TITLE
csi cannot be used？

### ISSUE THREAD

**Issue by liupeidong0620** [kubeedge/kubeedge#1696]
- Follow the documentation example [csi](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md)
Failed to run `Statefulset`.

- error log
```sh
[root@master1 csi]# kubectl get pod -o wide
NAME                        READY   STATUS             RESTARTS   AGE     IP                NODE          NOMINATED NODE   READINESS GATES
csi-hostpath-controller-0   2/3     CrashLoopBackOff   9          21m     10.32.0.4         master1       <none>           <none>
csi-hostpath-edge-hdtmp     2/2     Running            0          3h30m   192.168.198.129   edge-node-1   <none>           <none>


# describe pod

[root@master1 csi]# kubectl describe pod csi-hostpath-controller-0
Name:         csi-hostpath-controller-0
Namespace:    default
Priority:     0
Node:         master1/192.168.198.136
Start Time:   Tue, 19 May 2020 16:14:01 +0800
Labels:       app=csi-hostpath-controller
              controller-revision-hash=csi-hostpath-controller-6f6d8bc7c6
              statefulset.kubernetes.io/pod-name=csi-hostpath-controller-0
Annotations:  <none>
Status:       Running
IP:           10.32.0.4
IPs:
  IP:           10.32.0.4
Controlled By:  StatefulSet/csi-hostpath-controller
Containers:
  csi-provisioner:
    Container ID:  docker://17db51dbe40e5b726c6ee4500f62a8ace0937bfa70c2243d48c7865cde201c76
    Image:         quay.io/k8scsi/csi-provisioner:v1.2.1
    Image ID:      docker-pullable://quay.io/k8scsi/csi-provisioner@sha256:63a0a70125d40250091a1c1f6709ee9a6d03f41dd086c5936b3a2c591a1a14ac
    Port:          <none>
    Host Port:     <none>
    Args:
      -v=5
      --csi-address=/csi/csi.sock
      --connection-timeout=15s
    State:          Running
      Started:      Tue, 19 May 2020 16:14:02 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /csi from csi-socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6p24l (ro)
  csi-attacher:
    Container ID:  docker://32185f486bf86b13995b361be377a962366e285c4a06bbdef28a98662dfabc81
    Image:         quay.io/k8scsi/csi-attacher:v1.1.1
    Image ID:      docker-pullable://quay.io/k8scsi/csi-attacher@sha256:e4db94969e1d463807162a1115192ed70d632a61fbeb3bdc97b40fe9ce78c831
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --csi-address=/csi/csi.sock
    State:          Running
      Started:      Tue, 19 May 2020 16:14:03 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /csi from csi-socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6p24l (ro)
  csi-driver:
    Container ID:  docker://dd488cc09f3f07cbaa84366b258e19926841f6d4b62349c34c0ec136cfa1933c
    Image:         kubeedge/csidriver:v1.1.0
    Image ID:      docker-pullable://kubeedge/csidriver@sha256:d45d53748cf9e1f1ad7a126704165851b7f8e54025a0d3c837358feb15c432fa
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --drivername=$(CSI_DRIVERNAME)
      --endpoint=$(CSI_ENDPOINT)
      --kubeedge-endpoint=$(KUBEEDGE_ENDPOINT)
      --nodeid=$(KUBE_NODE_NAME)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 19 May 2020 16:35:10 +0800
      Finished:     Tue, 19 May 2020 16:35:10 +0800
    Ready:          False
    Restart Count:  9
    Environment:
      CSI_DRIVERNAME:     csi-hostpath
      CSI_ENDPOINT:       unix:///csi/csi.sock
      KUBEEDGE_ENDPOINT:  unix:///kubeedge/kubeedge.sock
      KUBE_NODE_NAME:     edge-node-1
    Mounts:
      /csi from csi-socket-dir (rw)
      /kubeedge from kubeedge-socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6p24l (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  csi-socket-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/plugins/csi-hostpath
    HostPathType:  DirectoryOrCreate
  kubeedge-socket-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubeedge
    HostPathType:  DirectoryOrCreate
  default-token-6p24l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6p24l
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     kubeedge-csi=controller:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                   From              Message
  ----     ------   ----                  ----              -------
  Normal   Pulled   22m                   kubelet, master1  Container image "quay.io/k8scsi/csi-provisioner:v1.2.1" already present on machine
  Normal   Created  22m                   kubelet, master1  Created container csi-provisioner
  Normal   Started  22m                   kubelet, master1  Started container csi-provisioner
  Normal   Pulled   22m                   kubelet, master1  Container image "quay.io/k8scsi/csi-attacher:v1.1.1" already present on machine
  Normal   Created  22m                   kubelet, master1  Created container csi-attacher
  Normal   Started  22m                   kubelet, master1  Started container csi-attacher
  Normal   Pulled   22m (x4 over 22m)     kubelet, master1  Container image "kubeedge/csidriver:v1.1.0" already present on machine
  Normal   Created  22m (x4 over 22m)     kubelet, master1  Created container csi-driver
  Normal   Started  22m (x4 over 22m)     kubelet, master1  Started container csi-driver
  Warning  BackOff  2m45s (x95 over 22m)  kubelet, master1  Back-off restarting failed container

# docker log
May 19 17:25:31 master1 dockerd[1070]: time="2020-05-19T17:25:31.719017673+08:00" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"
May 19 17:25:35 master1 dockerd[1070]: time="2020-05-19T17:25:35.089869371+08:00" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"
May 19 17:27:14 master1 dockerd[1070]: time="2020-05-19T17:27:14.186280982+08:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 19 17:27:14 master1 dockerd[1070]: time="2020-05-19T17:27:14.186593020+08:00" level=warning msg="6f14a995a3b856f39b47b1a2c17dba55ee79b5e9f28168ea79221efd9ddc3ecb cleanup: failed to unmount IPC: umount /var/lib/docker/containers/6f14a995a3b856f39b47b1a2c17dba55ee79b5e9f28168ea79221efd9ddc3ecb/mounts/shm, flags: 0x2: no such file or directory"
May 19 17:27:14 master1 dockerd[1070]: time="2020-05-19T17:27:14.218265978+08:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 19 17:27:14 master1 dockerd[1070]: time="2020-05-19T17:27:14.218669724+08:00" level=warning msg="a19af5a548bf8dcb30400db71c46a645ba323afa22812d000d8e185fa9feeb50 cleanup: failed to unmount IPC: umount /var/lib/docker/containers/a19af5a548bf8dcb30400db71c46a645ba323afa22812d000d8e185fa9feeb50/mounts/shm, flags: 0x2: no such file or directory"
May 19 17:27:14 master1 dockerd[1070]: time="2020-05-19T17:27:14.482360389+08:00" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
May 19 17:27:49 master1 dockerd[1070]: time="2020-05-19T17:27:49.635235984+08:00" level=info msg="Attempting next endpoint for pull after error: manifest unknown: manifest unknown"

```

- kubeedge version
```sh
[root@master1 csi]# kubectl get nodes
NAME          STATUS   ROLES    AGE   VERSION
edge-node-1   Ready    edge     26h   v1.17.1-kubeedge-v1.2.1
master1       Ready    master   35d   v1.17.3
```

- `Statefulset` example for CSI HostPath Driver on cloud

```yaml
[root@master1 csi]# cat deployment.yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-controller
spec:
  serviceName: "csi-hostpath-controller"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-controller
  template:
    metadata:
      labels:
        app: csi-hostpath-controller
    spec:
      tolerations:
      - key: kubeedge-csi
        #operator: Exists
        value: controller
        operator: Equal
        effect: NoSchedule
      #serviceAccountName: csi-controller
      serviceAccountName: default
      nodeName: master1
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.2.1
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --connection-timeout=15s
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: csi-socket-dir
        - name: csi-driver
          image: kubeedge/csidriver:v1.2.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--drivername=$(CSI_DRIVERNAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--kubeedge-endpoint=$(KUBEEDGE_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_DRIVERNAME
              value: csi-hostpath
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBEEDGE_ENDPOINT
              value: unix:///kubeedge/kubeedge.sock
            - name: KUBE_NODE_NAME
              # replace this value with the name of edge node
              # which is in charge of Create Volume and Delete Volume,
              # Controller Publish Volume and Controller Unpublish Volume.
              value: edge-node-1
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
            - mountPath: /kubeedge
              name: kubeedge-socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: csi-socket-dir
        - hostPath:
            path: /var/lib/kubeedge
            type: DirectoryOrCreate
          name: kubeedge-socket-dir
```
