### ISSUE TITLE
keadm init --advertise-address=  shoudl use "ip" but not `ip`

### ISSUE THREAD

**Issue by xwdreamer** [kubeedge/kubeedge#1797]
**What happened**:

follow the official docs , install cloudcore with advertise-address tags , do not create the right `cloudcore.yaml`

**How to reproduce it (as minimally and precisely as possible)**:

**use `192.168.1.30,22x.xxx.xxx.217`**
```
keadm init --advertise-address=`192.168.1.30,22x.xxx.xxx.217`
```
cat /etc/kubeedge/config/cloudcore.yaml
```
apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  kubeConfig: /root/.kube/config
  master: ""
  qps: 100
leaderelection:
  LeaderElect: false
  LeaseDuration: 15s
  RenewDeadline: 10s
  ResourceLock: endpointsleases
  ResourceName: cloudcorelease
  ResourceNamespace: kubeedge
  RetryPeriod: 2s
modules:
  cloudHub:
    advertiseAddress:
    - 192.168.1.30   #attention ,this is only one ip

    enable: true
    https:

```

**use "192.168.1.30,22x.xxx.xxx.217"**
```
keadm init --advertise-address="192.168.1.30,22x.xxx.xxx.217"
```
cat /etc/kubeedge/config/cloudcore.yaml
```
apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  kubeConfig: /root/.kube/config
  master: ""
  qps: 100
leaderelection:
  LeaderElect: false
  LeaseDuration: 15s
  RenewDeadline: 10s
  ResourceLock: endpointsleases
  ResourceName: cloudcorelease
  ResourceNamespace: kubeedge
  RetryPeriod: 2s
modules:
  cloudHub:
    advertiseAddress:
    - 192.168.1.30
    - 22x.xxx.xxx.217  ###attention ,there are two ip
    enable: true
    https:

```

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/1173919/84134200-d1c06380-aa7a-11ea-97a9-66b8197adc79.png)

**Environment**:
- KubeEdge version(1.3.1):  

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`)：
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:
