### ISSUE TITLE
Kubectl logs failed

### ISSUE THREAD

**Issue by bluefriday** [kubeedge/kubeedge#1876]
**What happened**:

In my cluster, there are 2 nodes (cloud : local virturebox, edge : raspberrypi)
I upgraded my kubeedge to v1.3.1 and tested 'kubectl logs'

but log test failed. I attach my log and config

>>>

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  v1.3.1 (same)

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`): 
```
[root@master]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                3
On-line CPU(s) list:   0-2
Thread(s) per core:    1
Core(s) per socket:    3
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 158
Model name:            Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
```
- OS (e.g. `cat /etc/os-release`): Centos 7
- Kernel (e.g. `uname -a`): Linux master 3.10.0-1127.10.1.el7.x86_64
- Go version (e.g. `go version`): go version go1.13.3 linux/amd64
- Others: VirtualBoc Guest OS on windows10 pro

**EdgeSide Environment**: raspberry pi 3 b+
- edgecore version (e.g. `edgecore --version`):  v1.3.1 (same)
- Hardware configuration (e.g. `lscpu`):
```
root@raspberrypi:/var/lib/edged# lscpu
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               4
Model name:          Cortex-A53
```
- OS (e.g. `cat /etc/os-release`): 
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
```

- Kernel (e.g. `uname -a`):  Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
- Go version (e.g. `go version`): go version go1.13.8 linux/arm
- Others:

1) netstat command result (with edge node)
```
root@raspberrypi:/# netstat -anp | grep LISTEN
tcp        0      0 127.0.0.1:10350         0.0.0.0:*               LISTEN      773/./edgecore
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      470/sshd
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      459/mosquitto
tcp6       0      0 :::8081                 :::*                    LISTEN      2938/docker-proxy
tcp6       0      0 :::22                   :::*                    LISTEN      470/sshd
tcp6       0      0 :::1883                 :::*                    LISTEN      459/mosquitto
...
```

2) kubectl log result(failed) 
```
[root@master]# kubectl logs -n kube-system nginx-deployment-6f9874cfdf-z5vwn
Error from server: Get https://10.20.30.77:10350/containerLogs/kube-system/nginx-deployment-6f9874cfdf-z5vwn/nginx: dial tcp 10.20.30.77:10350: connect: connection refused
[root@master]#
```

**Comment by bluefriday** [comment]
These are my config files.

1. cloudcore ------------------------------------------
```
apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  kubeConfig: /root/.kube/config
  master: ""
  qps: 100
leaderelection:
  LeaderElect: false
  LeaseDuration: 15s
  RenewDeadline: 10s
  ResourceLock: endpointsleases
  ResourceName: cloudcorelease
  ResourceNamespace: kubeedge
  RetryPeriod: 2s
modules:
  cloudHub:
    advertiseAddress:
    - 10.0.2.15
    enable: true
    https:
      address: 0.0.0.0
      enable: true
      port: 10002
    keepaliveInterval: 30
    nodeLimit: 10
    quic:
      address: 0.0.0.0
      maxIncomingStreams: 10000
      port: 10001
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCAKeyFile: /etc/kubeedge/ca/rootCA.key
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
      enable: true
    websocket:
      address: 0.0.0.0
      enable: true
      port: 10000
    writeTimeout: 30
  cloudStream:
    enable: true
    streamPort: 10003
    tlsStreamCAFile: /etc/kubeedge/ca/streamCA.crt
    tlsStreamCertFile: /etc/kubeedge/certs/stream.crt
    tlsStreamPrivateKeyFile: /etc/kubeedge/certs/stream.key
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    tunnelPort: 10004
  deviceController:
    buffer:
      deviceEvent: 1
      deviceModelEvent: 1
      updateDeviceStatus: 1024
    context:
      receiveModule: devicecontroller
      responseModule: cloudhub
      sendModule: cloudhub
    enable: true
    load:
      updateDeviceStatusWorkers: 1
  edgeController:
    buffer:
      configMapEvent: 1
      deletePod: 1024
      endpointsEvent: 1
      podEvent: 1
      queryConfigMap: 1024
      queryEndpoints: 1024
      queryNode: 1024
      queryPersistentVolume: 1024
      queryPersistentVolumeClaim: 1024
      querySecret: 1024
      queryService: 1024
      queryVolumeAttachment: 1024
      secretEvent: 1
      serviceEvent: 1
      updateNode: 1024
      updateNodeStatus: 1024
      updatePodStatus: 1024
    context:
      receiveModule: edgecontroller
      responseModule: cloudhub
      sendModule: cloudhub
    enable: true
    load:
      deletePodWorkers: 1024
      queryConfigMapWorkers: 4
      queryEndpointsWorkers: 4
      queryNodeWorkers: 4
      queryPersistentVolumeClaimWorkers: 4
      queryPersistentVolumeWorkers: 4
      querySecretWorkers: 4
      queryServiceWorkers: 4
      queryVolumeAttachmentWorkers: 4
      updateNodeStatusWorkers: 1
      updateNodeWorkers: 4
      updatePodStatusWorkers: 1
    nodeUpdateFrequency: 10
  syncController:
    enable: true
```

2. edgecore ------------------------------------------
```
apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  aliasName: default
  dataSource: /var/lib/kubeedge/edgecore.db
  driverName: sqlite3
kind: EdgeCore
modules:
  dbTest:
    enable: false
  deviceTwin:
    enable: true
  edgeHub:
    enable: true
    heartbeat: 15
    httpServer: https://cloudcore-ip:10002
    projectID: e632aba927ea4ac2b575ec1603d56f10
    quic:
      handshakeTimeout: 30
      readDeadline: 15
      server: cloudcore-ip:10001
      writeDeadline: 15
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    token: "my token value"
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: cloudcore-ip:10000
      writeDeadline: 15
  edgeMesh:
    enable: false
    lbStrategy: RoundRobin
    listenInterface: docker0
    listenPort: 40001
    subNet: 9.251.0.0/16
  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: cloudcore-ip:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15
  edged:
    cgroupDriver: cgroupfs
    cgroupRoot: ""
    cgroupsPerQOS: true
    clusterDNS: ""
    clusterDomain: ""
    cniBinDir: /opt/cni/bin
    cniCacheDirs: /var/lib/cni/cache
    cniConfDir: /etc/cni/net.d
    concurrentConsumers: 5
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    edgedMemoryCapacity: 7852396000
    enable: true
    enableMetrics: true
    gpuPluginEnabled: false
    hostnameOverride: raspberrypi
    imageGCHighThreshold: 80
    imageGCLowThreshold: 40
    imagePullProgressDeadline: 60
    interfaceName: eth0
    maximumDeadContainersPerPod: 1
    networkPluginMTU: 1500
    nodeIP: edgecore-ip
    nodeStatusUpdateFrequency: 10
    podSandboxImage: kubeedge/pause:3.1
    registerNode: true
    registerNodeNamespace: default
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    runtimeRequestTimeout: 2
    runtimeType: docker
    volumeStatsAggPeriod: 60000000000
  eventBus:
    enable: true
    mqttMode: 2
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
    mqttSessionQueueSize: 100
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    podStatusSyncInterval: 60
  serviceBus:
    enable: false
```

**Comment by GsssC** [comment]
can `curl https://10.20.30.77:10350/containerLogs/kube-system/nginx-deployment-6f9874cfdf-z5vwn/nginx` in edgenode?

**Comment by bluefriday** [comment]
I ran curl command in my edge node (10,20.30.77). result is below.

```
root@raspberrypi:~/# curl https://10.20.30.77:10350/containerLogs/kube-system/nginx-deployment-6f9874cfdf-z5vwn/nginx
curl: (7) Failed to connect to 10.20.30.77 port 10350: Connection refused
root@raspberrypi:~/#
```

**Comment by GsssC** [comment]
@bluefriday That is weird, how about `cutl localhost:10350`? May you do not stop firewalld

**Comment by bluefriday** [comment]
> @bluefriday That is weird, how about `cutl localhost:10350`? Maybe you haven't turned off the firewall

@GsssC 
In case of ``` http://localhost:10350``` , I could get log, (but still not work in case of ```https://localhost:10350```). 

Is there any guide or document about setting for kubectl edge log in KubeEdge v1.3.0+?

**Comment by GsssC** [comment]
@bluefriday https://github.com/kubeedge/kubeedge/pull/1914
May it help you.

**Comment by bluefriday** [comment]
@GsssC Thanks for your help.
With your link(#1914) and guides(https://github.com/kubeedge/kubeedge/blob/release-1.3/docs/setup/kubeedge_install_source.md), I created a stream crt/key and setup iptables config.
However, the kubectl logs command still doesn't work. (show 'An internal error' message)

I want to know what crt and key are needed at the below edgecore.yaml 
```
  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: cloudcore-ip:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
```
