### ISSUE TITLE
The pod IP is none

### ISSUE THREAD

**Issue by dddddai** [kubeedge/kubeedge#1942]
**What happened**:
![fcaefd56a3060731cffa7dabdccb52e7](https://user-images.githubusercontent.com/41563853/87866233-b7e73a00-c9b1-11ea-96d9-50a86c15b52e.png)

**What you expected to happen**:
The pod IP should be 192.168.1.11 becasue I set `hostNetwork: true`
![4bc6ce598f32ee7e71c3b1394ede522a](https://user-images.githubusercontent.com/41563853/87866239-cf262780-c9b1-11ea-903c-308afba72ff5.png)

**How to reproduce it (as minimally and precisely as possible)**:
1.`kubectl apply -f nginx.yaml`
2.`kubectl get po -owide`

nginx.yaml :
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
```

**Anything else we need to know?**:
1. I can access nginx at 192.168.1.11
![7260a7cddab804388b2c104e97940f16](https://user-images.githubusercontent.com/41563853/87866241-dbaa8000-c9b1-11ea-92c9-d04c34d6b0a1.png)

2. This problem did not occur with the Kubelet node
![39}TL9L_BR@NI0ME1DPZAW3](https://user-images.githubusercontent.com/41563853/87866245-e2d18e00-c9b1-11ea-802f-4eb8c08691bb.png)

**Environment**:
- KubeEdge version:  v1.3.1
