### ISSUE TITLE
kube-flannel-ds-amd64-65wxz :    Neither --kubeconfig nor --master was specified

### ISSUE THREAD

**Issue by Ranguo956** [kubeedge/kubeedge#2083]
cloud-side: 192.168.64.10
edge-side: 192.168.64.11

**What happened**:
#### cqupt@cloud-side:~$watch kubectl get pods --all-namespaces -owide
NAMESPACE--------- NAME--------------------------------STATUS------------------ IP------------------NODE
kube-system   coredns-b46dbdfcf-5h27w ---------------Running-------- ---10.244.0.26--------------cloud-side
kube-system   coredns-b46dbdfcf-t644d------------------Running-------- ---10.244.0.27--------------cloud-side 
kube-system   etcd-cloud-side-------------------------------Running------------192.168.64.10---------cloud-side
kube-system   kube-apiserver-cloud-side------------------Running------------192.168.64.10 ------ cloud-side
kube-system   kube-controller-manager-cloud-side ----Running------------192.168.64.10 --------cloud-side 
kube-system   kube-flannel-ds-amd64-65wxz-------------Error----------------192.168.64.11--------edge-side 
kube-system   kube-flannel-ds-amd64-z5qvv-------------Running-----------192.168.64.10-------- cloud-side 
kube-system   kube-proxy-9bpvc[11;52H1/1--------------Running------------192.168.64.11--------edge-side
kube-system   kube-proxy-mlqmh[12;52H1/1------------- Running-----------192.168.64.10-------cloud-side
kube-system   kube-scheduler-cloud-side------------------Running-----------192.168.64.10-------- cloud-side 

#### cqupt@cloud-side:~$ kubectl logs -n kube-system kube-flannel-ds-amd64-65wxz
I0817 07:24:13.351244       1 main.go:531] Using interface with name enp1s0 and address 192.168.64.11
I0817 07:24:13.351412       1 main.go:548] Defaulting external address to interface address (192.168.64.11)
W0817 07:24:13.351444       1 client_config.go:517] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0817 07:24:13.351473       1 client_config.go:522] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E0817 07:24:13.351698       1 main.go:243] Failed to create SubnetManager: fail to create kubernetes config: invalid configuration: default cluster has no server defined

**How to reproduce it (as minimally and precisely as possible)**:

#### edgecore.yaml:

```
apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  aliasName: default
  dataSource: /var/lib/kubeedge/edgecore.db
  driverName: sqlite3
kind: EdgeCore
modules:
  dbTest:
    enable: false
  deviceTwin:
    enable: true
  edgeHub:
    enable: true
    heartbeat: 15
    httpServer: 192.168.64.10:10002
    projectID: e632aba927ea4ac2b575ec1603d56f10
    quic:
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.64.10:10001
      writeDeadline: 15
    rotateCertificates: true
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    token: 50900264be9c44965c1db14941b3cc5f2dda5539cb96385315582afe71446133.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTc2NjY3OTB9.V0BUI7DrPJXfkX8bfQ_EUIsEN7SSCIM59y6CjD7R7VI
    websocket:
      server: 192.168.64.10:1000
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.64.10:10000
      writeDeadline: 15
  edgeMesh:
    enable: true
    lbStrategy: RoundRobin
    listenInterface: docker0
    listenPort: 40001
    subNet: 9.251.0.0/16
  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: 192.168.64.10:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15
  edged:
    cgroupDriver: cgroupfs
    cgroupRoot: ""
    cgroupsPerQOS: true
    clusterDNS: ""
    clusterDomain: ""
    cniBinDir: /opt/cni/bin
    cniCacheDirs: /var/lib/cni/cache
    cniConfDir: /etc/cni/net.d
    concurrentConsumers: 5
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    edgedMemoryCapacity: 7852396000
    enable: true
    enableMetrics: true
    gpuPluginEnabled: false
    hostnameOverride: edge-side
    imageGCHighThreshold: 80
    imageGCLowThreshold: 40
    imagePullProgressDeadline: 60
    interfaceName: enp1s0
    maximumDeadContainersPerPod: 1
    networkPluginMTU: 1500
    nodeIP: 192.168.64.11
    nodeStatusUpdateFrequency: 10
    podSandboxImage: kubeedge/pause:3.1
    registerNode: true
    registerNodeNamespace: default
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    runtimeRequestTimeout: 2
    runtimeType: docker
    volumeStatsAggPeriod: 60000000000
  eventBus:
    enable: true
    mqttMode: 2
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
    mqttSessionQueueSize: 100
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    podStatusSyncInterval: 60
  serviceBus:
    enable: false
```

**Anything else we need to know?**:

**Environment**: 
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  KubeEdge 1.4.0
     
**CloudSide Environment**: 
- Hardware configuration (e.g. `lscpu`): Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
- OS (e.g. `cat /etc/os-release`):ubuntu 16.04,
- Kernel (e.g. `uname -a`):4.10.0-28-generic
- Go version (e.g. `go version`): go 1.13.10
- Others: enp2s0 ,   ip:192.168.64.11,   kubernetes 1.18.6

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):v1.4.0
- Hardware configuration (e.g. `lscpu`):Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
- OS (e.g. `cat /etc/os-release`)::ubuntu 16.04
- Kernel (e.g. `uname -a`):4.10.0-28-generic
- Go version (e.g. `go version`): go 1.13.10
- Others: enp1s0,    ip:192.168.64.11
