### ISSUE TITLE
Pod get stuck in pending on some edge node

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#2148]
**What happened**:
On a 1 normal node + 3 edge nodes cluster, deploy a nginx deployment with node selector to edge nodes, 3 replicas, only 2 pod running, 1 pod stuck in pending.

**What you expected to happen**:
All pods get running

**How to reproduce it (as minimally and precisely as possible)**:
Apply following yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      nodeSelector:
        node-role.kubernetes.io/edge: ''
      tolerations:
        - key: node.kubeedge.io
          operator: Equal
          value: edge
          effect: "NoSchedule"
```

**Anything else we need to know?**:
Nodes status
```
NAME         STATUS   ROLES           AGE     VERSION
edgenode-1   Ready    agent,edge      4h2m    v1.18.6-kubeedge-v1.4.0
edgenode-2   Ready    agent,edge      3h58m   v1.18.6-kubeedge-v1.4.0
edgenode-3   Ready    agent,edge      151m    v1.18.6-kubeedge-v1.4.0
host         Ready    master,worker   7d4h    v1.17.9
```

Pod status
```
NAME                                READY   STATUS    RESTARTS   AGE
nginx-deployment-58d5654c8f-h68fv   1/1     Running   0          15m
nginx-deployment-58d5654c8f-snghk   0/1     Pending   0          15m
nginx-deployment-58d5654c8f-x8zf9   1/1     Running   0          15m
```

Pending pod description
```
Name:           nginx-deployment-58d5654c8f-snghk
Namespace:      default
Priority:       0
Node:           edgenode-1/
Labels:         app=nginx
                pod-template-hash=58d5654c8f
Annotations:    kubesphere.io/restartedAt: 2020-09-10T06:44:43.404Z
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/nginx-deployment-58d5654c8f
Containers:
  nginx:
    Image:        nginx:latest
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-v9hlv (ro)
Conditions:
  Type           Status
  PodScheduled   True
Volumes:
  default-token-v9hlv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-v9hlv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/edge=
Tolerations:     node.kubeedge.io=edge:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  15m   default-scheduler  Successfully assigned default/nginx-deployment-58d5654c8f-snghk to edgenode-1
```

Edgecore logs on node
```
E0910 07:02:46.738240   11134 metaclient.go:125] send sync message default/secret/default-token-v9hlv failed, error:timeout to get response, retries: 2
E0910 07:02:46.738363   11134 secret.go:195] Couldn't get secret default/default-token-v9hlv: get secret from metaManager failed, err: timed out waiting for the condition
I0910 07:02:46.738515   11134 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "default-token-v9hlv" : get secret from metaManager failed, err: timed out waiting fo
r the condition
E0910 07:02:46.738681   11134 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/secret/6c7e1f15-c30e-43f0-afef-135369d073cf-default-token-v9hlv podName:6c7e1f15-c
30e-43f0-afef-135369d073cf nodeName:}" failed. No retries permitted until 2020-09-10 07:03:02.738625773 +0000 UTC m=+825.292096980 (durationBeforeRetry 16s). Error: "MountVolume.SetUp f
ailed for volume \"default-token-v9hlv\" (UniqueName: \"kubernetes.io/secret/6c7e1f15-c30e-43f0-afef-135369d073cf-default-token-v9hlv\") pod \"nginx-deployment-58d5654c8f-snghk\" (UID:
\"6c7e1f15-c30e-43f0-afef-135369d073cf\") : get secret from metaManager failed, err: timed out waiting for the condition"
I0910 07:02:46.738683   11134 process.go:459] ########## process get: req[{Header:{ID:7a3f3e82-a388-4e8b-982e-1ada8392cad0 ParentID: Timestamp:1599721246727 ResourceVersion: Sync:true}
Router:{Source:edged Group:meta Operation:query Resource:default/secret/default-token-v9hlv} Content:<nil>}], resp[{Header:{ID: ParentID: Timestamp:0 ResourceVersion: Sync:false} Router
:{Source: Group: Operation: Resource:} Content:<nil>}], err[timeout to get response]
E0910 07:02:46.738757   11134 process.go:461] remote query failed: timeout to get response
```

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
v1.4.0

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
8 Core 16G
- OS (e.g. `cat /etc/os-release`):
Ubuntu 18.04.3
- Kernel (e.g. `uname -a`):
4.15.0-117-generic #118-Ubuntu
- Go version (e.g. `go version`): 
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
v1.4.0
- Hardware configuration (e.g. `lscpu`):
x86 8Core 16G
arm 4Core 4G
- OS (e.g. `cat /etc/os-release`):
x86 Ubuntu 18.04.3
arm Ubuntu 18.04.3
- Kernel (e.g. `uname -a`):
x86 4.15.0-117-generic #118-Ubuntu
arm 5.3.0-1033-raspi2 #35-Ubuntu SMP
- Go version (e.g. `go version`): 
1.13.14
- Others:

**Comment by daixiang0** [comment]
@Ma-Dan could you share more details about it? Such as where do pods run on? `-o wide` would help.

**Comment by Ma-Dan** [comment]
This is the pod scheduling state
```
NAME                                READY   STATUS    RESTARTS   AGE   IP           NODE         NOMINATED NODE   READINESS GATES
nginx-deployment-58d5654c8f-5xksm   1/1     Running   0          39s   <none>       edgenode-3   <none>           <none>
nginx-deployment-58d5654c8f-7g9mb   1/1     Running   0          39s   172.17.0.2   edgenode-2   <none>           <none>
nginx-deployment-58d5654c8f-k7n8m   0/1     Pending   0          39s   <none>       edgenode-1   <none>           <none>
```

**Comment by Ma-Dan** [comment]
After a period of time, maybe 20 minutes, edgenode-1 got into NotReady state, so I rerun edgecore on edgenode-1, then it get back to Ready state, but newly deployed pod still can not run on it.

**Comment by Ma-Dan** [comment]
And this is the config on edgenode-1
```
# With --defaultconfig flag, users can easily get a default full config file as reference, with all fields (and field descriptions) included and default values set. 
# Users can modify/create their own configs accordingly as reference. 
# Because it is a full configuration, it is more suitable for advanced users.

apiVersion: edgecore.config.kubeedge.io/v1alpha1
database:
  aliasName: default
  dataSource: /var/lib/kubeedge/edgecore.db
  driverName: sqlite3
kind: EdgeCore
modules:
  dbTest:
    enable: false
  deviceTwin:
    enable: true
  edgeHub:
    enable: true
    heartbeat: 15
    httpServer: https://cloudcore:10002
    projectID: e632aba927ea4ac2b575ec1603d56f10
    quic:
      handshakeTimeout: 30
      readDeadline: 15
      server: cloudcore:10001
      writeDeadline: 15
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    token: xxx
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: cloudcore:10000
      writeDeadline: 15
  edgeMesh:
    enable: false
    lbStrategy: RoundRobin
    listenInterface: docker0
    listenPort: 40001
    subNet: 9.251.0.0/16
  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: cloudcore:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15
  edged:
    cgroupDriver: cgroupfs
    cgroupRoot: ""
    cgroupsPerQOS: true
    clusterDNS: ""
    clusterDomain: ""
    cniBinDir: /opt/cni/bin
    cniCacheDirs: /var/lib/cni/cache
    cniConfDir: /etc/cni/net.d
    concurrentConsumers: 5
    devicePluginEnabled: false
    dockerAddress: unix:///var/run/docker.sock
    edgedMemoryCapacity: 7852396000
    enable: true
    enableMetrics: true
    gpuPluginEnabled: false
    hostnameOverride: edgenode-1
    imageGCHighThreshold: 80
    imageGCLowThreshold: 40
    imagePullProgressDeadline: 60
    interfaceName: eth0
    maximumDeadContainersPerPod: 1
    networkPluginMTU: 1500
    #networkPluginName: cni
    nodeIP: 192.168.100.1
    nodeStatusUpdateFrequency: 10
    podSandboxImage: kubeedge/pause:3.1
    registerNode: true
    registerNodeNamespace: default
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    runtimeRequestTimeout: 2
    runtimeType: docker
    volumeStatsAggPeriod: 60000000000
  eventBus:
    enable: false
    mqttMode: 2
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
    mqttSessionQueueSize: 100
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    podStatusSyncInterval: 60
  serviceBus:
    enable: false
```
