### ISSUE TITLE
Pod in error status while using deployment, specify port in hostPort

### ISSUE THREAD

**Issue by alan0415** [kubeedge/kubeedge#2152]
**What happened**:
I have one PC as cloud node and one Raspberry pi 4 as edge node in my cluster. I used deployment to deploy grafana at edge node; use hostPort so I can access it with edge-IP:3000.
I deployed it at edge, found that it worked at first; but after a few second, it try to restart pods, and turn pod status into error. But the weird thing is I checked the container status running at edge, it looks fine. I also access to grafana used edge-IP:3000 and it also worked.
The pod status shown as below:
```
NAME                       READY   STATUS    RESTARTS   AGE   IP       NODE     NOMINATED NODE   READINESS GATES
grafana-6fb45bfc59-s99vv   0/1     Pending   0          11s   <none>   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     ContainerCreating   0          70s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   1/1     Running             0          92s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   1/1     Running             1          117s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     Error               2          2m19s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     Error               3          2m56s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     Error               4          3m35s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   1/1     Running             5          4m12s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     Error               5          4m25s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     Error               6          4m26s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   1/1     Running             7          7m25s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   1/1     Running             8          7m46s   172.17.0.2   edge-1   <none>           <none>
grafana-6fb45bfc59-s99vv   0/1     Error               8          7m54s   172.17.0.2   edge-1   <none>           <none>

```
**What you expected to happen**:
I use as type hostPort beacuse I want to access to Grafana use edge-IP:3000. But I want to know why the pod status turned into error, even though the container still work on edge node.  If I should not specify hostPort as port type?

**How to reproduce it (as minimally and precisely as possible)**:
The following is my yaml for deploy grafana.
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana
spec:
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: grafana
          hostPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/grafana
          subPath: grafana
          name: storage
      volumes:
      - name: storage
        hostPath:
          path: /mnt/grafana
        #persistentVolumeClaim:
        #  claimName: grafana
      nodeSelector:
        name: edge-1
```
**Anything else we need to know?**:
I got some error message at edge_core log:
```
W0911 11:29:54.459297   27829 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/grafana-9f7fcd5c4-8ncvj through plugin: invalid network status for
W0911 11:29:54.467723   27829 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/grafana-9f7fcd5c4-8ncvj through plugin: invalid network status for
W0911 11:29:55.496497   27829 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/grafana-9f7fcd5c4-8ncvj through plugin: invalid network status for
W0911 11:29:55.513002   27829 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/grafana-9f7fcd5c4-8ncvj through plugin: invalid network status for
```
**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  
```
Kubeedge v1.2.1
```
**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
```
$ lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Stepping:            3
CPU MHz:             800.028
CPU max MHz:         3300.0000
CPU min MHz:         800.0000
BogoMIPS:            5399.81
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
```
- OS (e.g. `cat /etc/os-release`):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`):
`Linux k8s-node01 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
`
- Go version (e.g. `go version`): 
`go version go1.14 linux/amd64`
- Others:

**EdgeSide Environment**:
- edgecore version (e.g. edgecore --version`): Kubeedge v1.2.1
- Hardware configuration (e.g. `lscpu`):
```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```
- OS (e.g. `cat /etc/os-release`):
```PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
- Kernel (e.g. `uname -a`):
`Linux raspberrypi 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
`
- Go version (e.g. `go version`): 
`go version go1.13.12 linux/arm
`
- Others:
