### ISSUE TITLE
Container can't be deployed to raspberry pi edge device

### ISSUE THREAD

**Issue by Oliveirakun** [kubeedge/kubeedge#2154]
**What happened**:
When I try to deploy a nginx container to a raspberry pi edge node, k8s show this message in container status:
```
NAME                                READY   STATUS               RESTARTS   AGE   IP             NODE     NOMINATED NODE   READINESS GATES
nginx-deployment-6899fc4f97-lbxhm   0/1     ContainerCannotRun   0          11s   192.168.0.43   ubuntu   <none>           <none>
```

**What you expected to happen**:
The expected was to container run normally

**How to reproduce it (as minimally and precisely as possible)**:
Apply this manifest to deploy nginx to a raspberry pi 3 edge node:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
      - name: nginx
        image: nginx:1.19-alpine
        ports:
        - containerPort: 80
      nodeSelector: 
        beta.kubernetes.io/arch: arm64
```

**Anything else we need to know?**:

Node status:
```
NAME                  STATUS   ROLES        AGE   VERSION
ubuntu                Ready    agent,edge   9h    v1.18.6-kubeedge-v1.4.0
ubuntu-test-machine   Ready    master       33h   v1.19.1
```

When I run this command `kubectl get pod termination-demo --output=yaml` to show what was the error, the following is showed:
```
containerStatuses:
  - containerID: docker://bedb5f2881ae2827ad5d1d29439812b767dfafba19b52b3b2b795740053c8fd9
    image: nginx:1.19-alpine
    imageID: docker-pullable://nginx@sha256:a97eb9ecc708c8aa715ccfb5e9338f5456e4b65575daf304f108301f3b497314
    lastState:
      terminated:
        containerID: docker://bedb5f2881ae2827ad5d1d29439812b767dfafba19b52b3b2b795740053c8fd9
        exitCode: 128
        finishedAt: "2020-09-12T05:39:37Z"
        message: 'error while creating mount source path ''/var/lib/edged/pods/ff58cc16-f10d-4af5-a09c-e4d624dee266/volumes/kubernetes.io~secret/default-token-dv7db'':
          mkdir /var/lib/edged: read-only file system'
        reason: ContainerCannotRun
        startedAt: "2020-09-12T05:39:37Z"
    name: nginx
    ready: false
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: docker://bedb5f2881ae2827ad5d1d29439812b767dfafba19b52b3b2b795740053c8fd9
        exitCode: 128
        finishedAt: "2020-09-12T05:39:37Z"
        message: 'error while creating mount source path ''/var/lib/edged/pods/ff58cc16-f10d-4af5-a09c-e4d624dee266/volumes/kubernetes.io~secret/default-token-dv7db'':
          mkdir /var/lib/edged: read-only file system'
        reason: ContainerCannotRun
        startedAt: "2020-09-12T05:39:37Z"
  hostIP: 192.168.0.43
  phase: Running
  podIP: 192.168.0.43
  podIPs:
  - ip: 192.168.0.43
  qosClass: BestEffort
  startTime: "2020-09-12T05:39:38Z"
```

I checked the `/var/lib/edged` directory, changed permissions, I'm sure it's not read-only because I can write with any user but this problem still occurs 

**Environment**:
- KubeEdge version(e.g. `cloudcore/edgecore --version`):  

KubeEdge v1.4.0

**CloudSide Environment**:
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

Hardware configuration:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   40 bits physical, 48 bits virtual
CPU(s):                          2
On-line CPU(s) list:             0,1
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       2
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           79
Model name:                      Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
Stepping:                        1
CPU MHz:                         2199.998
BogoMIPS:                        4399.99
Virtualization:                  VT-x
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       64 KiB
L1i cache:                       64 KiB
L2 cache:                        8 MiB
NUMA node0 CPU(s):               0,1
Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc
                                 _known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid
                                 _fault invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap xsaveopt md_clear                                r

```

OS:
```
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Kernel:
```
Linux ubuntu-test-machine 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Hardware configuration: 

**EdgeSide Environment**:
- edgecore version (e.g. `edgecore --version`):
- Hardware configuration (e.g. `lscpu`):
- OS (e.g. `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Go version (e.g. `go version`): 
- Others:

EdgeCore version:
```
KubeEdge v1.4.0
```

Hardware configuration:
```
Architecture:                    aarch64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           4
Model name:                      Cortex-A53
Stepping:                        r0p4
CPU max MHz:                     1200.0000
CPU min MHz:                     600.0000
BogoMIPS:                        38.40
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Not affected
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

OS:
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

Kernel:
```
Linux ubuntu 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```
