### ISSUE TITLE
metrics-server deploy unavailable containercreating

### ISSUE THREAD

**Issue by tkzkno** [kubeedge/kubeedge#2306]
**What happened and what you expected to happen**:
read [https://docs.kubeedge.io/en/latest/setup/keadm.html](url)
deploy all files(/metrics-server/manifests/base)
`deployment.yaml`
```yaml:deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: metrics
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: metrics
    spec:
      serviceAccountName: metrics-server
      volumes:
      # mount in tmp so we can safely use from-scratch images and/or read-only containers
      - name: tmp-dir
        emptyDir: {}
      hostNetwork: true
      containers:
      - name: metrics-server
        image: metrics-server-kubeedge:latest
        imagePullPolicy: Never
        args:
          - --cert-dir=/tmp
          - --secure-port=4443
          - --v=2
          - --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalIP,Hostname
          - --kubelet-use-node-status-port
        ports:
        - name: https
          containerPort: 4443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: https
            scheme: HTTPS
          periodSeconds: 10
          failureThreshold: 3
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
      nodeSelector:
        kubernetes.io/os: linux
```

`$kubectl get deploy metrics-server -n kube-system -o yaml`
```
status:
  conditions:
  - lastTransitionTime: "2020-11-07T05:44:15Z"
    lastUpdateTime: "2020-11-07T05:44:15Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-11-07T05:54:16Z"
    lastUpdateTime: "2020-11-07T05:54:16Z"
    message: ReplicaSet "metrics-server-68458c65f" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

`$ kubectl describe deploy metrics-server -n kube-system `
```
Name:                   metrics-server
Namespace:              kube-system
CreationTimestamp:      Sat, 07 Nov 2020 05:44:15 +0000
Labels:                 <none>
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               name=metrics
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  0 max unavailable, 25% max surge
Pod Template:
  Labels:           name=metrics
  Service Account:  metrics-server
  Containers:
   metrics-server:
    Image:      metrics-server-kubeedge:latest
    Port:       4443/TCP
    Host Port:  4443/TCP
    Args:
      --cert-dir=/tmp
      --secure-port=4443
      --v=2
      --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalIP,Hostname
      --kubelet-use-node-status-port
    Liveness:     http-get https://:https/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get https://:https/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /tmp from tmp-dir (rw)
  Volumes:
   tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      False   MinimumReplicasUnavailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   metrics-server-68458c65f (1/1 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  23m   deployment-controller  Scaled up replica set metrics-server-68458c65f to 1
```
`$ kubectl describe pod metrics-server -n kube-system`
```
Name:         metrics-server-68458c65f-6qfg2
Namespace:    kube-system
Priority:     0
Node:         edge-01/192.168.10.170
Start Time:   Sat, 07 Nov 2020 05:44:17 +0000
Labels:       name=metrics
              pod-template-hash=68458c65f
Annotations:  <none>
Status:       Pending
IP:           192.168.10.170
IPs:
  IP:           192.168.10.170
Controlled By:  ReplicaSet/metrics-server-68458c65f
Containers:
  metrics-server:
    Container ID:  
    Image:         metrics-server-kubeedge:latest
    Image ID:      
    Port:          4443/TCP
    Host Port:     4443/TCP
    Args:
      --cert-dir=/tmp
      --secure-port=4443
      --v=2
      --kubelet-preferred-address-types=InternalDNS,InternalIP,ExternalIP,Hostname
      --kubelet-use-node-status-port
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       http-get https://:https/livez delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get https://:https/readyz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /tmp from tmp-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-ng46s (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  tmp-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  metrics-server-token-ng46s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-ng46s
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  25m   default-scheduler  Successfully assigned kube-system/metrics-server-68458c65f-6qfg2 to edge-01

```

`$kubectl get node -o wide `
```
NAME        STATUS   ROLES        AGE    VERSION                   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
edge-01     Ready    agent,edge   2d2h   v1.18.6-kubeedge-v1.4.0   192.168.10.170   <none>        Ubuntu 20.04.1 LTS   5.4.0-52-generic   docker://19.3.13
edge-02     Ready    agent,edge   2d2h   v1.18.6-kubeedge-v1.4.0   192.168.10.166   <none>        Ubuntu 20.04.1 LTS   5.4.0-52-generic   docker://19.3.13
instance1   Ready    master       2d2h   v1.19.3                   10.138.0.7       <none>        Ubuntu 20.04.1 LTS   5.4.0-1028-gcp     docker://19.3.13
```

`$docker images`
```
REPOSITORY                                               TAG                                        IMAGE ID            CREATED             SIZE
metrics-server-kubeedge                                  latest                                     7db9adb83b84        18 hours ago        60.5MB
gcr.io/k8s-staging-metrics-server/metrics-server-amd64   42ae895f21f6bb7669b7014984aaed3b0c341f7b   7db9adb83b84        18 hours ago        60.5MB

```

**Anything else we need to know?**:

cloud : GCP
edge : intel NUC 

How to fix ?? 
Thanks for your help

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubectl --version
# paste output here
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
# paste output here
```

</details>

<details><summary>EdgeCore Version</summary>

```
$ edgecore --version
# paste output here
```

</details>
