### ISSUE TITLE
cloudcore waiting only on IP v6 ports: edge cannot connect with IP v4

### ISSUE THREAD

**Issue by didier-durand** [kubeedge/kubeedge#2357]
**What happened**:

I installed 2 Ubuntu instances on Google Cloud : 1 with microk8s to be the cloud part. 1 with with the edge components (docker, etc.) 

Both machines start properly. But the edge machine fails to obtain the certificate from cloudcore machine as it tries to connect  on the IPv4 advertised address on port 10002.

The issue is that the cloudcore machine only waits on ipv6 ports 10000 & 10002 (not on same ports for IP v4). Hence, connection from edge fails.

The error message is:

`Nov 22 12:42:18 microk8s-ke-edge edgecore[6634]: F1122 12:42:18.337584    6634 certmanager.go:91] Error: failed to get CA certificate, err: Get "https://34.71.164.171:10002/ca.crt": dial tcp 34.71.164.171:10002: i/o timeout`

When I curl with localhost from the cloudcore machine itself, I get the CA:

```
curl --insecure https://localhost:10002/ca.crt --output ca.crt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   382  100   382    0     0  18190      0 --:--:-- --:--:-- --:--:-- 19100
ddurand@microk8s-ke-cloud:~$ cat ca.crt
0?z0??0
;?^~??US5Na|Q˾|?K ?@?}?ۡJf3<????b?O?<?ܿUG?t????a0_0U??0U%+0U?0?0U?s?l'4?Piӕ??&???o??0
*?H?=I0F!??+r͠?T??????;??IҌ$z?"T?!?tP!????I+2Y?6l0?{J#~ݢu?%?yKݻ
```
If I do same curl, with the public IP address of the cloudcore machine (given by GCE at boot time) from this same cloudcore machine itself, it hangs. Though, ping of the public IP address of the cloudcore machine  from the cloudcore machine will succeed even if it goes through some Google NAT service to translate private IP to public IP. Of course, ping and curl from the cloudcore machine to the cloudcore machine via its private IP (10.x.x.x of RFC1918) work fine.

The issue seems to be that the cloudcore machine only waits on ipv6 ports 10000 & 10002 (and not on same ports for IP v4 - see below). Hence, connection from edge fails.

When I check status on IP ports, I get the following: 

```
sudo netstat -tulpn | grep LISTEN
tcp        0      0 127.0.0.1:19001         0.0.0.0:*               LISTEN      8306/kube-apiserver 
tcp        0      0 127.0.0.1:1338          0.0.0.0:*               LISTEN      8207/containerd     
tcp        0      0 127.0.0.1:42081         0.0.0.0:*               LISTEN      8207/containerd     
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      8372/kubelet        
tcp        0      0 0.0.0.0:25000           0.0.0.0:*               LISTEN      5109/python3        
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      8338/kube-proxy     
tcp        0      0 127.0.0.1:9099          0.0.0.0:*               LISTEN      9238/calico-node    
tcp        0      0 127.0.0.1:10251         0.0.0.0:*               LISTEN      4927/kube-scheduler 
tcp        0      0 127.0.0.1:10252         0.0.0.0:*               LISTEN      4949/kube-controlle 
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      8338/kube-proxy     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      381/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      905/sshd: /usr/sbin 


tcp6       0      0 :::16443                :::*                    LISTEN      8306/kube-apiserver 
tcp6       0      0 :::10250                :::*                    LISTEN      8372/kubelet        
tcp6       0      0 :::10255                :::*                    LISTEN      8372/kubelet        
tcp6       0      0 :::10000                :::*                    LISTEN      7791/cloudcore      
tcp6       0      0 :::10257                :::*                    LISTEN      4949/kube-controlle 
tcp6       0      0 :::10002                :::*                    LISTEN      7791/cloudcore      
tcp6       0      0 :::10259                :::*                    LISTEN      4927/kube-scheduler 
tcp6       0      0 :::22                   :::*                    LISTEN      905/sshd: /usr/sbin
```

**What you expected to happen**:

I would expect cloudcore to wait cloudcore to wait on both ipv4 & ipv6 ports 10000 & 10002.

The config has the proper advertise address: see below.

Do I have a problem on my configuration that I need to fix ? (see below)

**How to reproduce it (as minimally and precisely as possible)**:

Use standard procedure to install cloud core

**Anything else we need to know?**:

**Environment**:
_Ubuntu:_ 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```
```
cat /etc/kubeedge/config/cloudcore.yaml

apiVersion: cloudcore.config.kubeedge.io/v1alpha1
kind: CloudCore
kubeAPIConfig:
  burst: 200
  contentType: application/vnd.kubernetes.protobuf
  kubeConfig: /home/ddurand/.kube/config
  master: ""
  qps: 100
leaderelection:
  LeaderElect: false
  LeaseDuration: 15s
  RenewDeadline: 10s
  ResourceLock: endpointsleases
  ResourceName: cloudcorelease
  ResourceNamespace: kubeedge
  RetryPeriod: 2s
modules:
  cloudHub:
    advertiseAddress:
    - 34.121.41.139
    edgeCertSigningDuration: 365
    enable: true
    https:
      address: 0.0.0.0
      enable: true
      port: 10002
    keepaliveInterval: 30
    nodeLimit: 1000
    quic:
      address: 0.0.0.0
      maxIncomingStreams: 10000
      port: 10001
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCAKeyFile: /etc/kubeedge/ca/rootCA.key
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
      enable: true
    websocket:
      address: 0.0.0.0
      enable: true
      port: 10000
    writeTimeout: 30
  cloudStream:
    enable: false
    streamPort: 10003
    tlsStreamCAFile: /etc/kubeedge/ca/streamCA.crt
    tlsStreamCertFile: /etc/kubeedge/certs/stream.crt
    tlsStreamPrivateKeyFile: /etc/kubeedge/certs/stream.key
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    tunnelPort: 10004
  deviceController:
    buffer:
      deviceEvent: 1
      deviceModelEvent: 1
      updateDeviceStatus: 1024
    context:
      receiveModule: devicecontroller
      responseModule: cloudhub
      sendModule: cloudhub
    enable: true
    load:
      updateDeviceStatusWorkers: 1
  edgeController:
    buffer:
      configMapEvent: 1
      deletePod: 1024
      endpointsEvent: 1
      podEvent: 1
      queryConfigMap: 1024
      queryEndpoints: 1024
      queryNode: 1024
      queryPersistentVolume: 1024
      queryPersistentVolumeClaim: 1024
      querySecret: 1024
      queryService: 1024
      queryVolumeAttachment: 1024
      secretEvent: 1
      serviceEvent: 1
      updateNode: 1024
      updateNodeStatus: 1024
      updatePodStatus: 1024
    context:
      receiveModule: edgecontroller
      responseModule: cloudhub
      sendModule: cloudhub
    enable: true
    load:
      deletePodWorkers: 4
      queryConfigMapWorkers: 4
      queryEndpointsWorkers: 4
      queryNodeWorkers: 4
      queryPersistentVolumeClaimWorkers: 4
      queryPersistentVolumeWorkers: 4
      querySecretWorkers: 4
      queryServiceWorkers: 4
      queryVolumeAttachmentWorkers: 4
      updateNodeStatusWorkers: 1
      updateNodeWorkers: 4
      updatePodStatusWorkers: 1
    nodeUpdateFrequency: 10
  syncController:
    enable: true

```
