### ISSUE TITLE
Create csisamples hostpath PVC failed

### ISSUE THREAD

**Issue by Ma-Dan** [kubeedge/kubeedge#2551]
**What happened**:
Following https://github.com/kubeedge/kubeedge/tree/master/build/csisamples/hostpath code and CSI guide (https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md), created csi-hostpath-controller statefulset, csi-hostpath-edge daemonset, and storageclass for csi-hostpath, these steps all succeeded. Create PVC failed, csi-hostpath-controller-0 csi-driver container showed these error logs:
```
I0202 08:43:24.884533       1 utils.go:130] gprc call: /csi.v1.Controller/CreateVolume
I0202 08:43:24.884591       1 utils.go:131] gprc request: {"capacity_range":{"required_bytes":1073741824},"name":"pvc-ad68f05f-0356-4ce0-b33d-04872dc8bd9f","volume_capabilities":[{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}}]}
I0202 08:43:24.886177       1 controllerserver.go:86] create volume marshal to string: {"name":"pvc-ad68f05f-0356-4ce0-b33d-04872dc8bd9f","capacityRange":{"requiredBytes":"1073741824"},"volumeCapabilities":[{"mount":{"fsType":"ext4"},"accessMode":{"mode":"SINGLE_NODE_WRITER"}}]}
I0202 08:44:24.886881       1 controllerserver.go:114] create volume result: &{{35715d4c-045b-4e6f-bb47-95edd5932213  1612255464886  false} {cloudhub resource error node/edgenode-1/default/volume/b6759256-6532-11eb-8f6f-82bdd730b058} timeout to get response}
E0202 08:44:24.886969       1 controllerserver.go:124] create volume decode with error: illegal base64 data at input byte 7
E0202 08:44:24.887001       1 utils.go:134] gprc error: illegal base64 data at input byte 7
```

**What you expected to happen**:
Create volume successfully and workload can use this volume.

**How to reproduce it (as minimally and precisely as possible)**:
1. kubectl create -f csicontroller.yaml (modify KUBE_NODE_NAME to actual node name)
2. kubectl create -f csinode.yaml
3. kubectl create -f sc.yaml
4. kubectl create -f pvc.yaml

**Anything else we need to know?**:

**Environment**:
<details><summary>Kubernets Version</summary>

```console
$ kubelet --version
Kubernetes v1.17.9
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

<details><summary>CloudCore Version</summary>

```console
$ cloudcore --version
KubeEdge v1.5.0
```

</details>

<details><summary>EdgeCore Version</summary>

```console
$ edgecore --version
KubeEdge v1.5.0
```

</details>

**CloudSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**EdgeSide Environment**:
<details><summary>Hardware configuration</summary>

```console
$ lscpu
# paste output here
```

</details>

<details><summary>OS</summary>

```console
$ cat /etc/os-release
# paste output here
```

</details>

<details><summary>Kernel</summary>

```console
$ uname -a
# paste output here
```

</details>

<details><summary>Go version</summary>

```console
$ go version
# paste output here
```

</details>

<details><summary>Others</summary>
</details>

**Comment by Ma-Dan** [comment]
https://github.com/kubeedge/kubeedge/pull/2133

**Comment by Ma-Dan** [comment]
With following modification, CSI hostpath can work on edge nodes.
(1) Update csi-provisioner to quay.io/k8scsi/csi-provisioner:v1.4.0 (https://github.com/kubeedge/kubeedge/blob/master/build/csisamples/hostpath/deploy/csicontroller.yaml#L110), csi-attacher to quay.io/k8scsi/csi-attacher:v2.1.0 (https://github.com/kubeedge/kubeedge/blob/master/build/csisamples/hostpath/deploy/csicontroller.yaml#L120)
(2) Apply code form this PR (https://github.com/kubeedge/kubeedge/pull/2133),  and update images of cloudcore, edgecore and csidriver(https://github.com/kubeedge/kubeedge/blob/master/build/csisamples/hostpath/deploy/csicontroller.yaml#L129)
(2) Add more resource access to clusterrole
external-controller-runner(https://github.com/kubeedge/kubeedge/blob/master/build/csisamples/hostpath/deploy/csicontroller.yaml#L8)
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-controller-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
```

kubeedge cloudcore (https://github.com/kubeedge/kubeedge/blob/master/build/cloud/03-clusterrole.yaml#L1)
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudcore
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/status", "configmaps", "pods", "pods/status", "secrets", "endpoints", "services"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update"]
- apiGroups: ["devices.kubeedge.io"]
  resources: ["devices", "devicemodels", "devices/status", "devicemodels/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["reliablesyncs.kubeedge.io"]
  resources: ["objectsyncs", "clusterobjectsyncs", "objectsyncs/status", "clusterobjectsyncs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["rules.kubeedge.io"]
  resources: ["rules", "ruleendpoints"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update"]
```

On edge nodes, PVC is mounted like below
```
I0207 07:27:45.465876       1 mount_linux.go:164] Detected OS without systemd
I0207 07:27:45.465905       1 mount_linux.go:146] Mounting cmd (mount) with arguments ([-o bind /csi-data-dir/e142a339-6915-11eb-8606-52542262f658 /var/lib/edged/pods/dd79b861-9058-4a20-a184-a310aa849e1e/volumes/kubernetes.io~csi/pvc-8ee4b66c-eee3-4302-84b1-fc60af00ff66/mount])
I0207 07:27:45.477015       1 mount_linux.go:146] Mounting cmd (mount) with arguments ([-o bind,remount /csi-data-dir/e142a339-6915-11eb-8606-52542262f658 /var/lib/edged/pods/dd79b861-9058-4a20-a184-a310aa849e1e/volumes/kubernetes.io~csi/pvc-8ee4b66c-eee3-4302-84b1-fc60af00ff66/mount])
```

Container modified files on /data is mapped to /var/lib/edged/pods/dd79b861-9058-4a20-a184-a310aa849e1e/volumes/kubernetes.io~csi/pvc-8ee4b66c-eee3-4302-84b1-fc60af00ff66/mount on host node.

But there are some error logs in cloudcore output, although persistent volume is working on edge nodes, there might still be some information not correctly synced.
```
E0207 07:45:01.633105       1 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.Rule: failed to list *v1.Rule: the server could not find the requested resource (get rules.rules.kubeedge.io)
E0207 07:45:02.421324       1 synccontroller.go:168] Unsupported object kind: persistentvolumeclaim
E0207 07:45:02.421415       1 synccontroller.go:168] Unsupported object kind: volumeattachment
E0207 07:45:02.421450       1 synccontroller.go:168] Unsupported object kind: persistentvolume
E0207 07:45:07.421773       1 synccontroller.go:168] Unsupported object kind: persistentvolumeclaim
E0207 07:45:07.421808       1 synccontroller.go:168] Unsupported object kind: volumeattachment
E0207 07:45:07.421827       1 synccontroller.go:168] Unsupported object kind: persistentvolume
E0207 07:45:12.388820       1 reflector.go:127] github.com/kubeedge/kubeedge/cloud/pkg/client/informers/externalversions/factory.go:119: Failed to watch *v1.RuleEndpoint: failed to list *v1.RuleEndpoint: the server could not find the requested resource (get ruleendpoints.rules.kubeedge.io)
E0207 07:45:12.422086       1 synccontroller.go:168] Unsupported object kind: persistentvolume
E0207 07:45:12.422208       1 synccontroller.go:168] Unsupported object kind: persistentvolumeclaim
E0207 07:45:12.422240       1 synccontroller.go:168] Unsupported object kind: volumeattachment
E0207 07:45:17.422400       1 synccontroller.go:168] Unsupported object kind: persistentvolume
E0207 07:45:17.422496       1 synccontroller.go:168] Unsupported object kind: persistentvolumeclaim
E0207 07:45:17.422511       1 synccontroller.go:168] Unsupported object kind: volumeattachment
```

**Comment by SheepSheepChen** [comment]
After applying #2133, pvc can not be created too
csi-driver container showed these error logs:
`E0308 15:36:29.326062       1 controllerserver.go:124] create volume decode with error: illegal base64 data at input byte 0
E0308 15:36:29.326078       1 utils.go:134] gprc error: illegal base64 data at input byte 0`

**Comment by Ma-Dan** [comment]
Please compile code from this branch [https://github.com/kubesphere/kubeedge/tree/csi-dev](https://github.com/kubesphere/kubeedge/tree/csi-dev ) and update cloudcore
csi provisioner/attacher also need update, use the following yamls, fill <xxx> with edge node's name
csicontroller.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller
  namespace: kubeedge

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-controller-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-role
subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kubeedge
roleRef:
  kind: ClusterRole
  name: external-controller-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kubeedge
  name: external-controller-cfg
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-role-cfg
  namespace: kubeedge
subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kubeedge
roleRef:
  kind: Role
  name: external-controller-cfg
  apiGroup: rbac.authorization.k8s.io

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-controller
  namespace: kubeedge
spec:
  serviceName: "csi-hostpath-controller"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-controller
  template:
    metadata:
      labels:
        app: csi-hostpath-controller
    spec:
      serviceAccountName: csi-controller
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.4.0
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --connection-timeout=15s
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v2.1.0
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: csi-socket-dir
        - name: csi-driver
          image: dockerhub.qingcloud.com/kubeedge/csidriver:v1.5.0-beta.0-288-g6a8514a3
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--drivername=$(CSI_DRIVERNAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--kubeedge-endpoint=$(KUBEEDGE_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_DRIVERNAME
              value: csi-hostpath
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBEEDGE_ENDPOINT
              value: unix:///kubeedge/kubeedge.sock
            - name: KUBE_NODE_NAME
              # replace this value with the name of edge node
              # which is in charge of Create Volume and Delete Volume,
              # Controller Publish Volume and Controller Unpublish Volume.
              value: <xxx>
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
            - mountPath: /kubeedge
              name: kubeedge-socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: csi-socket-dir
        - hostPath:
            path: /var/lib/kubeedge
            type: DirectoryOrCreate
          name: kubeedge-socket-dir
```

csinode.yaml
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-edge
  namespace: kubeedge
spec:
  selector:
    matchLabels:
      app: csi-hostpath-edge
  template:
    metadata:
      labels:
        app: csi-hostpath-edge
    spec:
      hostNetwork: true
      nodeName: <xxx>
      nodeSelector:
        node-role.kubernetes.io/edge: ''
        kubernetes.io/hostname: <xxx>
      tolerations:
        - key: node.kubeedge.io
          operator: Equal
          value: edge
          effect: "NoSchedule"
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-hostpath /registration/csi-hostpath-reg.sock"]
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/edged/plugins/csi-hostpath/csi.sock
          securityContext:
            privileged: true
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name:  csi-hostpath-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/k8scsi/hostpathplugin:v1.3.0
          imagePullPolicy: IfNotPresent
          args:
            - "--drivername=csi-hostpath"
            - "--v=5"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--endpoint=unix:///csi/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: plugins-dir
              mountPath: /var/lib/edged/plugins
              mountPropagation: Bidirectional
            - name: mountpoint-dir
              mountPath: /var/lib/edged/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/edged/plugins/csi-hostpath
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/edged/plugins_registry
            type: DirectoryOrCreate
        - name: plugins-dir
          hostPath:
            path: /var/lib/edged/plugins
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/edged/pods
            type: DirectoryOrCreate
```

sc.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-hostpath-sc
provisioner: csi-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

pvc.yaml
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-hostpath-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
```

busybox.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sleep", "1000000"]
        volumeMounts:
        - mountPath: "/data"
          name: my-csi-volume
      volumes:
        - name: my-csi-volume
          persistentVolumeClaim:
            claimName: csi-hostpath-pvc
      nodeSelector:
        node-role.kubernetes.io/edge: ''
        kubernetes.io/hostname: <xxx>
```
