### ISSUE TITLE
Device values can not support space and {}

### ISSUE THREAD

**Issue by Joey2021-dev** [kubeedge/kubeedge#2584]
**What happened**:
In our scene，set some complex strings (like json format) to device value, it was failed when strings contain “ ” and "{}"

edgecore log:

```
E0225 11:30:40.789280   26290 twin.go:104] Unmarshal update request body failed, err: &errors.errorString{s:"The value of twin must only include upper or lowercase letters, number, english, and special letter - _ . , : / @ # and the length of value should be less than 512 bytes"}
E0225 11:30:40.789402   26290 twin.go:63] TwinModule deal TwinCloudSync event failed
```

**What you expected to happen**:

space and {} can be supported in device value.

**How to reproduce it (as minimally and precisely as possible)**:
1. config device file:

```
twins:
    - propertyName: test
      desired:
        metadata:
          type: string
        value: "{test: message}"
```
2. create/update device 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

v1.17.3

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

v1.5.0

- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):

v1.5.0  

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by kevin-wangzefeng** [comment]
have you tried `>` or `|-` ?

```yaml
twins:
    - propertyName: test
      desired:
        metadata:
          type: string
        value: > {test: message}
```
