### ISSUE TITLE
[Autonomic Kube-API Endpoint] feature Introduction

### ISSUE THREAD

**Issue by GsssC** [kubeedge/kubeedge#2760]
# Autonomic Kube-API Endpoint
Autonomic Kube-API Endpoint(hereinafter referred to as AKE) is a very critical feature for meeting the requirement of accessing Kube API Instance at edge. It is a HTTP server to serve the Kube API request from kubernetes client (e.g. kubectl kubelet kubeproxy cni-plugin-agent istio). For now, it could serve most of Kube API verb like **Get List Watch Create Delete Update Patch**. [More Detail](https://github.com/GsssC/kubeedge/blob/ake-proposal/docs/proposals/Autonomic%20Kube-API%20Endpoints.md)
![image](https://user-images.githubusercontent.com/29768082/114855474-97e98780-9e18-11eb-8bf0-b4b9e605f947.png)

## **Benifits**
- **Feature development against edge scene would be decoupled with edgecore**
- **Compatible with kubernetes native solutions, like kubelet, istio, etc**
- **No longer need to extend new controllers in cloudcore if edges want new kind of Kube API.** 
## **Feature track**:
- [x] Support Get List Watch Create Delete Update Patch
- [x] Support to access CRDs
- [ ] **Add proposal and document in both Chinese and English(Urgent)**
- [ ] **Add e2e test(Urgent)**
- [ ] Add AKE client(an implementation of [clientset.Interface](https://github.com/kubernetes/kubernetes/blob/c90330d8f4ca9fd980df24044960a4d8bb28a780/staging/src/k8s.io/client-go/kubernetes/clientset.go#L70)) to meet **in-process accessing** requirement
- [ ] Add **lifecycle and Gabbage-Collection for listener and informer**(components to serve watch request) at cloud
- [ ] Support to serve request when Accept and Content-Type is **"application/vnd.kubernetes.protobuf"**
- [ ] Support **identification and authentication** of request.
- [ ] Try [Bbolt](https://github.com/etcd-io/bbolt) as basic storage.

## **Related Works**:
- [ ] Refactor edged to get Kube API by AKE client
- [ ] Try to move edged out of edgecore as a release of lite-kubelet.
- [ ] Refactor device-twin to get device api by AKE client
# User Manual
## Enable AKE feature
To enable AKE feature we need to config cloudcore and edgecore to enable ake-related modules, and would better disable other module.
### **1. Config CloudCore**
Enable **DynamicController**, **SyncController** and **CloudHub** like below:
```yaml
apiVersion: edgecore.config.kubeedge.io/v1alpha1
kind: CloudCore
modules:
  cloudHub:
    enable: true
  dynamicController:
    enable: true
  syncController:
    enable: true
```
### 2. Config EdgeCore
Enable **MetaManager**, **MetaManager/metaserver** and **EdgeHub** like below:
```yaml
apiVersion: edgecore.config.kubeedge.io/v1alpha1
kind: EdgeCore
modules:
  EdgeHub
    enable: true
  MetaManager:
    enable: true
    metaServer:  //metaServer is sub moduler of MetaManager
      enable: true
```
Start or Restart both cloudcore and edgecore, now we could acess Kube API at edge node(deployed with edgecore) through **`http://127.0.0.1:10550`** .
## Use Curl to access
[Kubernetes API Reference](https://kubernetes.io/docs/reference/kubernetes-api/) tell us what's the RESTful HTTP Kube API request path like,  if we want to get a certain Kube API object. For example [v1.Pod](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Operations), section _Operations/HTTP request_ shows:

> GET /api/v1/namespaces/{namespace}/pods/{name}

According to above information, there are some example to construct HTTP request with curl:
1. List all pods, `curl -s http://127.0.0.1:10550/api/v1/pods`
2. List all pods in namespace kube-system, `curl -s http://127.0.0.1:10550/api/v1/namespaces/kube-system/pods`
3. Get certain pod, `curl -s http://127.0.0.1:10550/api/v1/namespaces/{ns-foo}/pods/{pod-name-bar}`
4. Get certain endpoint, `curl -s http://127.0.0.1:10550/api/v1/namespaces/default/endpoints/kubernetes`
5. Watch all endpoint change, `curl -s http://127.0.0.1:10550/api/v1/endpoints?watch=true`
## Use Kubectl to acess (enable after https://github.com/kubeedge/kubeedge/pull/2770)
It is very hard to remember all complex Kube API path above. So we recommend to use **kubectl**, it automaticly translate human-friendly command to RESTful HTTP Kube API request. Now we:

1.  support part of command like **get, delete, create, describe, -o yaml**,  
2.  but do not support **No-Object** command like **attach, top, exec, proxy,logs and so on**.
### Config kubeconfig
The kubectl command line tool lets you control Kubernetes clusters. How to use kubectl please refer to [kubernetes offical guidance document](https://kubernetes.io/docs/reference/kubectl/overview/). Before using kubectl, we need to prepare a kubeconfig which points to metaserver. There are two ways to achieve it:
#### 1. create a new kubeconfig
The content of new kubeconfig is like below, name it _ake-kubeconfig.yaml_, and then use `kubectl --kubeconfig=ake-kubeconfig.yaml` every time when access metaserver.
```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://127.0.0.1:10550
  name: ake-test-cluster
contexts:
- context:
    cluster: ake-test-cluster
    user: ""
  name: ake-test-ctx
current-context: ake-test-ctx
preferences: {}
users: null
```
#### 2. modify default kubeconfig file at _~/.kube/config_ if have.
Add a new context called _ake-test-ctx_ and change _current-context_ to it. Use `kubectl config view` to show whether the modified kubeconfig is in effect.
```yaml
apiVersion: v1
kind: Config
clusters:
- cluster: #old cluster, don not touch
  ...
- cluster: #add a new cluster
    server: http://127.0.0.1:10550
  name: ake-test-cluster
contexts:
- context: #old context, do not touch
  ...
- context: #add a new context
    cluster: ake-test-cluster
    user: "" 
  name: ake-test-ctx
current-context: ake-test-ctx #change old context to new
preferences: {} #do not touch
users: #do not touch 
  ...
```
## Adapt Kubelet
TBD
## Adapt Istio
Refer to https://github.com/kubeedge/kubeedge/issues/2677
## Adapt Calico
TBD
