### ISSUE TITLE
failed to list *unstructured.Unstructured: the server could not find the requested resource

### ISSUE THREAD

**Issue by Poorunga** [kubeedge/kubeedge#2769]
**What happened**:
I created some istio crds(gateway, virtualservice, destinationrule), and I can get them through `kubectl`:
```
[root@ke-cloud ~]# kubectl get gateway -n edgemesh-test
NAME                   AGE
edgemesh-gateway-tls   4d1h
[root@ke-cloud ~]# kubectl get virtualservice -n edgemesh-test
NAME                        GATEWAYS                 HOSTS   AGE
edgemesh-gateway-tls-vsvc   [edgemesh-gateway-tls]   [*]     4d1h
```
I want to use the list-watch capability on the `edgecore` to obtain gateway resources, but it failed. Edgecore's list-watch has been ensured to be turned on, because I can get services, pods, configmap and other resources through it. 
The error of `dynamicController` is as follows:
```
I0413 10:46:36.799192   27814 application.go:384] [metaserver/ApplicationCenter] get a Application (NodeName=ke-edge1;Key=/core/v1/gateways/edgemesh-test/null;Verb=list;Status=InApplying;Reason=)
I0413 10:46:36.799272   27814 eventhandler.go:65] [metaserver/HandlerCenter] prepare a new resourceEventHandler(/v1, Resource=gateways)
I0413 10:46:36.799283   27814 eventhandler.go:105] [metaserver/resourceEventHandler] handler(/v1, Resource=gateways) init, prepare informer...
I0413 10:46:36.799322   27814 eventhandler.go:120] [metaserver/resourceEventHandler] handler(/v1, Resource=gateways) init, wait for informer starting...
E0413 10:46:36.800301   27814 reflector.go:127] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0413 10:46:37.889909   27814 reflector.go:127] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**What you expected to happen**:
Able to obtain gateway resources through the edgecore list-watch capabilities.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.17", GitCommit:"f3abc15296f3a3f54e4ee42e830c61047b13895f", GitTreeState:"clean", BuildDate:"2021-01-13T13:13:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
```
cloucore version: KubeEdge v1.6.1
edgecore version: KubeEdge v1.6.1
```
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by Poorunga** [comment]
@fisherxu

**Comment by GsssC** [comment]
What kind of resource dose istio want to get when meet this error? : )

**Comment by Poorunga** [comment]
I did not deploy istio, I just created some istio crds, such as `gateway`, `virtualservice` and `destinationrule`. I can get them through `kubectl`:
```
[root@ke-cloud ~]# kubectl get gateway -n edgemesh-test
NAME                   AGE
edgemesh-gateway-tls   4d1h
[root@ke-cloud ~]# kubectl get virtualservice -n edgemesh-test
NAME                        GATEWAYS                 HOSTS   AGE
edgemesh-gateway-tls-vsvc   [edgemesh-gateway-tls]   [*]     4d1h
```

But I can't get them through edgecore's list-watch:
```
[root@ke-edge1 ~]# curl 127.0.0.1:10550/api/v1/gateways
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "Internal error occurred: the server could not find the requested resource",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "the server could not find the requested resource"
      }
    ]
  },
  "code": 500
}
```

The error of `dynamicController` is as follows:
```
I0413 10:46:36.799192   27814 application.go:384] [metaserver/ApplicationCenter] get a Application (NodeName=ke-edge1;Key=/core/v1/gateways/edgemesh-test/null;Verb=list;Status=InApplying;Reason=)
I0413 10:46:36.799272   27814 eventhandler.go:65] [metaserver/HandlerCenter] prepare a new resourceEventHandler(/v1, Resource=gateways)
I0413 10:46:36.799283   27814 eventhandler.go:105] [metaserver/resourceEventHandler] handler(/v1, Resource=gateways) init, prepare informer...
I0413 10:46:36.799322   27814 eventhandler.go:120] [metaserver/resourceEventHandler] handler(/v1, Resource=gateways) init, wait for informer starting...
E0413 10:46:36.800301   27814 reflector.go:127] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
E0413 10:46:37.889909   27814 reflector.go:127] k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: the server could not find the requested resource
```

**Comment by GsssC** [comment]
@Poorunga  could you show the definition of these crds in yaml?

And I can not find a kube api called gateway in /v1.

**Comment by Poorunga** [comment]
@GsssC  Thank you for your answer.
Here is my CRDs yaml:
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.networking.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: networking.istio.io
  names:
    kind: VirtualService
    listKind: VirtualServiceList
    plural: virtualservices
    singular: virtualservice
    shortNames:
    - vs
    categories:
    - istio-io
    - networking-istio-io
  scope: Namespaced
  version: v1alpha3
  additionalPrinterColumns:
  - JSONPath: .spec.gateways
    description: The names of gateways and sidecars that should apply these routes
    name: Gateways
    type: string
  - JSONPath: .spec.hosts
    description: The destination hosts to which traffic is being sent
    name: Hosts
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: destinationrules.networking.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: networking.istio.io
  names:
    kind: DestinationRule
    listKind: DestinationRuleList
    plural: destinationrules
    singular: destinationrule
    shortNames:
    - dr
    categories:
    - istio-io
    - networking-istio-io
  scope: Namespaced
  version: v1alpha3
  additionalPrinterColumns:
  - JSONPath: .spec.host
    description: The name of a service from the service registry
    name: Host
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceentries.networking.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: networking.istio.io
  names:
    kind: ServiceEntry
    listKind: ServiceEntryList
    plural: serviceentries
    singular: serviceentry
    shortNames:
    - se
    categories:
    - istio-io
    - networking-istio-io
  scope: Namespaced
  version: v1alpha3
  additionalPrinterColumns:
  - JSONPath: .spec.hosts
    description: The hosts associated with the ServiceEntry
    name: Hosts
    type: string
  - JSONPath: .spec.location
    description: Whether the service is external to the mesh or part of the mesh (MESH_EXTERNAL or MESH_INTERNAL)
    name: Location
    type: string
  - JSONPath: .spec.resolution
    description: Service discovery mode for the hosts (NONE, STATIC, or DNS)
    name: Resolution
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: |-
      CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
      Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#metadata
    name: Age
    type: date
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gateways.networking.istio.io
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    release: istio
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: networking.istio.io
  names:
    kind: Gateway
    plural: gateways
    singular: gateway
    shortNames:
    - gw
    categories:
    - istio-io
    - networking-istio-io
  scope: Namespaced
  version: v1alpha3
```
