### ISSUE TITLE
EdgeMesh resolves wrong service

### ISSUE THREAD

**Issue by liamylian** [kubeedge/kubeedge#2845]
**What happened**:

I deployed 3 services (2 service on edge node expose same containerProt and hostPort 80): `Httpd` service on `cluster worker node`, `Nginx` service on `edge node A`, `Caddy` service on `edge node B`.
I login to `edge node A`, and use `curl` to visit `http://nginx-svc.default.svc.cluster.local:12345`, but I got pages from wrong services: sometimes `Caddy` service,  sometimes `Httpd` service, sometimes Nginx (ok), sometimes refused.

After I deploy 3 service using different nodePort and containerPort, EdgeMesh resolves services correctly. 

**What you expected to happen**:

- Visit `http://nginx-svc.default.svc.cluster.local:12345`, returns Nginx home page.
- Visit `http://caddy-svc.default.svc.cluster.local:12346`, returns Caddy home page.
- Visit `http://httpd-svc.default.svc.cluster.local:12347`, returns Httpd home page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install an All-in-One K8s cluster, for eaxmple KubeSphere 3.1.

```shell
# Make sure curl, openssl installed, firewall closed.
apt update 
apt install socat conntrack ebtables ipset
apt install docker.io
cat /etc/resolv.conf

export KKZONE=cn
curl -sfL https://get-kk.kubesphere.io | VERSION=v1.1.0 sh -
chmod +x kk
./kk create cluster --with-kubernetes v1.19.8 --with-kubesphere v3.1.0
```

2. Install KubeEdge

```shell
./keadm init --advertise-address="x.x.x.x"
netstat -nlp
```

3. Add EdgeNode

```shell
# Modify /etc/nsswitch.conf :
# hosts:          dns files mdns4_minimal [NOTFOUND=return]
echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
sysctl -p

apt update
apt install docker.io
./keadm join --cloudcore-ipport=x.x.x.x:10000 --token=x
```

4. Deploy Services

```shell
kubectl apply -f nginx.yml caddy.yml httpd.yml
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:41:51Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.8", GitCommit:"fd5d41537aee486160ad9b5356a9d82363273721", GitTreeState:"clean", BuildDate:"2021-02-17T12:33:08Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

- <details><summary>Cloud nodes Environment:</summary>

  - KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): `KubeEdge v1.6.1`
  - Hardware configuration (e.g. `lscpu`): 4C4G, amd64
  - OS (e.g. `cat /etc/os-release`): Ubuntu 20.04.2 LTS
  - Kernel (e.g. `uname -a`):  5.4.0-73-generic
  - Go version (e.g. `go version`): none
  - Others: none

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): KubeEdge v1.6.1
  - Hardware configuration (e.g. `lscpu`): 2C2G
  - OS (e.g. `cat /etc/os-release`): Ubuntu 20.04.2 LTS
  - Kernel (e.g. `uname -a`):  5.4.0-73-generic
  - Go version (e.g. `go version`): none
  - Others: none

  </details>

## Appendix: 

<details><summary>1. Httpd.yml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4-alpine
          ports:
            - containerPort: 80
              hostPort: 8030
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
        - key: node-role.kubernetes.io/edge
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64

---

apiVersion: v1
kind: Service
metadata:
  name: httpd-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: httpd
  ports:
    - name: http-0
      port: 12347
      protocol: TCP
      targetPort: 80
```
</details>

<details><summary>2. Nginx.yml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 80
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations:
        - key: node-role.kubernetes.io/edge
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: nginx
  ports:
    - name: http-0
      port: 12345
      protocol: TCP
      targetPort: 80
```
</details>

<details><summary>3. Caddy.yml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-deployment
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      hostNetwork: true
      containers:
        - name: caddy
          image: caddy:2.3.0-alpine
          ports:
            - containerPort: 80
              hostPort: 80
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations:
        - key: node-role.kubernetes.io/edge
          operator: Exists
          effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64

---

apiVersion: v1
kind: Service
metadata:
  name: caddy-svc
  namespace: default
spec:
  clusterIP: None
  selector:
    app: caddy
  ports:
    - name: http-0
      port: 12346
      protocol: TCP
      targetPort: 80
```
</details>
