### ISSUE TITLE
resolv.cont conent keep changing

### ISSUE THREAD

**Issue by bluven** [kubeedge/kubeedge#3033]
**What happened**:

I created a pod to do network diagnosing, sometimes I found the resolv.conf file kept changing. It's hard to believe, but it happended, I record it: [https://asciinema.org/a/O2TsjMpN2Pk8poCU5FkYWOeHr](https://asciinema.org/a/O2TsjMpN2Pk8poCU5FkYWOeHr)

pod spec: 
```
apiVersion: v1
kind: Pod
metadata:
  name: net-tool-edge2
  namespace: fabedge-e2e-test
spec:
  automountServiceAccountToken: false
  containers:
  - image: praqma/network-multitool:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    name: net-tool
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: edge2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/edge
    operator: Exists
```

**What you expected to happen**:

 resolv.conf of pod should remain unchanged. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I don't known if it's related, but It seems edgecore didn't prune pods deleted as below shown:
```
root@edge2:~# docker ps | grep net-tool-edge2
0c9a5c65ec27   293c239dd855         "/bin/sh /docker-ent…"   41 minutes ago      Up 41 minutes                k8s_net-tool_net-tool-edge2_fabedge-e2e-test_1d2772f2-971a-49f6-965e-c8ab08c56467_0
d0d384f04d4a   kubeedge/pause:3.1   "/pause"                 41 minutes ago      Up 41 minutes                k8s_POD_net-tool-edge2_fabedge-e2e-test_1d2772f2-971a-49f6-965e-c8ab08c56467_0
9e7d8ab43bb8   293c239dd855         "/bin/sh /docker-ent…"   2 hours ago         Up 2 hours                   k8s_net-tool_net-tool-edge2_fabedge-e2e-test_476dc6f5-54e5-4ce6-b79e-ce428384ad0a_0
729b147907b0   kubeedge/pause:3.1   "/pause"                 2 hours ago         Up 2 hours                   k8s_POD_net-tool-edge2_fabedge-e2e-test_476dc6f5-54e5-4ce6-b79e-ce428384ad0a_0
cb63190d402c   293c239dd855         "/bin/sh /docker-ent…"   2 hours ago         Up 2 hours                   k8s_net-tool_net-tool-edge2_fabedge-e2e-test_988059db-3512-4e29-9df0-eb5664a5b855_0
c747fc551260   kubeedge/pause:3.1   "/pause"                 2 hours ago         Up 2 hours                   k8s_POD_net-tool-edge2_fabedge-e2e-test_988059db-3512-4e29-9df0-eb5664a5b855_0
28206a5fe16e   293c239dd855         "/bin/sh /docker-ent…"   2 days ago          Up 2 days                    k8s_net-tool_net-tool-edge2_fabedge-e2e-test_32b06acc-bdf8-44d0-a7bc-2cbd128c2b71_0
8c78c4f75478   kubeedge/pause:3.1   "/pause"                 2 days ago          Up 2 days                    k8s_POD_net-tool-edge2_fabedge-e2e-test_32b06acc-bdf8-44d0-a7bc-2cbd128c2b71_0
7bdae0dd8a38   293c239dd855         "/bin/sh /docker-ent…"   2 days ago          Up 2 days                    k8s_net-tool_net-tool-edge2_fabedge-e2e-test_d236f304-e74e-46f2-b592-c576c970bcb9_0
de17dc73ad00   kubeedge/pause:3.1   "/pause"                 2 days ago          Up 2 days                    k8s_POD_net-tool-edge2_fabedge-e2e-test_d236f304-e74e-46f2-b592-c576c970bcb9_0
```
net-tool-edge2 is the debug pod I created several times.

by the way: It's more wierd. But when I executed `docker exec net-tool-edge2 -- cat /etc/resolv.conf', the content remain the same and is the expected content:
```
root@edge2:~# docker exec -ti 0c9a5c65ec27 sh
/ # cat /etc/resolv.conf 
nameserver 169.254.25.10
search fabedge-e2e-test.svc.root-cluster svc.root-cluster root-cluster openstacklocal
options ndots:5
```

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): KubeEdge v1.5.0

 - <details><summary>Cloud nodes Environment:</summary>
  - Hardware configuration (e.g. `lscpu`): 
 Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              10
On-line CPU(s) list: 0-9
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           10
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               94
Model name:          Intel Core Processor (Skylake)
Stepping:            3
CPU MHz:             2199.996
BogoMIPS:            4399.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-9
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat

  - OS (e.g. `cat /etc/os-release`): 
 NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

  - Kernel (e.g. `uname -a`): `Linux master1 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
  - Go version (e.g. `go version`):
  - Others:
  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
