### ISSUE TITLE
edge use kubeconfig to list/watch apiserver?

### ISSUE THREAD

**Issue by yttan** [kubeedge/kubeedge#3053]
**What happened and what you expected to happen**:

I succeeded to get resources from metaserver using curl like this:

```
curl -s http://127.0.0.1:10550/api/v1/namespaces/default/endpoints/kubernetes
```

But when it comes to constructing a kubeconfig file to list/watch from apiserver, I got errors.

this is the kubeconfig file:

```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://127.0.0.1:10550
  name: ake-test-cluster
contexts:
- context:
    cluster: ake-test-cluster
    user: ""
  name: ake-test-ctx
current-context: ake-test-ctx
preferences: {}
users: null
```

the command:

```
kubectl --kubeconfig=config get po
```

the log

```log
Error from server (InternalError): Internal error occurred: not a resource req
```

From the log I see kubectl requests http://127.0.0.1:10550/api/ 

```
curl -s http://127.0.0.1:10550/api/
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Internal error occurred: not a resource req",
  "reason": "InternalError",
  "details": {
    "causes": [
      {
        "message": "not a resource req"
      }
    ]
  },
  "code": 500
}
```

Anything I missed from this issue https://github.com/kubeedge/kubeedge/issues/2760 ?

Is it possible to construct a kubeconfig file and use it to get resources from apiserver for now? My kubeedge version is v1.7.1

If not, do you have any plans or roadmap to support it in the future?

cc @GsssC

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
