### ISSUE TITLE
Unable to resolve service names

### ISSUE THREAD

**Issue by salmanazmat666** [kubeedge/kubeedge#3062]
**What happened and what you expected to happen**:
I have two pods and two services on edge. From one pod I cannot hit the http endpoint of other pod. Following curl fails

> /data # curl http://edgex-core-consul.default:8500
> curl: (6) Could not resolve host: edgex-core-consul.default

curl works if I use the IP of the container instead of service name.

**How to reproduce it (as minimally and precisely as possible)**:
Following are two yaml files for two pods and respective services.

I do `curl http://edgex-core-consul.default:8500` from the redis container.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-core-consul
  labels:
    app.kubernetes.io/app: edgex-core-consul
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/app: edgex-core-consul
      app.kubernetes.io/instance: edgex
      app.kubernetes.io/version: 1.3.1
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: edgex-foundry
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: edgex-1.3.1

  template:
    metadata:
      name: edgex-core-consul
      labels:
        app.kubernetes.io/app: edgex-core-consul
        app.kubernetes.io/instance: edgex
        app.kubernetes.io/version: 1.3.1
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: edgex-foundry
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: edgex-1.3.1

    spec:
      hostname: edgex-core-consul
      containers:
      - name: edgex-core-consul
        image: edgexfoundry/docker-edgex-consul:1.3.0
        imagePullPolicy: IfNotPresent
        env:
          - name: EDGEX_DB
            value: "redis"
          - name: EDGEX_SECURE
            value: "false"
        ports:
        - name: tcp-8500
          protocol: TCP
          containerPort: 8500
        - name: tcp-8400
          protocol: TCP
          containerPort: 8400
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 2
            memory: 2048Mi
          requests:
            cpu: 1
            memory: 1024Mi
        volumeMounts:
        - name: consul-config
          mountPath: /consul/config
        - name: consul-data
          mountPath: /consul/data
        - name: consul-scripts
          mountPath: /consul/scripts
      volumes:
        - name: consul-config
          hostPath:
            path: /consul/config
            type: DirectoryOrCreate
        - name: consul-data
          hostPath:
            path: /consul/data
            type: DirectoryOrCreate
        - name: consul-scripts
          hostPath:
            path: /consul/scripts
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: edgex-core-consul
  labels:
    app.kubernetes.io/app: edgex-core-consul
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  selector:
    app.kubernetes.io/app: edgex-core-consul
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

  ports:
  - port: 8500
    name: "port-8500"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-consul
  labels:
    app.kubernetes.io/app: edgex-consul
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/consul-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-consul
  labels:
    app.kubernetes.io/app: edgex-consul
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: edgex-consul
      app.kubernetes.io/instance: edgex
      app.kubernetes.io/version: 1.3.1
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: edgex-foundry
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: edgex-1.3.1

  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
```

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgex-redis
  labels:
    app.kubernetes.io/app: edgex-redis
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/app: edgex-redis
      app.kubernetes.io/instance: edgex
      app.kubernetes.io/version: 1.3.1
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: edgex-foundry
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: edgex-1.3.1

  template:
    metadata:
      name: edgex-redis
      labels:
        app.kubernetes.io/app: edgex-redis
        app.kubernetes.io/instance: edgex
        app.kubernetes.io/version: 1.3.1
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: edgex-foundry
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: edgex-1.3.1

    spec:
      hostname: edgex-redis
      containers:
      - name: edgex-redis
        image: "redis:6.0.9-alpine"
        ports:
        - containerPort: 6379
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /data
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: edgex-redis
  labels:
    app.kubernetes.io/app: edgex-redis
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  selector:
    app.kubernetes.io/app: edgex-redis
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

  ports:
  - port: 6379
    name: "port-6379"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: edgex-redis
  labels:
    app.kubernetes.io/app: edgex-redis
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/mnt/edgex-redis-volume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: edgex-redis
  labels:
    app.kubernetes.io/app: edgex-redis
    app.kubernetes.io/instance: edgex
    app.kubernetes.io/version: 1.3.1
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: edgex-foundry
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: edgex-1.3.1

spec:
  selector:
    matchLabels:
      app.kubernetes.io/app: edgex-redis
      app.kubernetes.io/instance: edgex
      app.kubernetes.io/version: 1.3.1
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: edgex-foundry
      app.kubernetes.io/managed-by: Helm
      helm.sh/chart: edgex-1.3.1

  storageClassName: hostpath
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

**Anything else we need to know?**:
Following is the output of `kubectl get nodes`
```
$ sudo kubectl get nodes -n default
NAME                    STATUS   ROLES                  AGE   VERSION
ubuntu-sazmat           Ready    control-plane,master   44h   v1.19.14+k3s1
localhost.localdomain   Ready    agent,edge             24h   v1.19.3-kubeedge-v1.7.2
```
Following the output of `kubectl get pods`
```
$ sudo kubectl get pods -n default
NAME                                 READY   STATUS    RESTARTS   AGE
edgex-redis-56d57b4cc6-4z8nr         1/1     Running   1          24h
edgex-core-consul-78dcc849f8-n4zw2   1/1     Running   0          24h
```

**Environment**:
I'm using `K3S` on cloud side.
`K3S` version is `v1.19.14+k3s1`.
`kubectl version` output is 

> Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14+k3s1", GitCommit:"58c4dd55265913821479b3f371f191bf3630d2e1", GitTreeState:"clean", BuildDate:"2021-08-20T07:15:28Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.14+k3s1", GitCommit:"58c4dd55265913821479b3f371f191bf3630d2e1", GitTreeState:"clean", BuildDate:"2021-08-20T07:15:28Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

I used `keadm` to install cloud and edge side software.
`keadm` version is `v1.7.2-linux-amd64`.
