### ISSUE TITLE
modbus mapper in mappers-go cannot get time-series data properties

### ISSUE THREAD

**Issue by waynechan9** [kubeedge/kubeedge#3063]
**What happened**:
When I tried to deploy modbus mappers in [mappers-go/modbus](https://github.com/kubeedge/mappers-go/tree/main/mappers/modbus), and use the following [modbus device yaml](https://github.com/kubeedge/mappers-go/blob/main/build/crd-samples/devices/modbustcp-device-instance.yaml) to create the device,  I cannot get modbus data property "temperature". 

```
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: modbustcp-device
  labels:
    description: TISimplelinkSensorTag
    manufacturer: TexasInstruments
    model: CC2650
spec:
  deviceModelRef:
    name: modbus-sample-model
  protocol:
    modbus:
      slaveID: 1
    common:
      tcp:
        ip: "192.168.33.1"
        port: 502
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: ''
        operator: In
        values:
        - test
  propertyVisitors:
    - propertyName: temperature
      modbus:
        register: CoilRegister
        offset: 0
        limit: 1
        scale: 1
        isSwap: true
        isRegisterSwap: true
      collectCycle: 5000
    - propertyName: temperature-enable
      modbus:
        register: CoilRegister
        offset: 3
        limit: 1
        scale: 1.0
        isSwap: true
        isRegisterSwap: true
  data:
    dataProperties:
      - propertyName: temperature
        metadata:
          type: int
status:
  twins:
    - propertyName: temperature-enable
      reported:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "0"
      desired:
        metadata:
          timestamp: '1550049403598'
          type: integer
        value: "0"
```

I Just add `spec.data` section in modbustcp-device-instance.yaml sample, then tail  modbus-mapper-xxx pod  logs or use MQTT client to subscribe topic `$ke/events/device/+/data/update`, just cannot get temperature time-serials data.

**What you expected to happen**:
1. When subscribe edgenode MQTT topic  `$ke/events/device/+/data/update`, can get temperature time-serials data.

**How to reproduce it (as minimally and precisely as possible)**:
1. Simulate device or use real device with modbus protocal.
2. Modify sample [modbustcp-device-instance.yaml](https://github.com/kubeedge/mappers-go/blob/main/build/crd-samples/devices/modbustcp-device-instance.yaml), add `spec.data` section below.
```
  data:
    dataProperties:
      - propertyName: temperature
        metadata:
          type: int
```
3. Build modbus mapper docker image, and execute `kubectl apply -f mappers-go/mappers/modbus/deployment.yaml`
4. Use MQTT client to subscribe edgenode topic `$ke/events/device/+/data/update`, to see can get message or not. 

**Anything else we need to know?**:
After some debug, it was found that it was due to dataProperty section misplaced in configmap device-profile-config-xx.

**Environment**:
- KubeEdge version v1.17.2
