### ISSUE TITLE
Can't get enviroment value of secret when the pod in the edge node

### ISSUE THREAD

**Issue by khalid-jobs** [kubeedge/kubeedge#3180]
**What happened**:
I create a deployment ,and the deployment use a secretKeyRef like below:
```
- name: CA_SERVER_TOKEN
  valueFrom:
    secretKeyRef:
        name: tokensecret
        key: tokendata
```
When the deployment runs in the cloud node, it works. But When it runs in the edge node, the container can not get the `CA_SERVER_TOKEN` value
**What you expected to happen**:
The pod in the edge node should can get the `CA_SERVER_TOKEN` env

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the kubeedge and deploy a deployment with secretKeyRef.
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.5
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.7.2
