### ISSUE TITLE
`kubectl logs` i/o timeout

### ISSUE THREAD

**Issue by king-jingxiang** [kubeedge/kubeedge#3281]
**What happened**:
`iptables -t nat -A OUTPUT -p tcp --dport 10353 -j DNAT --to CLOUDCOREIP:30003`
kubectl logs timeout
```bash
$ kubectl logs app-nginx-hostnet-edge-5958db7c75-4dj64 -nleinaoyun-os-edge
Error from server: Get "https://10.10.8.8:10353/containerLogs/leinaoyun-os-edge/app-nginx-hostnet-edge-5958db7c75-4dj64/container-zbauk8": dial tcp 10.10.8.8:10353: connect: connection refused
$ sudo iptables -t nat -A OUTPUT -p tcp --dport 10353 -j DNAT --to 10.12.3.7:30003
$ time kubectl logs app-nginx-hostnet-edge-5958db7c75-4dj64 -nleinaoyun-os-edge
Error from server: Get "https://10.10.8.8:10353/containerLogs/leinaoyun-os-edge/app-nginx-hostnet-edge-5958db7c75-4dj64/container-zbauk8": dial tcp 10.10.8.8:10353: i/o timeout

real  0m30.118s
user  0m0.297s
sys 0m0.107s
```
cloudcore errors logs
```
E1109 02:10:25.309924       1 iptables.go:98] "Failed to ensure chain exists" err="error creating chain \"TUNNEL-PORT\": executable file not found in $PATH: " table=nat chain=TUNNEL-PORT
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
```
KubeEdge v1.8.2
```
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by QeelinDarly** [comment]
Do you have open your cloudStream and edgeStream before your operation?

**Comment by king-jingxiang** [comment]
> Do you have open your cloudStream and edgeStream before your operation?


the cloudStream and edgeStream is opened.
> kubectl get cm -nkubeedge cloudcore -oyaml
```
      cloudStream:
        enable: true
        streamPort: 10003
        tunnelPort: 10004
```

> /etc/kubeedge/config/edgecore.yaml
```
  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: 10.12.3.7:30004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15
```
