### ISSUE TITLE
pv's objectsync spec.ObjectKind is empty

### ISSUE THREAD

**Issue by neiba** [kubeedge/kubeedge#3585]
**What happened**:

persistentvolume's objectsync spec.ObjectKind is empty

**What you expected to happen**:

persistentvolume's objectsync spec.ObjectKind should be persistentvolumes

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /opt/persistentvolumes/vol-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node02
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: Exists
      containers:
      - name: busybox
        image: busybox:1.34.1
        command:
        - "sleep"
        args:
        - "infinity"
        volumeMounts:
        - mountPath: /vol-1
          name: vol-1
      volumes:
      - name: vol-1
        persistentVolumeClaim:
          claimName: vol-1
```

**Anything else we need to know?**:

i think k8s client get object, which typemeta is nil, caused the problem. https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/edgecontroller/controller/upstream.go#L561

i found it in v1.6.2，and i think it exists in master too.

**Environment**:
- Kubernetes version (use `kubectl version`): v.1.19.16
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.6.2
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): 
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
