### ISSUE TITLE
Dose MetaServer(Autonomic Kube-API Endpoint) on edgecore sopport coreDNS's kube-api query?

### ISSUE THREAD

**Issue by Alexandersande18** [kubeedge/kubeedge#4100]
**What happened and what you expected to happen**:
I tried to deploy coreDNS pods on edge nodes to support native DNS for edge subnets. But it seems like the coreDNS was not working(pod running but not woring for k8s name service). Dose MetaServer on edgecore Sopport coreDNS's kube-api query?
**How to reproduce it**:
I enabled the metaserver feature and it works well(curl tested).
I set the endpoint field in coreDNS to `http://127.0.0.1:10550`
I used **host network mode** to deploy coreDNS pod, so it can access metaserver through 127.0.0.1.
Here is my coreDNS yaml for deploying:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-edge1
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          endpoint http://127.0.0.1:10550
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . 223.5.5.5 {
          max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns-edge1
  namespace: kube-system
  labels:
    k8s-app: kube-dns-edge1
    kubernetes.io/name: "CoreDNS-edge1"
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns-edge1
  template:
    metadata:
      labels:
        k8s-app: kube-dns-edge1
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: coredns
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: Exists
      containers:
      - name: coredns
        image: coredns/coredns:1.9.3
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        args: [ "-conf", "/etc/coredns/Corefile" ]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
          readOnly: true
      dnsPolicy: Default
      hostNetwork: true
      volumes:
        - name: config-volume
          configMap:
            name: coredns-edge1
            items:
            - key: Corefile
              path: Corefile
```
Here is the log of coreDNS pod:
![0Y LFV8V4R%6G4%_G8G Y$A](https://user-images.githubusercontent.com/38888486/183069373-4bd33add-a9bf-4471-89bf-708d22dc50b9.png)
**Anything else we need to know?**:
coreDNS works for other non-k8s name querys:
![NVFL1$(E)K9000$%Q%FTG7D](https://user-images.githubusercontent.com/38888486/183070257-ad9ac788-5dd6-47da-be03-935c5cd4778a.png)
**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:16:05Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
cloudcore: KubeEdge v1.9.1
edgecore: KubeEdge v1.9.1
