### ISSUE TITLE
How I install weave on the edge node

### ISSUE THREAD

**Issue by vincentgoat** [kubeedge/kubeedge#4161]
1. Install weave

```
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&disable-npc=true"
```

If you need network policies please don't set `disable-npc` to true.

The prerequisite is that we should configure kube-client in `weave`, please refer to https://github.com/kubeedge/kubeedge/issues/3935#issuecomment-1234962037.

2. configure cloudcore

```
dynamicController:
  enable: true
  ...
```

3. configure edgecore

```
edged:
  ...
  clusterDNS: "10.32.0.1" --- weave bridge ip on edge node
  networkPluginName: cni
  clusterDomain: "cluster.local"
  cniBinDir: /opt/cni/bin
  cniConfDir: /etc/cni/net.d
  ...
metaManager:
  enable: true
  ...
  metaServer:
    enable: true
    server: 127.0.0.1:10550
    ...
```

Obtain the `clusterDNS`  address by querying `ip a` on your edge node, and searching for `weave`.

4. Things to watch out for

Refer to https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#-troubleshooting-blocked-connections

5. Issues that I have met

ISSUE 1: `[kube-peers] Could not get Kubernetes version` in container `weave-net`

RESOLVE: Refer to https://github.com/kubeedge/kubeedge/issues/3935#issuecomment-1236788287

ISSUE 2: Unauthorized error in component `cloudcore

```
[metaserver/applicationCenter]failed to process Application((NodeName=edge-node;Key=/core/v1/nodes/null/null;Verb=list;Status=Rejected;Reason=get current list error: Unauthorized)), get current list error: Unauthorized
```

RESOLVE: https://github.com/kubeedge/kubeedge/pull/3807)](https://github.com/kubeedge/kubeedge/pull/3807
