### ISSUE TITLE
Couldn't execute 'kubectl log' or 'kubectl exec' on edge pods with kubeedge-v1.12.0

### ISSUE THREAD

**Issue by bluven** [kubeedge/kubeedge#4301]
**What happened**:

I want to do `kubectl exec` on a edge pod, but this error happened:
```
[root@suzhou kubeedge]# kubectl exec -ti net-tool-edge1 -- bash
Error from server: error dialing backend: dial tcp 10.22.46.44:10250: connect: connection refused
```

**What you expected to happen**:
`kubectl exec` can work on edge pods.

**How to reproduce it (as minimally and precisely as possible)**:

I installed kubeedge-v1.12.0 as metioned in issue #4297 and open stream feature as metioned on this [guide](https://kubeedge.io/en/docs/setup/keadm/#enable-kubectl-logs-feature). 

I only changed edgecore.yaml on edge nodes and left cloudcore alone since I installed it using helm. 

**Anything else we need to know?**:
Nodes info:
```
[root@suzhou kubeedge]# kubectl get nodes -o wide
NAME     STATUS   ROLES                            AGE     VERSION                    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION           CONTAINER-RUNTIME
edge1    Ready    agent,edge                       126m    v1.22.6-kubeedge-v1.12.0   10.22.46.44   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://18.6.3
edge2    Ready    agent,edge                       118m    v1.22.6-kubeedge-v1.12.0   10.22.46.43   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://18.6.3
node1    Ready    <none>                           5h53m   v1.22.5                    10.22.46.26   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://18.6.3
suzhou   Ready    connector,control-plane,master   5h58m   v1.22.5                    10.22.46.10   <none>        CentOS Linux 7 (Core)   3.10.0-1160.el7.x86_64   docker://18.6.3
```
cloudcore pods info:
```
[root@suzhou kubeedge]# kubectl get po -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP            NODE     NOMINATED NODE   READINESS GATES
cloudcore-57b8db4464-8p4k4   1/1     Running   0          10m   10.22.46.10   suzhou   <none>           <none>
```

The contents under /etc/kubeedge for cloudcore
```
/ # ls /etc/kubeedge/
ca      certs   config
/ # ls -R /etc/kubeedge/*
/etc/kubeedge/ca:
streamCA.crt

/etc/kubeedge/certs:
stream.crt  stream.key

/etc/kubeedge/config:
cloudcore.yaml
```
cloudcore.yaml
```
apiVersion: cloudcore.config.kubeedge.io/v1alpha2
kind: CloudCore
kubeAPIConfig:
  kubeConfig: ""
  master: ""
modules:
  cloudHub:
    advertiseAddress:
    - 10.22.46.10
    dnsNames:
    - 
    nodeLimit: 1000
    tlsCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/edge.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/edge.key
    unixsocket:
      address: unix:///var/lib/kubeedge/kubeedge.sock
      enable: true
    websocket:
      address: 0.0.0.0
      enable: true
      port: 10000
    quic:
      address: 0.0.0.0
      enable: false
      maxIncomingStreams: 10000
      port: 10001
    https:
      address: 0.0.0.0
      enable: true
      port: 10002
  cloudStream:
    enable: true
    streamPort: 10003
    tunnelPort: 10004
  dynamicController:
    enable: false
  router:
    enable: false
  iptablesManager:
    enable: true
    mode: internal
```

The iptables rules of kubeedge on suzhou node:
```
[root@suzhou kubeedge]# iptables -t nat -S | grep TUNNEL
-N TUNNEL-PORT
-A PREROUTING -m comment --comment "kubeedge tunnel port" -j TUNNEL-PORT
-A OUTPUT -m comment --comment "kubeedge tunnel port" -j TUNNEL-PORT
-A TUNNEL-PORT -p tcp -m tcp --dport 10352 -j DNAT --to-destination 10.22.46.10:10003
-A TUNNEL-PORT -p tcp -m tcp --dport 10351 -j DNAT --to-destination 10.22.46.26:10003
```
note: the TUNNEL-PORT has two rules, but  since I have only one cloudcore pod, I don't think this rule below matters
```
-A TUNNEL-PORT -p tcp -m tcp --dport 10351 -j DNAT --to-destination 10.22.46.26:10003
``` 

The edgecore.yaml on edge1 node:
```
[root@edge1 ~]# cat /etc/kubeedge/config/edgecore.yaml 
apiVersion: edgecore.config.kubeedge.io/v1alpha2
database:
  aliasName: default
  dataSource: /var/lib/kubeedge/edgecore.db
  driverName: sqlite3
kind: EdgeCore
modules:
  dbTest:
    enable: false
  deviceTwin:
    enable: true
  edgeHub:
    enable: true
    heartbeat: 15
    httpServer: https://10.22.46.10:10002
    messageBurst: 60
    messageQPS: 30
    projectID: e632aba927ea4ac2b575ec1603d56f10
    quic:
      enable: false
      handshakeTimeout: 30
      readDeadline: 15
      server: 10.22.46.44:10001
      writeDeadline: 15
    rotateCertificates: true
    tlsCaFile: /etc/kubeedge/ca/rootCA.crt
    tlsCertFile: /etc/kubeedge/certs/server.crt
    tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    token: de7b2e97b63c3f26436c3637aa87ab6717ee4c80b1a380a1949fe099ad8f4096.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjU2NDM1MTB9.QeVa8loCY8rIxM8Hdjne9njEisH1XSeWTAS3okW0fuo
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: 10.22.46.10:10000
      writeDeadline: 15
  edgeStream:
    enable: true
    handshakeTimeout: 30
    readDeadline: 15
    server: 10.22.46.10:10004
    tlsTunnelCAFile: /etc/kubeedge/ca/rootCA.crt
    tlsTunnelCertFile: /etc/kubeedge/certs/server.crt
    tlsTunnelPrivateKeyFile: /etc/kubeedge/certs/server.key
    writeDeadline: 15
  edged:
    cniBinDir: /opt/cni/bin
    cniCacheDir: /var/lib/cni/cache
    cniConfDir: /etc/cni/net.d
    containerRuntime: docker
    dockerEndpoint: unix:///var/run/docker.sock
    enable: true
    hostnameOverride: edge1
    imagePullProgressDeadline: 1m0s
    kubeConfig: /etc/kubeedge/config/kubeconfig
    masterServiceNamespace: default
    maxPerPodContainerCount: 1
    minimumGCAge: 0s
    networkPluginName: cni
    networkPluginMTU: 1500
    nonMasqueradeCidr: 10.0.0.0/8
    podSandboxImage: kubeedge/pause:3.1
    registerNode: true
    registerNodeNamespace: default
    registerSchedulable: true
    remoteImageEndpoint: unix:///var/run/dockershim.sock
    remoteRuntimeEndpoint: unix:///var/run/dockershim.sock
    rootDirectory: /var/lib/kubelet
    seccompProfileRoot: /var/lib/kubelet/seccomp
    tailoredKubeletConfig:
      address: 127.0.0.1
      cgroupDriver: systemd
      cgroupsPerQOS: true
      clusterDNS:
      - 10.235.0.10
      clusterDomain: "cluster.local"
      configMapAndSecretChangeDetectionStrategy: Get
      containerLogMaxFiles: 5
      containerLogMaxSize: 10Mi
      contentType: application/json
      cpuCFSQuota: true
      cpuCFSQuotaPeriod: 100ms
      cpuManagerPolicy: none
      cpuManagerReconcilePeriod: 10s
      enableControllerAttachDetach: true
      enableDebugFlagsHandler: true
      enableDebuggingHandlers: true
      enableProfilingHandler: true
      enableServer: false
      enableSystemLogHandler: true
      enforceNodeAllocatable:
      - pods
      eventBurst: 10
      eventRecordQPS: 5
      evictionHard:
        imagefs.available: 15%
        memory.available: 100Mi
        nodefs.available: 10%
        nodefs.inodesFree: 5%
      evictionPressureTransitionPeriod: 5m0s
      failSwapOn: false
      fileCheckFrequency: 20s
      hairpinMode: promiscuous-bridge
      healthzBindAddress: 127.0.0.1
      healthzPort: 10248
      httpCheckFrequency: 20s
      imageGCHighThresholdPercent: 80
      imageGCLowThresholdPercent: 40
      imageMinimumGCAge: 2m0s
      iptablesDropBit: 15
      iptablesMasqueradeBit: 14
      kubeAPIBurst: 10
      kubeAPIQPS: 5
      logging:
        format: text
      makeIPTablesUtilChains: true
      maxOpenFiles: 1000000
      maxPods: 110
      memoryManagerPolicy: None
      memorySwap: {}
      memoryThrottlingFactor: 0.8
      nodeLeaseDurationSeconds: 40
      nodeStatusMaxImages: 50
      nodeStatusReportFrequency: 5m0s
      nodeStatusUpdateFrequency: 10s
      oomScoreAdj: -999
      podPidsLimit: -1
      port: 10250
      readOnlyPort: 10350
      registryBurst: 10
      registryPullQPS: 5
      resolvConf: /etc/resolv.conf
      runtimeRequestTimeout: 2m0s
      seccompDefault: false
      serializeImagePulls: true
      shutdownGracePeriod: 0s
      shutdownGracePeriodCriticalPods: 0s
      streamingConnectionIdleTimeout: 4h0m0s
      syncFrequency: 1m0s
      topologyManagerPolicy: none
      topologyManagerScope: container
      volumePluginDir: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/
      volumeStatsAggPeriod: 1m0s
  eventBus:
    enable: true
    eventBusTLS:
      enable: false
      tlsMqttCAFile: /etc/kubeedge/ca/rootCA.crt
      tlsMqttCertFile: /etc/kubeedge/certs/server.crt
      tlsMqttPrivateKeyFile: /etc/kubeedge/certs/server.key
    mqttMode: 2
    mqttPassword: ""
    mqttPubClientID: ""
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
    mqttSessionQueueSize: 100
    mqttSubClientID: ""
    mqttUsername: ""
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    metaServer:
      enable: false
      server: 127.0.0.1:10550
      tlsCaFile: /etc/kubeedge/ca/rootCA.crt
      tlsCertFile: /etc/kubeedge/certs/server.crt
      tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    remoteQueryTimeout: 60
  serviceBus:
    enable: false
    port: 9060
    server: 127.0.0.1
    timeout: 60
```
The port opened by edgecore on node edge1:
```
[root@edge1 ~]# ss -ltpn | grep edgecore
LISTEN     0      128    127.0.0.1:10350                    *:*                   users:(("edgecore",pid=20973,fd=28))
LISTEN     0      128    127.0.0.1:40501                    *:*                   users:(("edgecore",pid=20973,fd=17))
```

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:32:32Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.12.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
