### ISSUE TITLE
Get empty environment vriable value from `status.podIP` if `hostNetwork` enabled in edge.

### ISSUE THREAD

**Issue by xavierlineX** [kubeedge/kubeedge#4321]
**What happened**:
  Got an empty environment variable that from `status.podIP` if `hostNetwork` enabled.

**What you expected to happen**:
  Get the value of `status.podIP`(should be the IP address of the host like Kubernetes do)

**How to reproduce it (as minimally and precisely as possible)**:
    1. Duplicate `nginx_edge_demo.yaml`, remove `spec.template.spec.hostNetwork` in copy and apply edited. Then attach the pod and check the environment(`kubectl exec $PODNAME -- /bin/sh -c 'env'` ).
    2. Apply the unmodified one(and remove pods if necessary), attach and check the environment.

**Anything else we need to know?**:
Demo profile(nginx_edge_demo.yaml): 
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-edge
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        env:
        - name: IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: STATIC_DEMO_IP
          value: 1.1.1.1
        image: nginx:1.15.12
        ports:
        - containerPort: 80
          hostPort: 80
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: Exists
```

**Environment**:
- Kubernetes version (use `kubectl version`):
   ``` txt
   Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:16Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:48Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
   ```

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
  ``` shell
  cloud$ kubectl -n kubeedge exec $CLOUDCORE_POD_NAME -- cloudcore --version
  KubeEdge v1.11.2
  ---
  edge$ edgecore --version
  KubeEdge v1.11.2
  ```

<!-- 
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
--!>
