### ISSUE TITLE
the x86-image is not suiteable for non-X86 architecture

### ISSUE THREAD

**Issue by googlebabaio** [kubeedge/kubeedge#438]
## **Which jobs are failing**:
When deploy an app(such as nginx) on the accessed edge node (the device is raspberry pie) for POC testing, deployment is unsuccessful.

env:
k8s:1.11.3
edgecontroller 0.2, run with binary.
edgenode 0.2 , run with binary.
#### the node status:
```
# kubectl get node
NAME                 STATUS     ROLES     AGE       VERSION
edge-node-01         NotReady   <none>    8d        2.0.0
k8s-node-01          Ready      <none>    203d      v1.11.3
k8s-node-02          Ready      <none>    203d      v1.11.3
k8s-node-03          Ready      <none>    203d      v1.11.3
x86-edge-node-01     Ready      <none>    9d        2.0.0
```

#### poc-deploy.yaml:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-smp2
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
	  hostNetwork: true
      containers:
      - name: nginx-smp2
        image: nginx:1.15.12
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          hostPort: 80
      nodeSelector:
        node: edge-node-01
      imagePullSecrets:
      - name: harborsecret
```

#### show pod's status :
```
# kubectl get pod -n kubeedge 
NAME                          READY     STATUS              RESTARTS   AGE
nginx-smp2-5f74dc88c6-smqfd   0/1       ContainerCreating   0          5m
```

#### show pod's logs:
```
# kubectl logs nginx-smp2-5f74dc88c6-smqfd
Error from server: Get https://localhost:10250/containerLogs/default/nginx-smp2-5f74dc88c6-smqfd/nginx-smp2: dial tcp 127.0.0.1:10250: connect: connection ref
```

## **Which test(s) are failing**:
- If the edge node's cpu architectures is x86 ,deploying `poc-deploy.yaml'on the edge node can succeed.
- When the edge nodes using Raspberry Pi, the deployment fails.

#### The error message displayed at the `k8s` level is:
```
# kubectl logs nginx-smp2-5f74dc88c6-smqfd
Error from server: Get https://localhost:10250/containerLogs/default/nginx-smp2-5f74dc88c6-smqfd/nginx-smp2: dial tcp 127.0.0.1:10250: connect: connection ref
```

#### The errors displayed at the `docker` level is:
```
# docker logs 6b8d3644b154
standard_init_linux.go:207: exec user process caused "exec format error"
```

## **Since when has it been failing**:
not using kubeedge environment, run directly with docker, and discover

#### Raspberry pie type edge node(armv7)
```
# docker run -it nginx /bin/bash
standard_init_linux.go:207: exec user process caused "exec format error"
```

#### X86 Type Edge Node
```
# docker run -it arm32v7/nginx /bin/bash
root@52ef7489d5e0:/# 
```

**Guess, it's the reason for the image, so I went to find an ARM-based image to test, and sure enough!!!**

```
# docker run -it arm32v7/nginx /bin/bash
Unable to find image 'arm32v7/nginx' locally
arm32v7: Pulling from library/nginx
fac132c5d16f: Pull complete 
6aa30864eb85: Pull complete 
1b71bada70c3: Pull complete 
Digest: sha256:a054737199a0c9c47b3217c6e2993c469568fb10ffe8195e2e2544e1e17086e6
Status: Downloaded newer image for  arm32v7/nginx
root@10ef4979d5e0:/# 
```

## **Reason for failure**:
Because kubeedge is an important link between edge and cloud, it is inevitable to encounter many non-X86 architectures of servers(such as Raspberry Pi). 
We deployed image(base on x86) on the edge node(armv7 or other non-X86 architecture), and the edge node did not support the image, so the deployment failed.
At this time, we should use a dedicated image for special CPU architectures(such as armv7/armv8).

## **Anything else we need to know**:

- We can find some images using armv7 architecture at this address.
> https://hub.docker.com/u/arm32v7

- When we meet a problem, we should start at the bottom of things.

- Also, it's important to note that when deploying workload, remember to use`hostNetwork=true`
