### ISSUE TITLE
Node Group Management example fails with parse exception

### ISSUE THREAD

**Issue by smoms** [kubeedge/kubeedge#4450]
I am trying the Node Group Management example as explained [here](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/node-group-management.md).
I have created the NodeGroup resource:

`apiVersion: apps.kubeedge.io/v1alpha1
kind: NodeGroup
metadata:
  name: hangzhou
spec:
  matchLabels:
    location: hangzhou
---
apiVersion: apps.kubeedge.io/v1alpha1
kind: NodeGroup
metadata:
  name: beijing 
spec:
  matchLabels:
    location: beijing`

However I get an error like **error: error parsing ./EdgeApplication_1.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key**, as it seems that the given EdgeApplication yaml is not valid:

`apiVersion: apps.kubeedge.io/v1alpha1
kind: EdgeApplication
metadata:
  name: nginx-app 
spec:
  workloadTemplate:
    manifests:
    - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx
    spec:
      selector:
        matchLabels:
          app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
          - name: nginx
            image: nginx:latest
          ports:
          - containerPort: 80
    - apiVersion: v1
    kind: Service
    metadata:
      name: nginx-service
    spec:
      selector:
        app: nginx
      ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 8080
      type: LoadBalancer
  workloadScopes:
    targetNodeGroups:
      - name: hangzhou
        overriders:
          replicas: 2
          imageOverrider:
            - component: "registry"
              operator: "replace"
              value: "hangzhou.registry.io"
      - name: beijing
        overriders:
          replicas: 3
          imageOverrider:
            - component: "registry"
              operator: "replace"
              value: "beijing.registry.io"`

What is wrong?
thanks

**Comment by wackxu** [comment]
I do not see the yaml file separator ```---``` in your paste? have you delete it ?

**Comment by smoms** [comment]
As mentioned I copied the yaml from the kubeedge GitHub page. Please check that with a Yaml Lint.
However I got the right one, which I paste here:

```
apiVersion: apps.kubeedge.io/v1alpha1
kind: EdgeApplication
metadata:
  name: nginx-app 
spec:
  workloadTemplate:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx
      spec:
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:latest
            ports:
            - containerPort: 80
    - apiVersion: v1
      kind: Service
      metadata:
        name: nginx-service
      spec:
        selector:
          app: nginx
        ports:
        - name: http
          protocol: TCP
          port: 80
          targetPort: 8080
        type: LoadBalancer
  workloadScopes:
    targetNodeGroups:
      - name: hangzhou
        overriders:
          replicas: 2
          imageOverriders:
            - component: "registry"
              operator: "replace"
              value: "hangzhou.registry.io"
      - name: beijing
        overriders:
          replicas: 3
          imageOverriders:
            - component: "registry"
              operator: "replace"
              value: "beijing.registry.io"
```
