### ISSUE TITLE
 Implement metaserver compatibility with kubectl

### ISSUE THREAD

**Issue by vincentgoat** [kubeedge/kubeedge#4531]
**What would you like to be added/modified**:
Enable MetaServer and then implement MetaServer compatibility with kubectl for friendly use.
- Enable MetaServer for EdgeCore.
```
kind: EdgeCore
modules:
  EdgeHub
    enable: true
  MetaManager:
    enable: true
    metaServer:
      enable: true
  ...
```

- As of CloudCore, should enable dynamicController
```
kind: CloudCore
modules:
  cloudHub:
    enable: true
  dynamicController:
    enable: true
  ...
```
**Why is this needed**:
 Implement MetaServer compatibility with kubectl for friendly use.
