### ISSUE TITLE
EdgeCore CSI dirver not working - EdgeNode does not report number of driver volumes supported.

### ISSUE THREAD

**Issue by linuxcrash** [kubeedge/kubeedge#4565]
**What happened**:
When using the NFS or SMB CSI drivers to create persistent volumes for the edge, EdgeCore cannot mount the volumes.

I'm trying to run a pod on an EdgeWorker node running EdgeCore that is using a CSI-SMB volume mounted to it from the local LAN on the EdgeCore node. It seems that EdgeCore has a problem with the CSI-SMB daemonset pods when trying to load the driver plugin:

```bash
Dec 28 17:11:24 ed-worker-1 edgecore[748]: I1228 17:11:24.311062     748 csi_plugin.go:99] kubernetes.io/csi: Trying to validate a new CSI Driver with name: smb.csi.k8s.io endpoint: /var/lib/kubelet/plugins/smb.csi.k8s.io/csi.sock versions: 1.0.0
Dec 28 17:11:24 ed-worker-1 edgecore[748]: I1228 17:11:24.311668     748 csi_plugin.go:112] kubernetes.io/csi: Register new plugin with name: smb.csi.k8s.io at endpoint: /var/lib/kubelet/plugins/smb.csi.k8s.io/csi.sock
Dec 28 17:11:24 ed-worker-1 edgecore[748]: E1228 17:11:24.360934     748 nodeinfomanager.go:566] Invalid attach limit value 0 cannot be added to CSINode object for "smb.csi.k8s.io"
```

I have the very same error message using the CSI-NFS driver. It seems that EdgeCore tries to initalize the CSI driver and by doing so it uses nodeinfomanager to figure how many such CSI volumes are allowed to be used on the node but failes because 0 is returned and therefore no such volume will be able to be used on the node.
I'm currently not sure if this a bug in EdgeCore that returns wrong data to the CSI interface or if the CSI interface cannot get the necessary data from EdgeCore.

Relevant log line from EdgeCore systemd service:
```bash
nodeinfomanager.go:566] Invalid attach limit value 0 cannot be added to CSINode object for "[nfs.csi.k8s.io](http://nfs.csi.k8s.io/)"
```
If I run the very same pod on a cloud worker node (aka native K8s) it works just fine and the volume is mounted and available to the pod.

**What you expected to happen**:
The CSI volumes get mounted and attached into the pod requesting the PV.

**How to reproduce it (as minimally and precisely as possible)**:

- Install CSI SMB or NFS driver on the K8s cluster.
- Create a storage class for the CSI driver
- Create a PVC referring the storage class
- Create a Pod that uses the PVC and mount it in the pod.

**Anything else we need to know?**:
According to your documenation CSI drivers are supported by default.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24 (K3s)
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.13.0
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`): 4 cores, 4GB memory
  - OS (e.g. `cat /etc/os-release`): Ubuntu 22.04 LTS
  - Kernel (e.g. `uname -a`): Linux ed-worker-1 5.15.0-58-generic
  - Go version (e.g. `go version`): NA
  - Others:

  </details>

**Comment by vincentgoat** [comment]
Thank you for your info @linuxcrash 
Please check more info by executing `kubectl get csinode` and `kubectl describe csinode {your edgenode csinode}`

**Comment by linuxcrash** [comment]
@vincentgoat below are the output of the commands:

## kubectl get csinode
```bash
kubectl get csinode -o wide
NAME          DRIVERS   AGE
cl-worker-1   2         41d
cl-master-1   2         41d
```
## kubectl describe csinode
```bash
kubectl describe csinode
Name:               cl-worker-1
Labels:             <none>
Annotations:        storage.alpha.kubernetes.io/migrated-plugins:
                      kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd
CreationTimestamp:  Tue, 20 Dec 2022 10:41:38 +0000
Spec:
  Drivers:
    smb.csi.k8s.io:
      Node ID:  cl-worker-1
    nfs.csi.k8s.io:
      Node ID:  cl-worker-1
Events:         <none>


Name:               cl-master-1
Labels:             <none>
Annotations:        storage.alpha.kubernetes.io/migrated-plugins:
                      kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd
CreationTimestamp:  Tue, 20 Dec 2022 10:41:01 +0000
Spec:
  Drivers:
    smb.csi.k8s.io:
      Node ID:  cl-master-1
    nfs.csi.k8s.io:
      Node ID:  cl-master-1
Events:         <none>
```

## kubectl get nodes
```bash
kubectl get nodes 
NAME            STATUS   ROLES                  AGE   VERSION
cl-master-1     Ready    control-plane,master   41d   v1.24.7+k3s1
edge-worker-1   Ready    agent,edge             33d   v1.23.15-kubeedge-v1.13.0
cl-worker-1     Ready    <none>                 41d   v1.24.7+k3s1
```

## kubectl get csinode edge-worker-1
```bash
kubectl get csinode edge-worker-1
Error from server (NotFound): csinodes.storage.k8s.io "edge-worker-1" not found
```

Please note that my egde-worker node is not showing for the csinode commands...

**Comment by linuxcrash** [comment]
@vincentgoat,
here are the requested EdgeCore logs from the very beginning. I have compressed them using gzip as it was about 150MB.

Let me know if I can provide you with anything else.

[edgecore.log.gz](https://github.com/kubeedge/kubeedge/files/10539421/edgecore.log.gz)

**Comment by vincentgoat** [comment]
Thanks.
I reproduced it in my cluster and will update it here if there is any progress.

**Comment by vincentgoat** [comment]
I found that StorageV1Client didn't implement the function CSINodes() in kubeedge. This may be the root cause of this issue.
I will try to implement it and check if it will work fine.

**Comment by vincentgoat** [comment]
In addition, can you check the csi-driver container logs if the error happened?

**Comment by vincentgoat** [comment]
Hi, @linuxcrash 
Hostpath csi-driver is now working in my cluster with this fix https://github.com/kubeedge/kubeedge/pull/4579.
Please try this fix and deploy build/csisamples/deploy/csicontroller.yaml to check if nfs driver will work.

**Comment by linuxcrash** [comment]
@vincentgoat ,
Could you guide me a bit how I can test the fix and I also can't find the mentioned YAML file above.

**Comment by vincentgoat** [comment]
Correct the yaml path: kubeedge/build/csisamples/hostpath/deploy/csicontroller.yaml

**Step 1:** Build docker image kubeedge/csidriver:v1.4.0
Run command in the root dir of kubeedge repo `docker build -t kubeedge/csidriver:v1.4.0 -f build/csidriver/Dockerfile .`

**Step 2:** Replace `kubeedge/csidriver:v1.3.0` by the new image `kubeedge/csidriver:v1.4.0` in the file csicontroller.yaml

**Step 3:** Deploy the csicontroller.yaml

**Step 4:** Deploy the csi-driver on the edge node

**Comment by linuxcrash** [comment]
@vincentgoat 
I cannot build the docker image since I seem to not have the neccessary parts for GO setup to build it:

```bash

capitano@ed-worker-2:~/kubeedge$ sudo docker build -t 'kubeedge/csidriver:v1.4.0' build/csidriver/
Sending build context to Docker daemon  2.048kB
Step 1/7 : FROM golang:1.17.13-alpine3.16 AS builder
 ---> 270c4f58750f
Step 2/7 : ARG GO_LDFLAGS
 ---> Using cache
 ---> 16d4db5aa56c
Step 3/7 : COPY . /go/src/github.com/kubeedge/kubeedge
 ---> Using cache
 ---> 429bcacb9804
Step 4/7 : RUN CGO_ENABLED=0 GO111MODULE=off go build -v -o /usr/local/bin/csidriver -ldflags="${GO_LDFLAGS} -w -s" github.com/kubeedge/kubeedge/cloud/cmd/csidriver
 ---> Running in 5b35c4b1c34a
cannot find package "github.com/kubeedge/kubeedge/cloud/cmd/csidriver" in any of:
	/usr/local/go/src/github.com/kubeedge/kubeedge/cloud/cmd/csidriver (from $GOROOT)
	/go/src/github.com/kubeedge/kubeedge/cloud/cmd/csidriver (from $GOPATH)
The command '/bin/sh -c CGO_ENABLED=0 GO111MODULE=off go build -v -o /usr/local/bin/csidriver -ldflags="${GO_LDFLAGS} -w -s" github.com/kubeedge/kubeedge/cloud/cmd/csidriver' returned a non-zero code

```

How can I fix that properly. Sorry I'm not familiar with setting up GO at all.

**Comment by gy95** [comment]
you can just run `make image WHAT=csidriver` to build csidriver image

**Comment by linuxcrash** [comment]
@vincentgoat  / @gy95,
It seems I can't get the csi-hostpath-controller pod to run. Somehow it always ends up in CrashLoopBackOff

```bash
kubectl get all -n kubeedge
NAME                             READY   STATUS             RESTARTS       AGE
pod/cloudcore-5dc4f4c68c-8cmxv   1/1     Running            0              28d
pod/csi-hostpath-edge-j9bqt      2/2     Running            0              27s
pod/csi-hostpath-controller-0    0/3     CrashLoopBackOff   15 (15s ago)   3m14s

NAME                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                                             AGE
service/cloudcore   ClusterIP   10.43.69.127   <none>        10000/TCP,10001/TCP,10002/TCP,10003/TCP,10004/TCP   52d

NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
daemonset.apps/csi-hostpath-edge   1         1         1       1            1           node-role.kubernetes.io/edge=   27s

NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cloudcore   1/1     1            1           28d

NAME                                   DESIRED   CURRENT   READY   AGE
replicaset.apps/cloudcore-5dc4f4c68c   1         1         1       28d

NAME                                       READY   AGE
statefulset.apps/csi-hostpath-controller   0/1     3m14s
```
I changed the container image version number in the csicontroller.yaml to the one I have created and updated the KUBE_NODE_NAME to my KE edge node (ed-worker-1).

```yaml
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-controller
  namespace: kubeedge
spec:
  serviceName: "csi-hostpath-controller"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-controller
  template:
    metadata:
      labels:
        app: csi-hostpath-controller
    spec:
      serviceAccountName: csi-controller
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.2.1
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --connection-timeout=15s
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: csi-socket-dir
        - name: csi-driver
          image: kubeedge/csidriver:v1.4.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--drivername=$(CSI_DRIVERNAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--kubeedge-endpoint=$(KUBEEDGE_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_DRIVERNAME
              value: csi-hostpath
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBEEDGE_ENDPOINT
              value: unix:///kubeedge/kubeedge.sock
            - name: KUBE_NODE_NAME
              # replace this value with the name of edge node
              # which is in charge of Create Volume and Delete Volume,
              # Controller Publish Volume and Controller Unpublish Volume.
              value: ed-worker-1
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
            - mountPath: /kubeedge
              name: kubeedge-socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: csi-socket-dir
        - hostPath:
            path: /var/lib/kubeedge
            type: DirectoryOrCreate
          name: kubeedge-socket-dir       
```

## Edge Logfile
[edgecore.log](https://github.com/kubeedge/kubeedge/files/10776533/edgecore.log)

## Questions
I think I'm also missing an understanding how this csicontroller works. 
* Do you have documentation about it?
* Is it supposed to run the csicontroller on the KE Edge worker node?

**Comment by vincentgoat** [comment]
Hi, @linuxcrash 
FYI: https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md

**Comment by vincentgoat** [comment]
> **Step 4:** Deploy the csi-driver on the edge node
csi-driver here means the third-party plugin deployed on the edge node, which is different from kubeedge/csidriver, while kubeedge/csidriver is deployed on the cloud side.

**Comment by linuxcrash** [comment]
Hi @vincentgoat  @gy95 ,
I have followed the configuration and got the controller running on the cloud worker node but eventhough K8s reports the there is a csi-hostpath pod running on the edge worker, I cannot see it on the edge. Edgecore log contains some errors trying to start it.

![image](https://user-images.githubusercontent.com/5081159/221362280-b7df37c4-de50-4f07-acb1-3694ee249f5a.png)

## Edgecore Log
[edgecore.log](https://github.com/kubeedge/kubeedge/files/10831372/edgecore.log)

## CSI Controller YAML
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller
  namespace: kubeedge

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-controller-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-role
subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kubeedge
roleRef:
  kind: ClusterRole
  name: external-controller-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kubeedge
  name: external-controller-cfg
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-role-cfg
  namespace: kubeedge
subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kubeedge
roleRef:
  kind: Role
  name: external-controller-cfg
  apiGroup: rbac.authorization.k8s.io

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-controller
  namespace: kubeedge
spec:
  serviceName: "csi-hostpath-controller"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-controller
  template:
    metadata:
      labels:
        app: csi-hostpath-controller
    spec:
      serviceAccountName: csi-controller
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.2.1
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --connection-timeout=15s
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v1.1.1
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: csi-socket-dir
        - name: csi-driver
          image: kubeedge/csidriver:v1.4.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--drivername=$(CSI_DRIVERNAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--kubeedge-endpoint=$(KUBEEDGE_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_DRIVERNAME
              value: csi-hostpath
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBEEDGE_ENDPOINT
              value: unix:///kubeedge/kubeedge.sock
            - name: KUBE_NODE_NAME
              # replace this value with the name of edge node
              # which is in charge of Create Volume and Delete Volume,
              # Controller Publish Volume and Controller Unpublish Volume.
              value: edge-worker-1
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
            - mountPath: /kubeedge
              name: kubeedge-socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: csi-socket-dir
        - hostPath:
            path: /var/lib/kubeedge
            type: DirectoryOrCreate
          name: kubeedge-socket-dir
```

## CSI Node YAML
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-edge
  namespace: kubeedge
spec:
  selector:
    matchLabels:
      app: csi-hostpath-edge
  template:
    metadata:
      labels:
        app: csi-hostpath-edge
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-hostpath /registration/csi-hostpath-reg.sock"]
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/edged/plugins/csi-hostpath/csi.sock
          securityContext:
            privileged: true
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name:  csi-hostpath-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/k8scsi/hostpathplugin:v1.1.0
          imagePullPolicy: IfNotPresent
          args:
            - "--drivername=csi-hostpath"
            - "--v=5"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--endpoint=unix:///csi/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: plugins-dir
              mountPath: /var/lib/edged/plugins
              mountPropagation: Bidirectional
            - name: mountpoint-dir
              mountPath: /var/lib/edged/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/edged/plugins/csi-hostpath
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/edged/plugins_registry
            type: DirectoryOrCreate
        - name: plugins-dir
          hostPath:
            path: /var/lib/edged/plugins
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/edged/pods
            type: DirectoryOrCreate
```
