### ISSUE TITLE
KubeEdge IoT device not working

### ISSUE THREAD

**Issue by smoms** [kubeedge/kubeedge#4602]
Hi,

we are trying to create an IoT device using the OPCUA simulator provided by the sample projects.
We run the [opcua simulator](https://github.com/kubeedge/mappers-go/blob/2ed8bcba38/tests/devices-simulator/opcua/device/server.py) as a Docker container.

We have created the following Device CR:

```
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: simulator
spec:
  data:
    dataProperties:
      - propertyName: temperature
  deviceModelRef:
    name: opcua-model
  protocol:
    opcua:
      url: opc.tcp://192.168.1.84:4840,
      userName: testuser,
      password: /ca/pass,
      securityPolicy: Basic256Sha256,
      securityMode: Sign,
      certificate: /ca/clientcert.pem,
      privateKey: /ca/clientkey.pem
        #common:
        #customizedValues:
        #remoteCertificate: /ca/servercert.pem
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
      - key: region
        operator: In
        values:
        - edge-loc-1
  propertyVisitors:
    - propertyName: temperature
      collectCycle: 10
      opcua:
        nodeID: ns=2;i=3
      reportCycle: 10
```
and the following Device_Model CR:

```
apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  name: opcua-model
spec:
  protocol: "opcua"
  properties:
  - name: temperature
    description: temperature in degree celsius
    type:
      int:
        accessMode: ReadOnly
        maximum: 100
        unit: Degree Celsius
```
Once applied they generate this configMap:

```
apiVersion: v1
data:
  deviceProfile.json: '{"deviceInstances":[{"id":"simulator","name":"simulator","protocol":"opcua-simulator","model":"opcua-model","data":{"dataProperties":[{"propertyName":"temperature"}]},"propertyVisitors":[{"name":"temperature","propertyName":"temperature","modelName":"opcua-model","protocol":"opcua","reportCycle":10,"collectCycle":10,"visitorConfig":{"nodeID":"ns=2;i=3"}}]}],"deviceModels":[{"name":"opcua-model","properties":[{"name":"temperature","dataType":"int","description":"temperature
    in degree celsius","accessMode":"ReadOnly","defaultValue":0,"minimum":0,"maximum":100,"unit":"Degree
    Celsius"}]}],"protocols":[{"name":"opcua-simulator","protocol":"opcua","protocolConfig":{"url":"opc.tcp://192.168.1.84:4840,","userName":"testuser,","password":"/ca/pass,","securityPolicy":"Basic256Sha256,","securityMode":"Sign,","certificate":"/ca/clientcert.pem,","privateKey":"/ca/clientkey.pem"},"protocolCommonConfig":null}]}'
kind: ConfigMap
metadata:
  creationTimestamp: "2023-02-19T14:49:11Z"
  name: device-profile-config-edge-loc-1
  namespace: default
  resourceVersion: "6462766"
  uid: e2346bd7-8525-407e-b7e2-071e3c21bbd6
```

Finally I start the mapper as a deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opcua-mapper
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opcuamapper
  template:
    metadata:
      labels:
        app: opcuamapper
    spec:
      hostNetwork: true
      containers:
      - name: opcua-mapper-container
        image: opcua-mapper:v1.0-linux-amd64
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: config-volume
          mountPath: /opt/kubeedge/
        - name: certificates
          mountPath: /ca
      nodeSelector:
        topology.kubernetes.io/region: "edge-loc-1"
      volumes:
      - name: config-volume
        configMap:
          name: device-profile-config-edge-loc-1
      - name: certificates
        hostPath:
          path: /etc/kubeedge/ca/testca
          type: Directory
      restartPolicy: Always
```

However the mapper crashes without any meaningful logs:

`default          opcua-mapper-5bcdf778d5-7fdv6             0/1     CrashLoopBackOff   7 (2m51s ago)   13m`

and no messages transit on the mqtt server.
Also we tried to run on the edge node:

```
sqlite3 /var/lib/kubeedge/edgecore.db 
select * from meta where "type"='device';
```
but it returns empty results.

**What you expected to happen**:

I expect to have device created on the edge node and end-2-end connectivity with opcua device simulator. None of these instead happen.
At the end I expect to have a working opcua device simulator visible in the K8s control-plane. I.e. I can read and write the opcua values from/to the device from the K8s control-plane. 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps described above.

**Environment**:
- Kubernetes version (use `kubectl version`):
```
- Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.7+k3s1", GitCommit:"7af5b16788afe9ce1718d7b75b35eafac7454705", GitTreeState:"clean", BuildDate:"2022-10-25T19:31:34Z", GoVersion:"go1.18.7", Compiler:"gc", Platform:"linux/amd64"}
```

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
`Version: v1.13.0`
- <details><summary>Cloud nodes Environment:</summary>
1 node for cloudcode, 1 node for edgecore, 1 node for device simulator
  - Hardware configuration (e.g. `lscpu`): 
```
  Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         43 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
```
  - OS (e.g. `cat /etc/os-release`):
`  Ubuntu 22.04.1 LTS`
  - Kernel (e.g. `uname -a`):
  `Linux ed-worker-1 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
