### ISSUE TITLE
cloud create device but edge not create device

### ISSUE THREAD

**Issue by hou718945431** [kubeedge/kubeedge#4709]
**What happened and what you expected to happen**:
What happened
cloud create device but edge not create device

i expected to happen
cloud create device notice edge create device

**How to reproduce it (as minimally and precisely as possible)**:
tail -f /var/log/kubeedge/cloudcore.log
W0329 16:37:49.761841   27762 objectsync.go:95] failed to set metatype :no kind is registered for the type v1alpha2.Device in scheme "k8s.io/client-go/kubernetes/scheme/register.go:74"

and edgecore no error

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (1.23.0):
- KubeEdge version(1.13.0):

**Comment by hou718945431** [comment]
hello @RyanZhaoXB  i use commands  then get  this response
devicemodels                                   devices.kubeedge.io/v1alpha2           true         DeviceModel
devices                                        devices.kubeedge.io/v1alpha2           true         Device

**Comment by hou718945431** [comment]
I create devicemodes.yml  is this 

```
apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
 name: speaker-model
 namespace: default
spec:
 properties:
  - name: track           # 属性名称
    description: music track to play  # 描述
    type:
     string:     # 值类型
      accessMode: ReadWrite   #可读写
      defaultValue: ''      # 默认值
```

device.yml 

```
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: speaker-01
  labels:
    description: 'Speaker'
    manufacturer: 'test'
spec:
  deviceModelRef:
    name: speaker-model    # 关联的device model
  nodeSelector:     # 节点选择（这里是节点的标签）
    nodeSelectorTerms:
    - matchExpressions:
      - key: 'kubernetes.io/hostname'
        operator: In
        values:
        - aaa
```
