### ISSUE TITLE
CSI does not work in kubeedge 1.12.1, CSINode is never created in edge nodes

### ISSUE THREAD

**Issue by MikeRiz521** [kubeedge/kubeedge#4761]
**What happened**:
We have an Azure k8s cluster on the cloud and we have connected a few edge nodes using Kubeedge version 1.12.1. While attempting to follow the [csi proposal](https://github.com/kubeedge/kubeedge/blob/master/docs/proposals/csi.md) I noticed that the csi nodes on the edge are never created. There does not seem to be any obvious error in the logs of the `csi-controller` or the `csi-hostpath-driver`. Am I supposed to create the `kind:CSINode` manually, or should the `csinode.yaml` file create them for me? 

While researching I stumbled upon issue #4565 however I did not pick up any errors in the `edgecore` logs or any `panic` errors in the logs of any component. In fact when I tried to create the `volume` in the proposal, it never seemed to have been picked up by the `csi-controller` even if the volume was created. Furthermore, issue #3471 suggests CSINode might need to be created manually in edge nodes, as well as setting some node labels, however this is not mentioned anywhere in the original proposal, so if anything needs to be created manually by me, I would appreciate an update.

The only error I get is when the pod in the static provisioning example of the proposal tries to bind with the persistent volume through the claim, but instead I get:
```failed to provision volume with StorageClass "default": error generating accessibility requirements: error getting CSINode for selected node "edge-controller": csinode.storage.k8s.io "edge-controller" not found```. 

In the original proposal it is also mentioned that "There is an Edge Node which is in charge of Create Volume and Delete Volume, Controller Publish Volume and Controller Unpublish Volume. The name of this Edge Node needs to be manually specified in the parameters of CSI Driver from KubeEdge" (in our case this node is `edge-controller`). Does this edge node need any specific configuration, or is this configured by the components in `csinode.yaml`. Overall the entire proposal seems a bit complex and like it is missing some steps, so any further information will be appreciated.

Finally I've continuously seen this old PR #2133 being mentioned in issues where other users also had problems running the `csi-hostpath` exmaple, will this PR perhaps fix my issue? And if yes, how can I get the changes on the `cloudcore` side to the container we are running on the Azure cluster?

My colleagues and I would greatly appreciate having working PVs on the edge since it will unlock a great potential for our projects, while we are now bounded by using only `hostPath` volumes. We are willing to apply any old PR fixes or code changes from unmerged code paths, anything to get this over the line and working.

**What you expected to happen**:I am able to at least run the static provisioning example in the proposal

**How to reproduce it (as minimally and precisely as possible)**: Follow the csi orginal proposal while updating some image versions of the third-party components in `csicontroller.yaml` and `csinode.yaml`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.7 on Azure, 1.21.1 on Kubeedge
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.12.1

Attaching also the `csicontroller.yaml` and `csinode.yaml` to clarify the setup

`csicontroller.yaml`:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-controller
  namespace: kubeedge

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: external-controller-runner
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots"]
    verbs: ["get", "list"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshotcontents"]
    verbs: ["get", "list"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-role
subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kubeedge
roleRef:
  kind: ClusterRole
  name: external-controller-runner
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kubeedge
  name: external-controller-cfg
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-controller-role-cfg
  namespace: kubeedge
subjects:
  - kind: ServiceAccount
    name: csi-controller
    namespace: kubeedge
roleRef:
  kind: Role
  name: external-controller-cfg
  apiGroup: rbac.authorization.k8s.io

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-controller
  namespace: kubeedge
spec:
  serviceName: "csi-hostpath-controller"
  replicas: 1
  selector:
    matchLabels:
      app: csi-hostpath-controller
  template:
    metadata:
      labels:
        app: csi-hostpath-controller
    spec:
      serviceAccountName: csi-controller
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v2.1.2
          imagePullPolicy: IfNotPresent
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v3.0.0
          imagePullPolicy: IfNotPresent
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
          volumeMounts:
          - mountPath: /csi
            name: csi-socket-dir
        - name: csi-driver
          image: kubeedge/csidriver:v1.12.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--drivername=$(CSI_DRIVERNAME)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--kubeedge-endpoint=$(KUBEEDGE_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_DRIVERNAME
              value: csi-hostpath
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBEEDGE_ENDPOINT
              value: unix:///kubeedge/kubeedge.sock
            - name: KUBE_NODE_NAME
              # replace this value with the name of edge node
              # which is in charge of Create Volume and Delete Volume,
              # Controller Publish Volume and Controller Unpublish Volume.
              value: edge-controller
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: csi-socket-dir
            - mountPath: /kubeedge
              name: kubeedge-socket-dir
      nodeSelector:
        kubernetes.io/hostname: <cloudcore node>
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-hostpath
            type: DirectoryOrCreate
          name: csi-socket-dir
        - hostPath:
            path: /var/lib/kubeedge
            type: DirectoryOrCreate
          name: kubeedge-socket-dir
```
`csinode.yaml`:

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-hostpath-edge
  namespace: kubeedge
spec:
  selector:
    matchLabels:
      app: csi-hostpath-edge
  template:
    metadata:
      labels:
        app: csi-hostpath-edge
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      containers:
        - name: node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v2.1.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/csi-hostpath /registration/csi-hostpath-reg.sock"]
          args:
            - --v=5
            - --csi-address=/csi/csi.sock
            - --kubelet-registration-path=/var/lib/edged/plugins/csi-hostpath/csi.sock
          securityContext:
            privileged: true
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        - name:  csi-hostpath-driver
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: quay.io/k8scsi/hostpathplugin:v1.6.0
          imagePullPolicy: IfNotPresent
          args:
            - "--drivername=csi-hostpath"
            - "--v=5"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--endpoint=unix:///csi/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: plugins-dir
              mountPath: /var/lib/edged/plugins
              mountPropagation: Bidirectional
            - name: mountpoint-dir
              mountPath: /var/lib/edged/pods
              mountPropagation: "Bidirectional"
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/edged/plugins/csi-hostpath
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/edged/plugins_registry
            type: DirectoryOrCreate
        - name: plugins-dir
          hostPath:
            path: /var/lib/edged/plugins
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/edged/pods
            type: DirectoryOrCreate
```
