### ISSUE TITLE
when i use router, for mode "rest -> servicebus", always  timeout

### ISSUE THREAD

**Issue by zhijianfree** [kubeedge/kubeedge#4987]
**What happened**:
i have created rest、servicebus、rule，and then i send message to the node , but always timeout.

# Cloud
rest.yaml
```
apiVersion: rules.kubeedge.io/v1
kind: RuleEndpoint
metadata:
  name: my-rest
  labels:
    description: test
spec:
  ruleEndpointType: "rest"
  properties: {}
```

servicebus.yaml
```
apiVersion: rules.kubeedge.io/v1
kind: RuleEndpoint
metadata:
  name: my-servicebus
  labels:
    description: test
spec:
  ruleEndpointType: "servicebus"
  properties: { "service_port": "9000" }
```

rule.yaml
```
apiVersion: rules.kubeedge.io/v1
kind: Rule
metadata:
  name: my-rule-rest-servicebus
  labels:
    description: test
spec:
  source: "my-rest"
  sourceResource: { "path": "/cloud/cmd" }
  target: "my-servicebus"
  targetResource: { "path": "/v1.0/daemon/cloud/cmd" }
```
then i execute cmd int the cloudcore node.
```
curl -H "Content-type: application/json" -X POST -d '{"msg":"cloud send"}' http://127.0.0.1:9443/edge-node-20230726-e3f3da/default/cloud/cmd
```
response:
```
wait to get response time out
```
# Edge
custom app is listening port 9000:
```
[root@kubeedge-master servicebus]# k get pod -o wide | grep edgedaemon
edgedaemon-54c678d446-fvgvw          1/1     Running   0             25h    172.17.0.5       edge-node-20230726-e3f3da               <none>           <none>
[root@kubeedge-master servicebus]# kubectl get pod edgedaemon-54c678d446-fvgvw -o jsonpath='{.spec.containers[0].ports}'
[{"containerPort":9000,"hostPort":9000,"protocol":"TCP"}][root@kubeedge-master-1 servicebus]# 
```

my java app in the edgenode **edge-node-20230726-e3f3da**
```
  @PostMapping("/v1.0/daemon/cloud/cmd")
  public ResponseMeta<Object> receiveCloud(@RequestBody CloudData cloudData) {
    return new ResponseMeta<>(imageService.receiveCloud(cloudData));
  }
```

**What you expected to happen**:
my custom app(listen 900 port) should receive data.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.22.12
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.21.1
- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
  - OS (e.g. `cat /etc/os-release`): centos 7
  - Kernel (e.g. `uname -a`): 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`): v1.12.1
  - Hardware configuration (e.g. `lscpu`): 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                2
On-line CPU(s) list:   0,1
Thread(s) per core:    1
Core(s) per socket:    2
  - OS (e.g. `cat /etc/os-release`): CentOS Linux 7
  - Kernel (e.g. `uname -a`): Linux edge-node-20230726-e3f3da 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

  </details>
