### ISSUE TITLE
Run the edgemark report as follows: "edgemark flag redefined: version"

### ISSUE THREAD

**Issue by charnet1019** [kubeedge/kubeedge#5052]
**What happened**:
Run the edgemark report as follows: "edgemark flag redefined: version"
**What you expected to happen**:
Run successed
**How to reproduce it (as minimally and precisely as possible)**:
run the following command:
```bash
kubectl apply -f hollow_edge_node_template.yaml
```
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.24.7
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.12.4
- <details><summary>Cloud nodes Environment:</summary>

**Comment by ZhengXinwei-F** [comment]
Could you provide the "hollow_edge_node_template.yaml" you're using in more detail?

**Comment by charnet1019** [comment]
hollow_edge_node_template.yaml
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hollow-edge-node
  namespace: edgemark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hollow-edge-node
  template:
    metadata:
      labels:
        app: hollow-edge-node
    spec:
      #nodeSelector:
      #  app: nacos
      volumes:
        - name: local-time
          hostPath:
            path: /etc/localtime
      containers:
        - name: hollow-edgecore
          image: kubeedge/edgemark:v1.12.4
          volumeMounts:
            - name: local-time
              mountPath: /etc/localtime
              readOnly: true
          command:
            - edgemark
          args:
            - --token=$(TOKEN)
            - --name=$(NODE_NAME)
            - --http-server=https://60.60.60.229:10002
            - --websocket-server=60.60.60.229:10000
            #- --alsologtostderr
            #- --v=2
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tokensecret
                  key: tokendata
          resources:
            requests:
              cpu: 20m
              memory: 50M
          securityContext:
            privileged: true
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
```

Run successed when change image version from 1.12.4 to 1.14.2.
But reported "Failed to pull image "registry.k8s.io/e2e-test-images/agnhost:2.32" when i run the follwing cmmand:
```bash
[root@ksmaster01 edgemark]# ./clusterloader --testconfig=config.yaml --provider=kubemark --kubeconfig=${HOME}/.kube/config --v=2
```

config.yaml
```yaml
name: test

namespace:
  number: 1

tuningSets:
- name: Uniform1qps
  qpsLoad:
    qps: 1

steps:
- name: Start measurements
  measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: start
      labelSelector: group = test-pod
      threshold: 20s
  - Identifier: WaitForControlledPodsRunning
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = test-deployment
      operationTimeout: 120s
- name: Create deployment
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: Uniform1qps
    objectBundle:
    - basename: test-deployment
      objectTemplatePath: "deployment.yaml"
      templateFillMap:
        Replicas: 2
- name: Wait for pods to be running
  measurements:
  - Identifier: WaitForControlledPodsRunning
    Method: WaitForControlledPodsRunning
    Params:
      action: gather
- name: Measure pod startup latency
  measurements:
  - Identifier: PodStartupLatency
    Method: PodStartupLatency
    Params:
      action: gather
```

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  labels:
    group: test-deployment
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
      group: test-pod
  template:
    metadata:
      labels:
        group: test-pod
    spec:
      containers:
      - image: kubesphere/pause:3.7
        name: {{.Name}}
```
