### ISSUE TITLE
The pod of the kubeedge edge node cannot mount the "pvc" resource created in the cloud

### ISSUE THREAD

**Issue by wchangc** [kubeedge/kubeedge#5420]
**what happened**:
The pod of the kubeedge edge node cannot mount the "pvc" resource created in the cloud, if the pod is specified like this
```
         volumeMounts:
         - name: jenkins-home
           mountPath: /var/jenkins_home
           subPath: jenkins/jenkins_home
       volumes:
         - name: jenkins-home
           persistentVolumeClaim:
                 claimName: data-pvc
                 readOnly: false
```
Then the pod is always in this "ContainerCreating" state, and I tested it if the pod is specified to run on the cloud node, then there is no problem. But at the edge, the pod is always in the "ContainerCreating" state.

**How to reproduce it (as minimal and precise as possible)**:
1. Deploy nfs-server in the cloud
2. Start an nfs-provisioner in the cloud
3. Start a pod to specify the PVC, and the pod is on the edge node

**environment**:
- Kubernetes version: 1.23.17
- KubeEdge version: 1.13.5
- Docker version: 20.10.9
