### ISSUE TITLE
为什么我的应用没有部署到边缘？

### ISSUE THREAD

**Issue by Watle-fan** [kubeedge/kubeedge#5640]
我部署我的应用的时候显示running了，但应用没在edge，之前没有flannel插件的时候，三个node显示的也是ready，安装flannel插件的时候反倒部署会有报错，flannel插件安装的时候针对cloud和edge需要亲和性设置，那请问是针对edge1和edge2需要有两个yaml文件呢，还是edge端用一个，cloud端用一个就行了呢？我这个应用没部署到边缘端的原因就是因为缺少flannel插件吗？其次，当我应用运行成功的时候，我怎样可以在我的本地，或者通过访问某个地址的方式直接访问我的应用呢？因为之前从来没接触过相关内容，感觉不从下手，该怎么访问呢？有相关教程也可，感谢！
<img width="831" alt="c147f74c5538dfc30121c258ea23e9a" src="https://github.com/kubeedge/kubeedge/assets/78351235/e8237071-0d2b-420b-ba8d-085614a2f04a">
kubeedge：v1.14.5
k8s：v1.24.0

**Comment by letweare** [comment]
你的k8s安装使用的是
containerd 还是docker和cri-docker？

**Comment by Shelley-BaoYue** [comment]
1. If you need run flannel at edge, you can ref to: https://github.com/kubeedge/kubeedge/issues/4521  
2. If you want a deploy scheduled to your edge node, you can set node affinity in deply yaml
3. If you need access edge pods through svc, you can learn more about https://github.com/kubeedge/edgemesh

**Comment by Watle-fan** [comment]
> 你的k8s安装使用的是 containerd 还是docker和cri-docker？

安装使用的是isulad，初始化的时候有指定--remote-runtime-endpoint="unix:///var/run/isulad.sock"这样一个参数

**Comment by Watle-fan** [comment]
> 1. If you need run flannel at edge, you can ref to: [[Instruction] KubeEdge1.12+ integrates with flannel #4521](https://github.com/kubeedge/kubeedge/issues/4521)
> 2. If you want a deploy scheduled to your edge node, you can set node affinity in deply yaml
> 3. If you need access edge pods through svc, you can learn more about https://github.com/kubeedge/edgemesh

However, I reinitialized the k8s cluster, and I haven't installed flannel yet, why does node show ready?
<img width="721" alt="cb4128f71f7eec909a9eb3a8607b265" src="https://github.com/kubeedge/kubeedge/assets/78351235/08ec1701-2bea-4ac3-b232-ec18366d0d2e">

**Comment by letweare** [comment]
> > 你的k8s安装使用的是 containerd 还是docker和cri-docker？
> 
> 安装使用的是isulad，初始化的时候有指定--remote-runtime-endpoint=“unix:///var/run/isulad.sock”这样一个参数

ok，你的边缘节点加入云节点的状态是ready么?

**Comment by Watle-fan** [comment]
是ready，我重新安装了一遍，这次弄上flannel了，显示的ready，但是flannel的edge这个pod运行错误了，我这个edge的yaml的文件的里面的metadata:
  name: kube-flannel-edge-ds写的是这个，会有影响吗？用改成kube-flannel-edge1-ds吗
```
---
kind: Namespace
apiVersion: v1
metadata:
  name: kube-flannel
  labels:
    k8s-app: flannel
    pod-security.kubernetes.io/enforce: privileged
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: flannel
  name: flannel
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/status
  verbs:
  - patch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: flannel
  name: flannel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flannel
subjects:
- kind: ServiceAccount
  name: flannel
  namespace: kube-flannel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: flannel
  name: flannel
  namespace: kube-flannel
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-flannel
  labels:
    tier: node
    k8s-app: flannel
    app: flannel
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "EnableNFTables": false,
      "Backend": {
        "Type": "vxlan"
      }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-flannel-edge-ds
  namespace: kube-flannel
  labels:
    tier: node
    app: flannel
    k8s-app: flannel
spec:
  selector:
    matchLabels:
      app: flannel
  template:
    metadata:
      labels:
        tier: node
        app: flannel
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
              - key: node-role.kubernetes.io/agent
                operator: Exists
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: flannel
      initContainers:
      - name: install-cni-plugin
        image: docker.io/flannel/flannel-cni-plugin:v1.4.1-flannel1
        command:
        - cp
        args:
        - -f
        - /flannel
        - /opt/cni/bin/flannel
        volumeMounts:
        - name: cni-plugin
          mountPath: /opt/cni/bin
      - name: install-cni
        image: docker.io/flannel/flannel:v0.25.1
        command:
        - cp
        args:
        - -f
        - /etc/kube-flannel/cni-conf.json
        - /etc/cni/net.d/10-flannel.conflist
        volumeMounts:
        - name: cni
          mountPath: /etc/cni/net.d
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
      containers:
      - name: kube-flannel
        image: docker.io/flannel/flannel:v0.25.1
        command:
        - /opt/bin/flanneld
        args:
        - --ip-masq
        - --kube-subnet-mgr
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          privileged: false
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: EVENT_QUEUE_DEPTH
          value: "5000"
        volumeMounts:
        - name: run
          mountPath: /run/flannel
        - name: flannel-cfg
          mountPath: /etc/kube-flannel/
        - name: xtables-lock
          mountPath: /run/xtables.lock
      volumes:
      - name: run
        hostPath:
          path: /run/flannel
      - name: cni-plugin
        hostPath:
          path: /opt/cni/bin
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: flannel-cfg
        configMap:
          name: kube-flannel-cfg
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
```
