### ISSUE TITLE
Hoe should helm values config?

### ISSUE THREAD

**Issue by Thatwho** [kubeedge/kubeedge#5655]
**What happened and what you expected to happen**: I had deploy kubeedge on rke2 cluster with helm. For some reason, if I use hostNetwork which is kubeede charts default config, it would failed cause of port conflict，so I had set values like:
```yaml
cloudCore:
  replicaCount: 1
  hostNetWork: false
  image:
    repository: "kubeedge/cloudcore"
    tag: "v1.15.1"
    pullPolicy: "IfNotPresent"
    pullSecrets: []
  securityContext:
    privileged: true
```
and user NodePort as external port for edge connnect:
```yaml
  service:
    enable: true
    type: "NodePort"
    cloudhubNodePort: "31000"
    cloudhubQuicNodePort: "31001"
    cloudhubHttpsNodePort: "31002"
    cloudstreamNodePort: "31003"
    tunnelNodePort: "31004"
    annotations: {}
```
on the other hand, I had config iptablesManager's value like below to enable kubectl logs:
```yaml
iptablesManager:
  enable: true
  mode: "external"
  hostNetWork: true
  image:
    repository: "kubeedge/iptables-manager"
    tag: "v1.12.0"
    pullPolicy: "IfNotPresent"
    pullSecrets: []
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
  labels:
    k8s-app: iptables-manager
    kubeedge: iptables-manager
  annotations: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge
            operator: DoesNotExist
  tolerations: []
  nodeSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 25Mi
```
Fortunately, the edge node has successfully joined and the pod has deployed on the edge node：
```yaml
$ kubectl get node
NAME     STATUS   ROLES                       AGE   VERSION
edge01   Ready    agent,edge                  13h   v1.26.10-kubeedge-v1.15.1
node01   Ready    control-plane,etcd,master   13d   v1.27.13+rke2r1
```
```yaml
$ kubectl get pod -o wide
NAME    READY   STATUS    RESTARTS   AGE   IP          NODE     NOMINATED NODE   READINESS GATES
nginx   1/1     Running   0          27m   10.88.0.6   edge01   <none>           <none>
```
But when I trying to get logs of the pod, I got a 502 error:
```yaml
$ kubectl logs nginx
Error from server: Get "https://192.168.50.15:10351/containerLogs/default/nginx/nginx": proxy error from 127.0.0.1:9345 while dialing 192.168.50.15:10351, code 502: 502 Bad Gateway
```
I can found the iptables rules at the network namespace of cloud-iptables-manager pod：
```bash
$ iptables -t nat -L OUTPUT -n -v
Chain OUTPUT (policy ACCEPT 7631 packets, 458K bytes)
 pkts bytes target     prot opt in     out     source               destination         
66507 3991K TUNNEL-PORT  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubeedge tunnel port */
$ iptables -t nat -L TUNNEL-PORT -n -v
Chain TUNNEL-PORT (2 references)
 pkts bytes target     prot opt in     out     source               destination         
   24  1440 DNAT       tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:10351 to:10.42.0.113:10003
```
Have I migconfigured cahrts value?

**Anything else we need to know?**: 

**Environment**:
- Kubernetes version (use `kubectl version`): v1.27.13+rke2r1
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): v1.15.1

**Comment by Shelley-BaoYue** [comment]
Why is the iptables-manager version 1.12 but the cloudcore version is 1.15？ Although I'm not sure if this is related to the issue

**Comment by Thatwho** [comment]
> Why is the iptables-manager version 1.12 but the cloudcore version is 1.15？ Although I'm not sure if this is related to the issue

I have upgrade both of them to v1.17.0, but the problem still exists. Is there any suggestion to debug this?

**Comment by Thatwho** [comment]
well, I have redeploy v1.17.0 with helm. The values.yaml likes below:
```yaml
appVersion: "1.17.0"

cloudCore:
  replicaCount: 1
  hostNetWork: false
  image:
    repository: "kubeedge/cloudcore"
    tag: "v1.17.0"
    pullPolicy: "IfNotPresent"
    pullSecrets: []
  securityContext:
    privileged: true
  labels:
    k8s-app: kubeedge
    kubeedge: cloudcore
  annotations: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge
            operator: DoesNotExist
  tolerations: []
  nodeSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 512Mi
  strategy: {}
  featureGates:
    requireAuthorization: false
  modules:
    cloudHub:
      # Caution!: Leave this entry to empty will cause CloudCore to exit abnormally once KubeEdge is enabled.
      # At least a public IP Address or an IP which can be accessed by edge nodes must be provided!
      advertiseAddress:
        - "192.168.50.31"
      dnsNames:
        - ""
      nodeLimit: "1000"
      websocket:
        port: 10000
        enable: true
      quic:
        port: 10001
        enable: false
        maxIncomingStreams: "10000"
      https:
        enable: true
    cloudStream:
      enable: true
    dynamicController:
      enable: false
    router:
      enable: false
    taskManager:
      enable: false
  service:
    enable: true
    type: "NodePort"
    cloudhubNodePort: "31000"
    cloudhubQuicNodePort: "31001"
    cloudhubHttpsNodePort: "31002"
    cloudstreamNodePort: "31003"
    tunnelNodePort: "31004"
    annotations: {}

iptablesManager:
  enable: true
  mode: "external"
  hostNetWork: true
  image:
    repository: "kubeedge/iptables-manager"
    tag: "v1.17.0"
    pullPolicy: "IfNotPresent"
    pullSecrets: []
  securityContext:
    capabilities:
      add:
        - NET_ADMIN
        - NET_RAW
  labels:
    k8s-app: iptables-manager
    kubeedge: iptables-manager
  annotations: {}
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/edge
            operator: DoesNotExist
  tolerations: []
  nodeSelector: {}
  resources:
    limits:
      cpu: 200m
      memory: 50Mi
    requests:
      cpu: 100m
      memory: 25Mi
```
and the iptables of the pod iptablesManager likes:
```yaml
/ # iptables -tnat -nL
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
TUNNEL-PORT  0    --  0.0.0.0/0            0.0.0.0/0            /* kubeedge tunnel port */

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
TUNNEL-PORT  0    --  0.0.0.0/0            0.0.0.0/0            /* kubeedge tunnel port */

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain TUNNEL-PORT (2 references)
target     prot opt source               destination         
DNAT       6    --  0.0.0.0/0            0.0.0.0/0            tcp dpt:10351 to:10.42.0.173:10003
```
while the iptables of the host machine does not contain rules with TUNNEL-PORT.
Is this situation normal? Should host machine got the same iptables rule?
