### ISSUE TITLE
Enhancement:  EdgeApplication can deploy directly to target nodes with label-selector , without NodeGroup CRD in the middle

### ISSUE THREAD

**Issue by panpan0000** [kubeedge/kubeedge#5669]
**What would you like to be added/modified**:

It's quite troublesome to maintain so many node-groups if the combination is complex ( the nodes will be group by various dimensions, like by location, by cpu-arch, by model, by gpu-type...etc )

Just like Karamda, it's propagation policy is friendly 
https://karmada.io/zh/docs/userguide/scheduling/resource-propagating/
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-propagation
spec:
  #...
  placement:
    clusterAffinity:
      labelSelector:
        matchExpressions:
        - key: location
          operator: In
          values:
          - us
```

we can just learn from it  as below: 
```
apiVersion: apps.kubeedge.io/v1alpha1
kind: EdgeApplication
spec:
  workloadScope:
    targetNodeGroups:            #     targetNodeGroups:       <-----------
          nodeSelectorTerms:                    <--------------
          - matchExpressions:
              - key: location
                operator: In
                values:
                -  us
          overriders: ....
  workloadTemplate:
      ....
```

**Why is this needed**:
