### ISSUE TITLE
edge node上使用in-cluster模式失败

### ISSUE THREAD

**Issue by JacobLi11** [kubeedge/kubeedge#6051]
**What happened**:
当我在edge node上的pod使用incluster 模式的时候，依旧报错
我在edge node上其他node上执行
echo $KUBERNETES_SERVICE_HOST
显示为空
**What you expected to happen**:
我希望能在1.17.4上能运行 in-cluster 模式
**How to reproduce it (as minimally and precisely as possible)**:
参考文章：
https://release-1-18.docs.kubeedge.io/docs/advanced/inclusterconfig

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"31", GitVersion:"v1.31.3-eks-56e63d8", GitCommit:"7a5334cf6c02f054f69ceef6698ffa059441b7c9", GitTreeState:"clean", BuildDate:"2024-12-03T17:52:44Z", GoVersion:"go1.22.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.31) exceeds the supported minor version skew of +/-1

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):
edgecore 没有--version选项
但是我通过keadm安装的1.17.4
root@ip-172-31-29-125:/home/ubuntu# keadm version
version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"37f922c392adb87805a12f87ed8ecb751970ee89", GitTreeState:"clean", BuildDate:"2024-12-02T12:25:09Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

- <details><summary>Cloud nodes Environment:</summary>

  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>
- <details><summary>Edge nodes Environment:</summary>

  - edgecore version (e.g. `edgecore --version`):
  - Hardware configuration (e.g. `lscpu`):
  - OS (e.g. `cat /etc/os-release`):
  - Kernel (e.g. `uname -a`):
  - Go version (e.g. `go version`):
  - Others:

  </details>

**Comment by JacobLi11** [comment]
@Shelley-BaoYue 可以帮忙看一下吗，感谢🙏

**Comment by JacobLi11** [comment]
我修改了服务的配置，但是edge上的metaserver 无法启动
<img width="958" alt="image" src="https://github.com/user-attachments/assets/11e7445c-4978-4cda-904f-153b95a66bfb" />

**Comment by JacobLi11** [comment]
```yaml
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    metaServer:
      apiAudiences: null
      dummyServer: 169.254.30.10:10550
      enable: true
      server: 127.0.0.1:10550
      serviceAccountIssuers:
      - https://kubernetes.default.svc.cluster.local
      serviceAccountKeyFiles: null
      tlsCaFile: /etc/kubeedge/ca/rootCA.crt
      tlsCertFile: /etc/kubeedge/certs/server.crt
      tlsPrivateKeyFile: /etc/kubeedge/certs/server.key
    remoteQueryTimeout: 60
```
metamanager 配置
