### ISSUE TITLE
multiple edges router manager

### ISSUE THREAD

**Issue by brealisty** [kubeedge/kubeedge#6087]
**What happened and what you expected to happen**:
I know how to deliver messages between one edge with cloud through this docs: https://kubeedge.io/docs/developer/custom_message_deliver/ .

but mutilple edges means write multiple rule-eventbus-rest.yaml to apply every edge node? or just add multiple node name in one yaml file like this:
```yaml
apiVersion: rules.kubeedge.io/v1
kind: Rule
metadata:
  name: my-rule-eventbus-rest
  labels:
    description: test
spec:
  source: "my-eventbus"
  sourceResource: {"topic": "test","node_name": ["edge-node1", "edge-node2"]}
  target: "my-rest"
  targetResource: {"resource":"http://127.0.0.1:8080/hello"}
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): cloudcore：1.13   edgecore：1.13
