### ISSUE TITLE
Not sure how to expose pod running on Windows edge node to other pods or the local LAN

### ISSUE THREAD

**Issue by HaojieZhang6848** [kubeedge/kubeedge#6095]
# What happened and what you expected to happen

## What happened

I have deployed an Edgecore on Windows Server 2022 with `keadm` and deployed a pod to run on the edge node.

However, after some trials, I did not find a way to expose the pod running on the windows edge node to the local LAN or other pods in the cluster.

## What I expected to happen

There should be some way to expose the pod running on the windows edge node to the local LAN or other pods in the cluster.

# How to reproduce it (as minimally and precisely as possible)

## Cloud Component Installation

1. Install k3s v1.31 on an Ubuntu 22.04 server.
2. Install KubeEdge CloudCore v1.19.0 with `keadm` on the Ubuntu server.

### How I installed containerd

I downloaded the file `cri-containerd-1.7.20-windows-amd64.tar.gz` from [here](https://github.com/containerd/containerd/releases/tag/v1.7.20) and extracted it to `C:\Program Files\containerd`.

Then I modified `C:\Program Files\containerd\cni\conf\0-containerd-nat.conf` to the following:

```conf
{
    "cniVersion": "0.2.0",
    "name": "nat",
    "type": "nat",
    "master": "Ethernet",
    "ipam": {
        "subnet": "172.16.0.0/24",
        "routes": [
            {
                "GW": "172.16.0.1"
            }
        ]
    },
    "capabilities": {
        "portMappings": true,
        "dns": true
    }
}
```

Then I runned `C:\Program Files\containerd\containerd.exe --register-service` to register containerd as a service to make it run in background.

### How I installed KubeEdge EdgeCore

I used the `keadm` tool to install the EdgeCore v1.19.0 on the Windows Server 2022.

#### Use HostNetwork to expose the pod to the local LAN

I used the following yaml to deploy a pod running on the windows edge node to run a simple http server. I expect to visit the `simple-server-pod` from local LAN by visiting `http://<windows-edge-node-ip>:8002`. Unfortunately, it did not work. My browser just complained `ERR_CONNECTION_TIMED_OUT`.

The problem is the same approach works on Linux edge node, but not on Windows edge node.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: simple-server-pod
  labels:
    app: simple-server
spec:
  nodeSelector:
    kubernetes.io/hostname: win-6s4080hbac3
  hostNetwork: true
  containers:
  - name: simple-server
    image: python:3.12.8-windowsservercore
    command: ["python", "-m", "http.server",  "8002"]
    ports:
    - containerPort: 8002
      hostPort: 8002
```

#### Use NodePort to expose the pod to the local LAN

I used the following yaml to deploy a pod running on the windows edge node to run a simple http server. I expect to visit the `simple-server-pod` from local LAN by visiting `http://<windows-edge-node-ip>:30080`. Unfortunately, it did not work. My browser still complained `ERR_CONNECTION_TIMED_OUT`.

The problem is the same approach works on Linux edge node, but not on Windows edge node.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: simple-server-pod
  labels:
    app: simple-server
spec:
    nodeSelector:
        kubernetes.io/hostname: win-6s4080hbac3
    containers:
    - name: simple-server
        image: python:3.12.8-windowsservercore
        command: ["python", "-m", "http.server",  "8002"]
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: simple-server-service
spec:
  selector:
    app: simple-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
    nodePort: 30080
  type: NodePort
```

#### Use Edgemesh to expose the service to other pods in the same cluster

I know that edgemesh is a solution for `pod-to-service` communication in KubeEdge cluster. However, from [here](https://hub.docker.com/r/kubeedge/edgemesh-agent/tags) it seems that there is no Windows version of `edgemesh-agent`. So I believe edgemesh will not work on Windows edge node.

# Anything else we need to know?

The following is my `edgecore.yaml` on the Windows Edge Node:

```yaml
apiVersion: edgecore.config.kubeedge.io/v1alpha2
database:
  aliasName: default
  dataSource: C:\var\lib\kubeedge\edgecore.db
  driverName: sqlite3
kind: EdgeCore
modules:
  dbTest:
    enable: false
  deviceTwin:
    dmiSockPath: /etc/kubeedge/dmi.sock
    enable: true
  edgeHub:
    enable: true
    heartbeat: 15
    httpServer: https://192.168.1.89:10002
    messageBurst: 60
    messageQPS: 30
    projectID: e632aba927ea4ac2b575ec1603d56f10
    quic:
      enable: false
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.1.89:10001
      writeDeadline: 15
    rotateCertificates: true
    tlsCaFile: c:\etc\kubeedge\ca\rootCA.crt
    tlsCertFile: c:\etc\kubeedge\certs\server.crt
    tlsPrivateKeyFile: c:\etc\kubeedge\certs\server.key
    token: ""
    websocket:
      enable: true
      handshakeTimeout: 30
      readDeadline: 15
      server: 192.168.1.89:10000
      writeDeadline: 15
  edgeStream:
    enable: false
    handshakeTimeout: 30
    readDeadline: 15
    server: 192.168.1.89:10004
    tlsTunnelCAFile: c:\etc\kubeedge\ca\rootCA.crt
    tlsTunnelCertFile: c:\etc\kubeedge\certs\server.crt
    tlsTunnelPrivateKeyFile: c:\etc\kubeedge\certs\server.key
    writeDeadline: 15
  edged:
    enable: true
    hostnameOverride: win-6s4080hbac3
    maxContainerCount: -1
    maxPerPodContainerCount: 1
    minimumGCAge: 0s
    podSandboxImage: kubeedge/pause:3.6
    registerNodeNamespace: default
    registerSchedulable: true
    reportEvent: false
    rootDirectory: c:\var\lib\edged
    tailoredKubeletConfig:
      address: 127.0.0.1
      cgroupsPerQOS: false
      clusterDomain: cluster.local
      configMapAndSecretChangeDetectionStrategy: Get
      containerLogMaxFiles: 5
      containerLogMaxSize: 10Mi
      containerRuntimeEndpoint: npipe://./pipe/containerd-containerd
      contentType: application/json
      cpuCFSQuota: false
      cpuCFSQuotaPeriod: 100ms
      cpuManagerPolicy: none
      cpuManagerReconcilePeriod: 10s
      enableControllerAttachDetach: true
      enableDebugFlagsHandler: true
      enableDebuggingHandlers: true
      enableProfilingHandler: true
      enableSystemLogHandler: true
      eventBurst: 100
      eventRecordQPS: 50
      evictionHard:
        imagefs.available: 15%
        memory.available: 100Mi
        nodefs.available: 10%
      evictionPressureTransitionPeriod: 5m0s
      failSwapOn: false
      fileCheckFrequency: 20s
      hairpinMode: promiscuous-bridge
      imageGCHighThresholdPercent: 85
      imageGCLowThresholdPercent: 80
      imageMaximumGCAge: 0s
      imageMinimumGCAge: 2m0s
      imageServiceEndpoint: npipe://./pipe/containerd-containerd
      iptablesDropBit: 15
      iptablesMasqueradeBit: 14
      localStorageCapacityIsolation: true
      logging:
        flushFrequency: 5s
        format: text
        options:
          json:
            infoBufferSize: "0"
        verbosity: 0
      makeIPTablesUtilChains: true
      maxOpenFiles: 1000000
      maxPods: 110
      memoryManagerPolicy: None
      memorySwap: {}
      memoryThrottlingFactor: 0.9
      nodeLeaseDurationSeconds: 40
      nodeStatusMaxImages: 0
      nodeStatusReportFrequency: 5m0s
      nodeStatusUpdateFrequency: 10s
      oomScoreAdj: -999
      podPidsLimit: -1
      readOnlyPort: 10350
      registerNode: true
      registryBurst: 10
      registryPullQPS: 5
      resolvConf: ""
      runtimeRequestTimeout: 2m0s
      seccompDefault: false
      serializeImagePulls: true
      shutdownGracePeriod: 0s
      shutdownGracePeriodCriticalPods: 0s
      staticPodPath: c:\etc\kubeedge\manifests\
      streamingConnectionIdleTimeout: 4h0m0s
      syncFrequency: 1m0s
      topologyManagerPolicy: none
      topologyManagerScope: container
      volumePluginDir: C:\usr\libexec\kubernetes\kubelet-plugins\volume\exec\
      volumeStatsAggPeriod: 1m0s
    windowsPriorityClass: NORMAL_PRIORITY_CLASS
  eventBus:
    enable: true
    eventBusTLS:
      enable: false
      tlsMqttCAFile: c:\etc\kubeedge\ca\rootCA.crt
      tlsMqttCertFile: c:\etc\kubeedge\certs\server.crt
      tlsMqttPrivateKeyFile: c:\etc\kubeedge\certs\server.key
    mqttMode: 2
    mqttPassword: ""
    mqttPubClientID: ""
    mqttQOS: 0
    mqttRetain: false
    mqttServerExternal: tcp://127.0.0.1:1883
    mqttServerInternal: tcp://127.0.0.1:1884
    mqttSessionQueueSize: 100
    mqttSubClientID: ""
    mqttUsername: ""
  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    metaServer:
      apiAudiences: null
      dummyServer: 169.254.30.10:10550
      enable: false
      server: 127.0.0.1:10550
      serviceAccountIssuers:
      - https://kubernetes.default.svc.cluster.local
      serviceAccountKeyFiles: null
      tlsCaFile: c:\etc\kubeedge\ca\rootCA.crt
      tlsCertFile: c:\etc\kubeedge\certs\server.crt
      tlsPrivateKeyFile: c:\etc\kubeedge\certs\server.key
    remoteQueryTimeout: 60
  serviceBus:
    enable: false
    port: 9060
    server: 127.0.0.1
    timeout: 60
```

I am not familiar with the CNI techonology and container networking on Windows. I appreciate if you can provide some guidance on how to expose the pod running on the Windows edge node to the local LAN. Thanks!

# Environment

Kubernetes version (use `kubectl version`): 
  
```
Client Version: v1.31.4+k3s1
Kustomize Version: v5.4.2
Server Version: v1.31.4+k3s1
```

KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

```
v1.19.0
```
