### ISSUE TITLE
When using KubeEdge, the device model (DeviceModel) does not load or sync correctly in CloudCore

### ISSUE THREAD

**Issue by WFUing** [kubeedge/kubeedge#6132]
**What happened and what you expected to happen**:

When using KubeEdge, the device model (DeviceModel) does not load or sync correctly in CloudCore. Specifically,

I created a DeviceModel

```yaml
apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
  name: camera-model
  namespace: default
spec:
  properties:
    - name: capture_frequency
      description: "摄像头采集帧率（fps），表示每秒采集的帧数"
      type:
        int:
          accessMode: ReadWrite
          defaultValue: 10
          unit: "fps"
    - name: enabled
      description: "摄像头启用状态，true 表示启用，false 表示关闭"
      type:
        boolean:
          accessMode: ReadWrite
          defaultValue: true

```

and a Device

```yaml
apiVersion: devices.kubeedge.io/v1alpha2
kind: Device
metadata:
  name: camera-device
  namespace: default
spec:
  deviceModelRef:
    name: camera-model
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: "kubernetes.io/hostname"
            operator: In
            values:
              - edge3
status:
  twins:
    - propertyName: capture_frequency
      desired:
        metadata:
          type: int
        value: "10"
      reported:
        value: "10"
    - propertyName: enabled
      desired:
        value: "true"
      reported:
        value: "true"
```

Successfully deployed

```
$ kubectl get devicemodels 
NAME           AGE
camera-model   16s
$ kubectl get device
NAME            AGE
camera-device   18s
```

Although the device model cameraa-model has been created in the Kubernetes cluster, CloudCore cannot load the device model, resulting in the inability to correctly bind and synchronize the device instance with the device model.

When I updated the device, there was a problem

as follows:

```bash
$ kubectl logs cloudcore-6875f45599-vw7kv -n kubeedge | grep device
I0208 12:40:54.962162       1 module.go:54] Module devicecontroller registered successfully
I0208 12:40:55.294086       1 core.go:52] starting module devicecontroller
I0208 12:40:55.294209       1 downstream.go:389] Start downstream devicecontroller
I0208 12:40:57.295139       1 upstream.go:66] Start upstream devicecontroller
#1: not found device model for device: camera-device, operation: update
#2: not found device model for device: camera-device, operation: update
#3: not found device model for device: camera-device, operation: update
#4: not found device model for device: camera-device, operation: update
#5: not found device model for device: camera-device, operation: update
#6: not found device model for device: camera-device, operation: update
#7: not found device model for device: camera-device, operation: update
#8: not found device model for device: camera-device, operation: update
#9: not found device model for device: camera-device, operation: update
#10: not found device model for device: camera-device, operation: update
W0208 14:57:29.623842       1 downstream.go:297] Built message resource failed for device, device: camera-device, operation: update, error: required parameter are not set (node id, namespace or resource type)
#1: not found device model for device: camera-device, operation: update
#2: not found device model for device: camera-device, operation: update
#3: not found device model for device: camera-device, operation: update
#4: not found device model for device: camera-device, operation: update
#5: not found device model for device: camera-device, operation: update
#6: not found device model for device: camera-device, operation: update
#7: not found device model for device: camera-device, operation: update
#8: not found device model for device: camera-device, operation: update
#9: not found device model for device: camera-device, operation: update
#10: not found device model for device: camera-device, operation: update
W0208 14:59:42.673671       1 downstream.go:297] Built message resource failed for device, device: camera-device, operation: update, error: required parameter are not set (node id, namespace or resource type)
(scheduler) (base) wds@cloud:~/zhitai/graduate/keas/devices/camera$ kubectl get devicemodels
NAME           AGE
camera-model   10m
(scheduler) (base) wds@cloud:~/zhitai/graduate/keas/devices/camera$ kubectl edit device camera-device
device.devices.kubeedge.io/camera-device edited
(scheduler) (base) wds@cloud:~/zhitai/graduate/keas/devices/camera$ kubectl logs cloudcore-6875f45599-vw7kv -n kubeedge | grep device
I0208 12:40:54.962162       1 module.go:54] Module devicecontroller registered successfully
I0208 12:40:55.294086       1 core.go:52] starting module devicecontroller
I0208 12:40:55.294209       1 downstream.go:389] Start downstream devicecontroller
I0208 12:40:57.295139       1 upstream.go:66] Start upstream devicecontroller
#1: not found device model for device: camera-device, operation: update
#2: not found device model for device: camera-device, operation: update
#3: not found device model for device: camera-device, operation: update
#4: not found device model for device: camera-device, operation: update
#5: not found device model for device: camera-device, operation: update
#6: not found device model for device: camera-device, operation: update
#7: not found device model for device: camera-device, operation: update
#8: not found device model for device: camera-device, operation: update
#9: not found device model for device: camera-device, operation: update
#10: not found device model for device: camera-device, operation: update
W0208 14:57:29.623842       1 downstream.go:297] Built message resource failed for device, device: camera-device, operation: update, error: required parameter are not set (node id, namespace or resource type)
#1: not found device model for device: camera-device, operation: update
#2: not found device model for device: camera-device, operation: update
#3: not found device model for device: camera-device, operation: update
#4: not found device model for device: camera-device, operation: update
#5: not found device model for device: camera-device, operation: update
#6: not found device model for device: camera-device, operation: update
#7: not found device model for device: camera-device, operation: update
#8: not found device model for device: camera-device, operation: update
#9: not found device model for device: camera-device, operation: update
#10: not found device model for device: camera-device, operation: update
W0208 14:59:42.673671       1 downstream.go:297] Built message resource failed for device, device: camera-device, operation: update, error: required parameter are not set (node id, namespace or resource type)
```

**How to reproduce it (as minimally and precisely as possible)**:

That is what I said above.

**Anything else we need to know?**:

I found some source code

```go
	// filter operation
	switch operation {
	case model.InsertOperation:
	case model.DeleteOperation:
	case model.UpdateOperation:
	default:
		klog.Warningf("unknown operation %s for device %s when send device msg", operation, device.Name)
		return
	}
	modelMsg.BuildRouter(modules.DeviceControllerModuleName, constants.GroupResource, modelResource, operation)

	err = dc.messageLayer.Send(*modelMsg)
	if err != nil {
		klog.Errorf("Failed to send device addition message %v, device: %s, operation: %s, error: %v",
			modelMsg, device.Name, operation, err)
	}
}

func (dc *DownstreamController) sendDeviceModelMsg(device *v1beta1.Device, operation string) {
	// send operate msg for device model
	// now it is depended on device, maybe move this code to syncDeviceModel's method
	if device == nil || device.Spec.DeviceModelRef == nil {
		return
	}
	deviceModelID := util.GetResourceID(device.Namespace, device.Spec.DeviceModelRef.Name)
	var edgeDeviceModel any
	var ok bool
	err := retry.Do(
		func() error {
			edgeDeviceModel, ok = dc.deviceModelManager.DeviceModel.Load(deviceModelID)
			if !ok {
				return fmt.Errorf("not found device model for device: %s, operation: %s", device.Name, operation)
			}
			return nil
		},
```

It is dc.deviceModelManager.DeviceModel.Load, and the deviceModelID cannot be loaded

**Environment**:
- Kubernetes version (use `kubectl version`):1.27.0
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):1.19.0

**Comment by WFUing** [comment]
The above problem is a problem with the device and devicemodel versions, and it has now been solved.

But new problems arise, the following is the logs of edgecore:

```
Feb 08 14:47:16 edge3 edgecore[30530]: E0208 14:47:16.616067   30530 dmiworker.go:150] udpate device camera-device failed with err: fail to get dmi client of protocol mqtt
```

**Comment by WFUing** [comment]
I have a question, how to write a simple mqtt dmi, is there any ready-made one?

**Comment by wbc6080** [comment]
`udpate device camera-device failed with err: fail to get dmi client of protocol mqtt`

This is because you have not registered a mapper for the mqtt protocol. Mapper is used as a device management plug-in in kubeedge. We have previously implemented a built-in mqtt mapper for reference  https://github.com/kubeedge/mappers-go/tree/main/mappers/device-v1beta1/mqtt-mapper

**Comment by WFUing** [comment]
Yes, I used https://github.com/kubeedge/mappers-go/tree/main/mappers/device-v1beta1/mqtt-mapper, but I don't know how to use mqtt-mapper. First of all, there was a problem when compiling the code.

It was mainly the following two places.

The first

```go
// driver.go
func (c *CustomizedClient) SetDeviceData(visitor *VisitorConfig) error {
	configData := &c.ProtocolConfig.ConfigData
	_, operationInfo, _, err := configData.SplitTopic()
	if operationInfo == DEVICEINfO {
		return errors.New("This is a device config, not to set device data.")
	}
	if err != nil {
		return err
	}
	visitor.ProcessOperation(c.DeviceConfigData)
	return  nil
}

// device.go 
// setVisitor check if visitor property is readonly, if not then set it.
func setVisitor(visitorConfig *driver.VisitorConfig, twin *common.Twin, dev *driver.CustomizedDev) error {
	if twin.Property.PProperty.AccessMode == "ReadOnly" {
		klog.V(3).Infof("%s twin readonly property: %s", dev.Instance.Name, twin.PropertyName)
		return nil
	}
	klog.V(2).Infof("Convert type: %s, value: %s ", twin.Property.PProperty.DataType, twin.ObservedDesired.Value)
	value, err := common.Convert(twin.Property.PProperty.DataType, twin.ObservedDesired.Value)
	if err != nil {
		klog.Errorf("Failed to convert value as %s : %v", twin.Property.PProperty.DataType, err)
		return err
	}
	err = dev.CustomizedClient.SetDeviceData(value, visitorConfig) // error
	if err != nil {
		return fmt.Errorf("%s set device data error: %v", twin.PropertyName, err)
	}
	return nil
}
```

and the second,

```go
// devicestatus.go
// Run timer function.
func (deviceStates *DeviceStates) PushStatesToEdgeCore() {
	states, error := deviceStates.Client.GetDeviceStates() //error
	if error != nil {
		klog.Errorf("GetDeviceStates failed: %v", error)
		return
	}

	statesRequest := &dmiapi.ReportDeviceStatesRequest{
		DeviceName:      deviceStates.DeviceName,
		State:           states,
		DeviceNamespace: deviceStates.DeviceNamespace,
	}

	log.Printf("send statesRequest", statesRequest.DeviceName, statesRequest.State)
	if err := grpcclient.ReportDeviceStates(statesRequest); err != nil {
		klog.Errorf("fail to report device states of %s with err: %+v", deviceStates.DeviceName, err)
	}
}

// driver.go
func (c *CustomizedClient) GetDeviceStates(visitor *VisitorConfig) (string, error) {
	res, err := visitor.getFieldByTag(c.DeviceConfigData)
	if err != nil {
		return common.DeviceStatusOK, nil
	}
	return res, nil

}
```


I tried to understand the code, mainly because the **ParsedMessage** in VisitorConfigData and the **DeviceConfigData** of CustomizedClient are not clearly referred to.


In addition to the code problem, at runtime, the device registration and data update methods, these two topic types, will have errors. In any case, there will be an error. The current method is to configure deviceinfo in the protocol first, and then change it to update

```yaml
apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: camera-device1
  namespace: default
spec:
  deviceModelRef:
    name: camera-model
  nodeName: cloud
  protocol:
    protocolName: mqtt
    configData:
      brokerURL: "192.168.0.103:1883"
      topic: "default/camera-device/deviceinfo/json" // Here Error
  properties:
  - name: capture_frequency
    collectCycle: 10000000000
    reportCycle: 10000000000
    reportToCloud: true
    desired:
      metadata:
        type: int32  
      value: "10"
    visitors:
      protocolName: "mqtt"
      configData:
        dataType: "int"
        operationInfo: 1
        SerializedFormat: 0

  - name: enabled
    collectCycle: 10000000000
    reportCycle: 10000000000
    reportToCloud: true
    desired:
      metadata:
        type: BOOLEAN  
      value: "true"
    visitors:
      protocolName: mqtt
      configData:
        dataType: "boolean"
        operationInfo: 1
        SerializedFormat: 0

status:
  twins:
    - propertyName: capture_frequency
      observedDesired:
        value: "10"
      reported:
        value: "10"
    - propertyName: enabled
      observedDesired:
        value: "true"
      reported:
        value: "true"
```

In general, I don't know how to modify the device configuration through the cloud. Is it through devicetwin? For example, I have a camera at the edge and need to change the camera's acquisition frequency (there is an interface for this modification in the default device, which can be achieved by subscribing to mqtt messages). Can this be achieved through devicetwin?
