### ISSUE TITLE
How to use NodeUpgradeJob?

### ISSUE THREAD

**Issue by Gillefranc** [kubeedge/kubeedge#6170]
**What happened and what you expected to happen**:
I installed KubeEdge version 1.19, with one master node and one edge node.
Created a NodeUpgradeJob like this:
```
apiVersion: operations.kubeedge.io/v1alpha1
kind: NodeUpgradeJob
metadata:
  name: upgrade-edge-node
spec:
  image: kubeedge/installation-package:v1.20.0
```
Applied this using `kubectl apply -f upgrade-job.yaml`

Nothing happens, running `kubectl describe nodeupgradejobs.operations.kubeedge.io upgrade-edge-node` returns this:

```
Name:         upgrade-edge-node
Namespace:    
Labels:       <none>
Annotations:  <none>
API Version:  operations.kubeedge.io/v1alpha1
Kind:         NodeUpgradeJob
Metadata:
  Creation Timestamp:  2025-02-20T11:15:54Z
  Generation:          1
  Resource Version:    13728
  UID:                 136f85e3-b28f-42f0-bf94-a540ffd29995
Spec:
  Image:  kubeedge/installation-package:v1.20.0
Events:   <none>
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.30.10
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`): 1.19.2
