### ISSUE TITLE
pointer error in cloud/pkg/devicecontroller/controller/downstream.go

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#662]
**What happened**:
If you set a desired value for only one parameter the value will used by all twins.
**What you expected to happen**:
the value should only be used by the expected twin
**How to reproduce it (as minimally and precisely as possible)**:
git diff to add more debugging:
--- a/cloud/pkg/devicecontroller/controller/downstream.go
+++ b/cloud/pkg/devicecontroller/controller/downstream.go
@@ -629,7 +629,11 @@ func addUpdatedTwins(new []v1alpha1.Twin, twin map[string]*types.MsgTwin, versio
        opt := false
        optional := &opt
        for _, dtwin := range new {
\+               log.LOGGER.Debugf("twin actual value: %v", dtwin.Reported.Value)
\+               log.LOGGER.Debugf("twin expected value: %v", dtwin.Desired.Value)
\+               log.LOGGER.Debugf("twin expected value: %v", &dtwin.Desired.Value)
                expected := &types.TwinValue{}
\+               log.LOGGER.Debugf("twin expected: %v", expected)
                expected.Value = &dtwin.Desired.Value
                timestamp := time.Now().UnixNano() / 1e6
## Device Instance
```yaml
---
apiVersion: devices.kubeedge.io/v1alpha1
kind: Device
metadata:
        name: cpu-sensor-tag01
        labels:
                description: CPU-Sensor
                model: cpu-sensor
spec:
        deviceModelRef:
                name: cpu-sensor
        nodeSelector:
                nodeSelectorTerms:
                        - matchExpressions:
                                  - key: ''
                                    operator: IN
                                    values:
                                            - edge
status:
        twins:
                - propertyName: CPU_Temperatur
                  reported:
                          metadata:
                                  type: int
                - propertyName: cpu_id
                  reported:
                          value: "0"
                          metadata:
                                  type: int

```
## Device Model
```yaml
---
apiVersion: devices.kubeedge.io/v1alpha1
kind: DeviceModel
metadata:
        label:
                description: CPU-Sensor
        name: cpu-sensor
spec:
        properties:
                - name: CPU_Temperatur
                  description: temperatur in degree celsius
                  type:
                          int:
                                  accessMode: ReadOnly
                                  unit: Degree Celsius
                - name: cpu_id
                  description: set the id of the cpu
                  type:
                          int:
                                  accessMode: ReadWrite
                                  defaultValue: 0

```

- at this point you need an running instance
- kubectl apply -f deviceModel + deviceInstance
- kubectl edit device cpu-sensor-tag01; #and adding the following to cpu_id:
  desired:
    value: "12313"

**Anything else we need to know?**:
By running the above example I produce the above the following output:
2019-06-06 23:11:34.785 +02:00 DEBUG controller/downstream.go:632 twin actual value:
2019-06-06 23:11:34.786 +02:00 DEBUG controller/downstream.go:633 twin expected value:
2019-06-06 23:11:34.786 +02:00 DEBUG controller/downstream.go:634 twin expected value: 0xc0003c47d0
2019-06-06 23:11:34.786 +02:00 DEBUG controller/downstream.go:636 twin expected: &{<nil> <nil>}
2019-06-06 23:11:34.786 +02:00 DEBUG controller/downstream.go:632 twin actual value: 0
2019-06-06 23:11:34.787 +02:00 DEBUG controller/downstream.go:633 twin expected value: 99887766
2019-06-06 23:11:34.787 +02:00 DEBUG controller/downstream.go:634 twin expected value: 0xc0003c47d0
2019-06-06 23:11:34.787 +02:00 DEBUG controller/downstream.go:636 twin expected: &{<nil> <nil>}

**Environment**:
not relevant
