### ISSUE TITLE
Unable to get GPU information of edge nodes

### ISSUE THREAD

**Issue by todayisgood** [kubeedge/kubeedge#779]
**What happened**:

The edge node is GPU type, but can't get the gpu resource info when run `kubectl get node edge-node -o yaml` , olny get the cpu and memory info:
```
allocatable:
    cpu: "4"
    memory: 19816Mi
    pods: "110"
  capacity:
    cpu: "4"
    memory: 19916Mi
    pods: "110"
```

**What you expected to happen**:

The edgecore can report GPU information to the cloud，and can get the  “nvidia.com/gpu”  info  when  run `kubectl get node edge-node -o yaml` , like this:
```
allocatable:
    cpu: 27866m
    memory: 54320540Ki
    nvidia.com/gpu: "1"
    pods: "253"
  capacity:
    cpu: "28"
    memory: 57547164Ki
    nvidia.com/gpu: "1"
    pods: "253"
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
the GPU node info:

```
# nvidia-smi
Mon Jun 24 13:12:09 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            On   | 00000000:00:05.0 Off |                    0 |
| N/A   29C    P8     6W /  75W |      0MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by rohitsardesai83** [comment]
@todayisgood , thanks for reporting this. Did you get a chance to look for possible causes ?

**Comment by rohitsardesai83** [comment]
```yaml
edged:
    register-node-namespace: default
    hostname-override: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
    interface-name: eth0
    edged-memory-capacity-bytes: 7852396000
    node-status-update-frequency: 10 # second
    device-plugin-enabled: false
    gpu-plugin-enabled: false  //------>>> can you set this to true and restart edge_core ?
    image-gc-high-threshold: 80 # percent
    image-gc-low-threshold: 40 # percent
    maximum-dead-containers-per-container: 1
    docker-address: unix:///var/run/docker.sock
    version: v1.10.9-kubeedge-v1.0.0
    runtime-type: docker
    remote-runtime-endpoint: /var/run/containerd/containerd.sock
    remote-image-endpoint: /var/run/containerd/containerd.sock
    runtime-request-timeout: 2
    podsandbox-image: k8s.gcr.io/pause

mesh:
    loadbalance:
        strategy-name: RoundRobin
```

@todayisgood , can you please set  gpu-plugin-enabled: true  in conf/edge.yaml
