### ISSUE TITLE
chang   websocket url format of edge.yaml  

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#920]
**What would you like to be added**:

**Why is this needed**:

currently,   the websocket url format of edge.yaml  like this:
```
edgehub:
    websocket:
        url: wss://0.0.0.0:10000/e632aba927ea4ac2b575ec1603d56f10/fb4ebb70-2783-42b8-b3ef-63e2fd6d242e/events

```
It requires the user to manually change the format of the url。 It often results in user configuration errors。And users often confuse `controller.node-id`, `controller.project-id`, and `edged.hostname-override`.
```
    controller:
        project-id: e632aba927ea4ac2b575ec1603d56f10
        node-id: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
edged:
    hostname-override: fb4ebb70-2783-42b8-b3ef-63e2fd6d242e
```

so I suggest changing the url format ， like quic:
```
edgehub:
    websocket:
        url: 127.0.0.1:10000
```

and edge_core assembles the specific url format itself by `edged.hostname-override`.

In addition, I think project-id is useless at the present stage. Shall we delete it first and add it later if there is multi-tenant demand?

/cc @rohitsardesai83 @sids-b @qizha @kevin-wangzefeng @subpathdev @chendave @edisonxiang @sujithsimon22 @Baoqiang-Zhang @kexun @fisherxu
